const D = (name, o) => ["dec", { name, ...o }];
export default {id:"foundations",num:"01",title:"Core foundations",example:"a URL shortener",
tagline:"Protocols, transport and the performance vocabulary — as decisions, not definitions. Each one: what to say, when to use it, when not to, what it costs, how it fails.",
terms:["REST vs GraphQL vs gRPC","WebSockets vs SSE","TCP vs UDP","HTTP/2 vs HTTP/3","Connection pooling","Blocking vs nonblocking","p99 latency"],
objectives:["Pick a communication protocol from the traffic shape and justify it in one sentence","Pick a real-time mechanism by asking who initiates and how often","Explain why a persistent connection makes the connection server stateful but not the application","Choose TCP or UDP from whether late data still has value","Use latency, throughput, availability and percentiles as decision inputs, not vocabulary"],
sections:[
{id:"protocol",title:"Choosing the API protocol: REST, GraphQL or gRPC",blocks:[
["p","A URL shortener is about as small as a useful system gets. Someone hands you a long URL and gets back a short code. Someone else follows that code and lands on the original page. Two operations. That is the whole product, and it is small enough that every decision in this chapter is visible in it."],
["p","Start with the one that sounds like it wants a fashionable answer: how should the client talk to your server?"],
["p","It does not want a fashionable answer. Ask two duller questions instead. Who is the client — a browser, a phone, or another service you control and deploy? And does the client need to choose the shape of the response, or is one shape right for everybody?"],
["p","For the shortener both answers are easy. The client is a browser or a script, so it is not something you control or can upgrade. And there is exactly one shape a redirect can take. Two answers, and the protocol falls out: REST."],
["p","Now change the system and watch the answers change with it. A profile screen in a mobile app needs the user, their last ten posts, the comment count on each, and the avatar of whoever commented most recently. Over REST that is four or five round trips, and on a phone the round trips — not the bytes — are what the user feels. Here the client genuinely does need to choose the shape of the response, and the answer moves to GraphQL."],
["p","Change it once more. Your API server needs a fraud score before it will issue a code for a submitted URL. Both ends of that call are yours. Nobody outside the company will ever make it. It happens on every single write. You are now paying to serialise JSON and parse it back thousands of times a second in exchange for nothing, and the answer moves to gRPC."],
["p","That is the whole method, and it is worth saying plainly because most candidates never do: REST is the default you move away from, not the one you move toward. If you cannot name the client need that made you leave, you have not made a decision. You have expressed a preference."],
D("REST",{say:"I'd use REST because the API is resource-oriented, externally accessible, easy to debug, and works naturally with browsers, proxies and CDNs.",
use:["Public or partner APIs","CRUD over well-defined resources","Mobile and web clients","Responses that benefit from HTTP caching by URL","Simple request–response traffic — the shortener's create and redirect"],
avoid:["A UI that needs many related resources per screen and makes 6–10 round trips","Clients that need different response shapes","Internal high-volume service-to-service calls where typing and efficiency matter"],
consider:["Over-fetching (all fields) and under-fetching (multiple requests) — mitigate with ?fields=name,email and ?include=posts","Versioning: put /v1/ in the path; additive changes only within a version","Status codes carry meaning: 201 created, 409 conflict, 429 rate-limited, 503 overloaded"],
nuance:"REST is not incapable of field selection or includes; GraphQL just standardises client-controlled selection far more powerfully.",
alt:"GraphQL for flexible clients; gRPC for internal typed calls."}),
D("GraphQL",{say:"I'd consider GraphQL because the frontend needs different combinations of deeply related data across several screens and we want to avoid many round trips.",
use:["Different clients (web, iOS, TV) need different response shapes","Highly connected data — a profile with posts with comments with authors","A frontend that changes faster than the backend","Round-trip count on mobile is the bottleneck"],
avoid:["Simple CRUD — it adds a query layer for nothing","Public APIs where you cannot trust query cost","Responses that must be CDN-cached by URL"],
consider:["N+1 database reads behind resolvers — use batching/dataloader","Deeply nested or expensive queries — enforce depth and complexity limits","Authorization per field, not per endpoint","Caching: queries go over POST so URL caching is unnatural; use persisted queries, client caches, resolver caches","Rate limiting by query cost, not request count; monitoring is harder"],
alt:"REST with fields/include parameters; a BFF (backend-for-frontend) per client."}),
D("gRPC",{say:"I'd use gRPC between internal services because we control both ends, want strongly typed contracts, and care about efficiency and streaming.",
use:["Service-to-service inside the datacenter","Polyglot teams that need generated clients","Streaming (server, client, bidirectional)","High call volume where JSON parsing shows up in profiles"],
avoid:["Browser clients — gRPC-Web exists but is indirect","Public APIs where curl-debuggability and human readability matter"],
consider:["Protocol Buffers over HTTP/2; binary serialisation; schema in .proto files","Propagate deadlines on every call or slow calls cascade","Field renumbering breaks compatibility — only add fields"],
nuance:"The common shape is Browser → REST/GraphQL gateway → gRPC internal services.",
cases:["Shortener: REST everywhere. Two endpoints, public, cacheable, no shaping needed.","Payments platform: REST publicly, gRPC between payments ↔ fraud ↔ ledger."]}),
["h","Why a network call is not a function call"],
["p","gRPC is built to make a remote call look like a local one. You call a method, you get a return value, and the network is hidden. That is the point of it, and it is also the one thing about it worth being nervous about."],
["p","A local function call has two outcomes: it returns, or your process has a much larger problem. A network call has four."],
["p","It succeeds and you hear so. It fails and you hear so. It succeeds and the response is lost on the way back — the work happened, and you have no idea. Or it is still running when you stop waiting, and it may finish correctly one second after you have already decided it did not."],
["p","The third and fourth have no equivalent inside a single process, and no amount of syntactic sugar removes them. A framework that makes the network invisible has not made it reliable; it has only made it easy to forget."],
["p","Chapter 08 is built entirely on those four outcomes. Notice them here, at the exact point where the abstraction first invites you to forget them."],
["t","REST is the safe default; you justify moving off it, never onto it. GraphQL trades server simplicity for client flexibility; gRPC trades debuggability for efficiency and contracts."]
]},
{id:"realtime",title:"Choosing the real-time mechanism: WebSockets, SSE or long polling",blocks:[
["p","The shortener needs none of this, and saying so out loud is worth a sentence in an interview. But add one feature — a dashboard where the owner of a link watches clicks arrive on it — and you have to decide how the browser finds out that something happened."],
["p","The instinct is to reach for WebSockets, because WebSockets are what real-time means to most people. Hold that instinct for one question: who actually needs to send?"],
["p","On the click dashboard, the server sends and the browser listens. The browser\'s only outbound traffic is the occasional ordinary request — change the date range, export a CSV. Frequent traffic one way, rare traffic the other. That is not a bidirectional problem, and buying a bidirectional mechanism means paying for connection management you did not need."],
["p","Now compare a chat window. The user types, the other user types, both sides send constantly, and neither is primarily a listener. There the sockets earn their cost."],
["p","So the test is not how live it feels. It is: does the client send often? If no, Server-Sent Events, which is a single long-lived HTTP response with automatic reconnection built into every browser. If yes, WebSockets. And if updates arrive every thirty seconds or slower, neither — poll, and spend the complexity somewhere it will be noticed."],
D("WebSockets",{say:"Both sides send frequent events, so a persistent bidirectional socket beats polling; I'll accept that connection servers hold state and add a presence layer to route to them.",
use:["Chat and messaging","Multiplayer games","Collaborative editing, live cursors","Presence and typing indicators","Anything where the client also sends many small messages"],
avoid:["The server only pushes and the client sends occasional REST calls — use SSE","Updates every 30 s or slower — poll","Anything behind a CDN or that needs URL caching"],
consider:["Lifecycle: HTTP handshake → upgrade → persistent connection","Load balancers need connection-aware (sticky) routing","Deploys terminate connections — drain gracefully, clients reconnect with backoff","Heartbeats to detect dead connections; limits on connections per server"],
cases:["Client disconnects and reconnects — resume from last sequence number","Messages arrive out of order or duplicated — sequence numbers + client dedup","User connected on three devices — fan out to every gateway holding one","Server holding the connection crashes — clients reconnect elsewhere; state was never only on that server","One user floods messages — per-connection rate limit"],
fails:"A gateway dies and 100k clients reconnect in the same second (thundering herd) — jittered backoff. Idle sockets leak memory. Corporate proxies kill long connections."}),
D("Server-Sent Events",{say:"The server sends and the client mostly listens, so SSE gives us push over a plain HTTP response without managing bidirectional connections.",
use:["Streaming an AI response token by token","Job progress and long-running task status","Live dashboards, notifications, score or price tickers"],
avoid:["The client needs to send frequent messages back — use WebSockets","Binary payloads (SSE is text)"],
consider:["Ordinary long-lived HTTP response; auto-reconnect with Last-Event-ID built into browsers","Client sends normal REST requests in the other direction","Browser connection limits per origin under HTTP/1.1; fine under HTTP/2"],
nuance:"POST /jobs creates the job; GET /jobs/123/events streams progress. Two protocols, one product."}),
D("Long polling",{say:"We need push-like behaviour where persistent connections aren't available, so the client holds a request open and re-issues it on every response.",
use:["Legacy clients or infrastructure that blocks WebSockets/SSE","A fallback path behind the primary mechanism"],
avoid:["Anything new where SSE or WebSockets are available"],
consider:["Each update costs a full HTTP request; hold time vs latency tradeoff","Server must hold many open requests — same concurrency pressure as sockets, less benefit"]}),
["h","Important correction: 'stateful servers'"],
["p","A persistent connection means a particular connection server owns that live socket. It does not make the whole application stateful. Keep durable state in shared storage and let connection servers remember only which clients are attached."],
["ex","Client\n  ↓ WebSocket\nConnection server        (knows: which clients are attached to me)\n  ↓\nPub/sub or message broker (routes: message for user U → whichever\n                           connection servers hold U's devices)\n  ↓\nApplication services + database (own: users, messages, history)"],
["ul",["Connection-aware routing (which server holds user U?)","Pub/sub across connection servers","Heartbeats and reconnection logic","Graceful draining during deploys","A cap on connections per server"]],
["t","WebSockets buy bidirectional low latency and cost you connection management. SSE buys most of the benefit for server-push cases with none of the management. Choose SSE unless the client genuinely talks back often."]
]},
{id:"transport",title:"TCP or UDP, and which HTTP",blocks:[
["p","TCP or UDP is almost never a live decision in an interview. It is on every syllabus because it explains other decisions, and this is the section where that becomes visible."],
["p","One question settles it: if this piece of data arrives late, is it still worth having?"],
["p","A byte of a redirect response — obviously yes. A URL missing its last four characters is not a slightly worse URL, it is garbage. So TCP, which retransmits anything lost and holds everything behind it until the gap is filled."],
["p","A frame of a video call from four hundred milliseconds ago — no. Showing it now would be worse than showing nothing, because the conversation has moved on. So UDP, which sends and forgets and lets the application decide what late means."],
["p","That single test decides it every time, and it is the only part of this you need to carry into the room."],
["h","Where the tradeoff actually bites"],
["p","TCP\'s ordering guarantee is per connection and it is unconditional. If packet three of ten goes missing, packets four through ten may already be sitting in the receiver\'s kernel, complete and correct — and the application is not permitted to see any of them until packet three has been retransmitted and slotted into place."],
["p","That is head-of-line blocking, and it is not a bug. It is the guarantee working as specified. You asked for a byte stream in order; you are getting a byte stream in order."],
["p","It is also the reason HTTP/1.1 browsers open six connections instead of one, the reason HTTP/2 multiplexed many streams onto a single connection and still could not escape the problem underneath, and the reason HTTP/3 moved to QUIC over UDP and rebuilt reliability per stream instead of per connection."],
["p","Each generation is the same negotiation reopened: how much ordering do we really need, and across what scope? Hold that question. It comes back in Chapter 07, where a partitioned log gives you strict ordering inside a partition and flatly refuses it across partitions — for exactly this reason, and at exactly this cost."],
D("TCP",{say:"The data must arrive complete and in order, so TCP's retransmission and ordering are worth the handshake and head-of-line blocking.",
use:["Every API call, page load, file transfer","Anything where a corrupted or missing byte is a bug"],
avoid:["Real-time media where a late frame is worthless","Tiny request–response exchanges where a handshake costs more than a retry (DNS)"],
consider:["Three-way handshake = one round trip before data; TLS adds one more","Head-of-line blocking: a lost packet stalls everything behind it on that connection","Reliability ends at the socket — an acknowledged TCP write is not a processed request; you still need application-level idempotency"]}),
D("UDP",{say:"Late data has no value here, so we send datagrams and never wait for a retransmit.",
use:["Voice and video calls, game state","DNS, NTP","QUIC/HTTP/3 as the substrate"],
avoid:["Anything that must be complete and ordered"],
consider:["You implement whatever reliability you need on top","Firewalls and NATs are less friendly"]}),
D("HTTP/1.1 vs HTTP/2 vs HTTP/3",{say:"HTTP/2 multiplexes on one connection; HTTP/3 moves to QUIC so one lost packet doesn't stall every stream — I'd enable both at the edge and not think about it further.",
use:["HTTP/2: default for browsers and gRPC","HTTP/3: mobile and lossy networks, media-heavy sites"],
avoid:["Spending interview time here unless the interviewer asks — it's an edge-config decision, not an architecture one"],
consider:["HTTP/1.1: one request at a time per connection; browsers open ~6","HTTP/2: many streams on one TCP connection; TCP head-of-line blocking remains","HTTP/3: per-stream reliability over UDP; 1-RTT (or 0-RTT) setup"]}),
D("TLS termination point",{say:"Terminate TLS at the load balancer to centralise certificates and offload CPU; re-encrypt internally because the network we don't control isn't only the public one.",
use:["Terminate at the edge for every public system","Re-encrypt hop-to-hop (mTLS/mesh) for anything with sensitive data"],
avoid:["Plaintext inside the datacenter for regulated data"],
consider:["The edge sees everything in plaintext — it is your most sensitive component","Certificate rotation must be automated or it will expire on a Sunday"]}),
["t","For the shortener none of this is a decision: TCP, HTTPS, HTTP/2 at the edge. Say so in one sentence and move on. The one real choice on the redirect path is 301 vs 302 — see Chapter 16."]
]},
{id:"connections",title:"Connections, pooling and proxies",blocks:[
["p","Every arrow in your diagram is a connection to something, and connections are not free."],
["p","Opening a TCP connection costs a round trip. Adding TLS costs another. If your API server opens a fresh connection to the database for each redirect, the setup costs more than the query — you are spending a millisecond of handshake to buy a hundred microseconds of lookup."],
["p","So nobody does that. Every client keeps a pool of already-open connections and borrows one per query. The interesting question is not whether to pool. It is how big the pool should be, and the answer is emphatically not as big as possible."],
["p","Size it from the database\'s side rather than your own. A database has a level of concurrency it is happiest at, and past that point throughput does not plateau — it falls. More connections mean more context switching, more lock contention and more memory per connection, and less actual work finished. Fifty application servers each holding fifty connections is two and a half thousand connections arriving at a machine that was happiest with two hundred."],
["p","The failure this produces is worth memorising, because it is misdiagnosed constantly. One slow query starts holding connections. The pool drains. Now requests that would have taken a millisecond are queued waiting for a connection that does not exist. Every database dashboard looks healthy — low CPU, low disk, few queries — and every user sees a timeout."],
["p","The database really is fine. The queue in front of it is not. When someone says the database is slow, the first question is whether anything is actually slow inside it, or whether everything is simply waiting to get in."],
D("Connection pooling and keep-alive",{say:"Opening a TCP+TLS connection costs more than the query it carries, so every client keeps a pool; I'll size it to the database's comfortable concurrency, not the web tier's peak.",
use:["App servers → database (always)","Service → service","Any repeated calls to the same host"],
avoid:["Never skip it for databases. Do cap it."],
consider:["Too small: requests queue for a connection while the DB idles","Too large: 50 servers × 50 connections = 2,500 connections the DB spends its time switching between","Central pooler (PgBouncer, RDS Proxy) once app servers exceed a couple of dozen"],
fails:"A slow query holds connections; the pool drains; healthy requests time out waiting for a connection — the classic 'database is fine but everything is slow'."}),
D("Reverse proxy / load balancer at the edge",{say:"Clients see one address; behind it we terminate TLS, balance, cache, rate-limit and hide topology so servers can come and go.",
use:["The public edge of every system"],
avoid:["Nothing — but don't confuse it with a forward proxy (VPN, corporate proxy) which serves clients"],
consider:["Caches responses: a hot redirect can be answered without an app server","Enforces rate limits before requests cost application capacity","Health checks decide who's in rotation — see Chapter 03 for how they cascade"]}),
D("Network partitions and partial failure",{say:"Every arrow in this diagram can lose its response; for each one I'll say what the caller does when it hears nothing.",
use:["Apply this lens to every network call you draw"],
consider:["Four outcomes: success, failure, success-but-response-lost, still-running-at-timeout","A partition means both sides are healthy and each thinks the other is dead","This is why timeouts, retries, idempotency and consensus exist (Chapters 05, 08)"],
cases:["Redirect lookup to the cache times out — fall through to DB or serve 503 fast?","Create-link response lost — client retries — idempotency key returns the same code"]}),
["t","Latency vs bandwidth: a satellite link has huge bandwidth and terrible latency. The shortener is all latency — a few hundred bytes on the user's critical path — so every decision optimises round trips, not throughput."]
]},
{id:"concurrency",title:"Processes, threads and I/O models",blocks:[
["p","Two requests arrive in the same millisecond and both generate the short code a7Gk2Qp. What happens?"],
["p","The tempting answer is to coordinate: keep a set of issued codes in memory, check it before writing, and refuse the second one. It is tempting, it is wrong, and understanding exactly why is worth more than the fix itself."],
["p","It is wrong because that set lives in one process\'s memory, and you have five API servers. Each holds its own set. Each believes it. None of them knows anything about the other four. You have not prevented the collision — you have made it invisible, which is worse, because now it produces a wrong answer instead of an error."],
["p","The fix is to stop coordinating and let the database refuse. Put a unique constraint on the code column, insert, and handle the failure. One of the two requests gets a constraint violation, generates a fresh code and retries. No lock, no shared memory, no agreement between servers — the invariant is enforced in the one place all five servers already trust."],
["p","Hold on to the shape of that move, because you are going to make it repeatedly. It is the same move as the conditional inventory decrement in Chapter 04, the seat reservation in Chapter 16, and the idempotency key in Chapter 02. When several actors have to agree about something, do not build agreement between them. Push the decision down to the single component they all already talk to, and let it say no."],
["h","CPU-bound and I/O-bound want opposite things"],
["p","A redirect handler computes almost nothing. It looks up a code and writes a header. Essentially all of its wall-clock time is spent waiting — on the cache, on the database, on the network. It is I/O-bound."],
["p","Give that work a thread per request and most of your threads are asleep, while the operating system burns real CPU switching between sleeping threads. Give it an event loop and a single thread holds thousands of waiting requests, waking only when data actually arrives."],
["p","Now put an image resizer on that same event loop. It computes for two hundred milliseconds without ever yielding, and for those two hundred milliseconds every other connection on the loop is frozen. The event loop is not slow. It is single-threaded by design, and CPU-bound work violates the design."],
["p","So: I/O-bound work wants concurrency, which means more requests in flight per core. CPU-bound work wants parallelism, which means more cores. Those are different needs with different remedies, and putting both on one pool guarantees neither gets what it wanted."],
D("Threads with shared memory",{say:"Threads share memory so they communicate cheaply; that's exactly what creates races, so anything shared is either immutable, behind a lock, or pushed into the database's atomic operations.",
use:["Parallel CPU work within one process","Request handling in thread-per-request servers"],
avoid:["Thousands of threads mostly waiting on I/O — context switching eats the CPU","Correctness-critical counters in application memory across servers (use the DB or a distributed store)"],
consider:["Race: two threads read-modify-write the same value — atomic ops or locks","Deadlock: A holds 1 wants 2, B holds 2 wants 1 — always acquire in the same order","Processes isolate crashes; threads don't"],
cases:["Two requests generate the same short code at the same instant — don't coordinate in memory; INSERT with a unique constraint and retry on conflict."]}),
D("Nonblocking / event-loop I/O",{say:"The work is I/O-bound — waiting on the database — so an event loop holds thousands of in-flight requests per core instead of a thread per request.",
use:["I/O-bound services: API servers, proxies, gateways, chat connection servers","Anything holding many idle connections"],
avoid:["CPU-heavy handlers (transcoding, hashing, report rendering) on the same loop — one long computation stalls every connection behind it"],
consider:["Async is not faster per request — the DB still takes as long; it's more concurrent per machine","Move CPU work to a worker pool or a queue"],
nuance:"CPU-bound wants parallelism (more cores). I/O-bound wants concurrency (more in-flight per core). Never share one thread pool between them."}),
["ex","Latency ladder — the numbers behind every 'put it in a cache'\nL1 cache         1 ns\nMemory         100 ns\nSSD read       100 µs\nDC round trip  500 µs\nDisk seek       10 ms\nUS coast↔coast  70 ms\nUS↔Europe      150 ms\n\nShortener consequence: a billion links × ~100 B fits in ~100 GB —\nthe whole mapping lives in memory; the DB is the durable copy."]
]},
{id:"performance-vocabulary",title:"Performance vocabulary as requirements",blocks:[
["p","Every word in this section is one you have already heard. The purpose of the section is to stop using them as vocabulary and start using them as requirements, and a requirement is a number attached to a consequence."],
["h","The mean is the wrong number"],
["p","Measure your redirect endpoint for an hour and find an average response time of twelve milliseconds. That sounds healthy. It tells you almost nothing."],
["p","The average is dragged around by outliers and hides the shape of the distribution entirely. Worse, no user experiences the average. Users experience their own request, and the ones deciding whether to come back are the ones on the slow end of it."],
["p","So sort the responses and look at positions instead. The median, p50, is the request in the middle: half your users had a better time than that. The p99 is the request ninety-nine percent of the way up the sorted list: one request in a hundred was worse."],
["p","Set targets on those, and notice the uncomfortable part. The slow requests are rarely random. The account with the most links has the most rows to scan. The customer with the longest history has the largest response to assemble. Your p99 is disproportionately your best users, which is precisely the wrong group to be serving worst."],
["h","Tail latency amplifies"],
["p","Now the arithmetic that makes the tail worse than it first appears."],
["p","Suppose one page load makes fifty backend calls, and each backend has a perfectly respectable one-in-a-hundred chance of being slow. What fraction of page loads contain at least one slow call?"],
["p","Not one percent. It is one minus 0.99 to the fiftieth power — about forty percent."],
["p","Two page loads in five hit somebody\'s p99. This is why a product can feel sluggish while every individual service dashboard looks fine, and why the p99 of your slowest dependency quietly becomes the p50 of your product. It is also a concrete argument against fanning a request out to more services than it needs."],
["h","Availability and durability are different promises"],
["p","A shortener that accepts a link, returns a code, and then loses the row has been perfectly available and has failed completely."],
["p","Availability is whether the system answers. Durability is whether what it already told you stays true. They fail independently, they are bought with different mechanisms — redundancy for one, replication and a durable write for the other — and a requirement that does not say which it means is not yet a requirement."],
["tbl",{cols:["Term","State it as","Consequence for the shortener"],rows:[
["Latency","p99 redirect < 20 ms at the edge","Redirects from cache/CDN; DB only on miss"],
["Throughput","50k redirects/s peak, 500 creates/s","Reads scale horizontally via cache; writes fit one leader"],
["Availability","Redirects 99.99%, creates 99.9%","Read and write paths fail independently"],
["Durability","An issued code never changes or disappears","Ack after replication; codes immutable"],
["Scalability","10× traffic without redesign","Stateless API tier; cache tier grows by node"],
["Read/write ratio","100:1","Invest in caches, not partitioning"],
["Percentiles","p50 5 ms, p99 20 ms","Tail comes from cache misses and GC — measure them, not the mean"]]}],
D("Percentiles over averages",{say:"I'll set the SLO on p99, not the mean — a page that fans out to 50 backends hits someone's p99 on 40% of loads.",
use:["Every latency requirement and every alert"],
avoid:["Quoting averages in an interview"],
consider:["1 − 0.99^50 ≈ 40%: tail latency compounds across fan-out","Tail causes: cache misses, GC pauses, lock contention, cold connections, slow disks","Optimising the mean is cheap; optimising p99 is the real work"]}),
["t","Availability and durability are different promises: a shortener that acknowledges a link and then forgets it has failed durability while being perfectly available. Say which one each requirement is about."]
]}
]};
