const D = (name, o) => ["dec", { name, ...o }];
export default {id:"apis",num:"02",title:"APIs and service architecture",example:"a payments API",
tagline:"The contract between clients and services, and where one service ends — every choice as: what to say, when, when not, what it costs, how it fails.",
terms:["Cursor vs offset","Idempotency key","Versioning","Rate limiting","Monolith vs microservices","API gateway","Stateless","Control vs data plane"],
objectives:["Pick a pagination style from who walks the list","Make a mutation safe to retry and say where the key lives and for how long","Version and rate-limit without breaking clients","Argue monolith vs microservices from a nameable boundary benefit","Choose sync vs async per call and separate control plane from data plane"],
sections:[
{id:"contract",title:"Resource modelling, status codes and validation",blocks:[
["p","A payments API is a promise made to somebody else's code. Unlike a function signature, which you can change on a Tuesday afternoon, you cannot take it back. Every decision in this chapter is shaped by that."],
["p","Here is a real one with a real answer. Should refunding a payment be POST /v1/refundPayment, or POST /v1/payments/{id}/refunds?"],
["p","The second, and not because it is tidier. The second says a refund is a thing. It has an id. It has a status. It can be listed, and it can itself fail and be retried. The first says a refund is something that happens to a payment and leaves nothing behind."],
["p","The moment support asks which refunds are currently pending, the first design has no answer and the second has a GET. Modelling nouns is not a style preference — it is a bet that anything worth doing is worth being able to look at afterwards."],
["p","Status codes are part of the same contract, and the gap between 409 and 422 is not pedantry. A 409 means your request was fine but the world is not in the right state: you cannot refund more than was charged, not yet anyway. A 422 means the request itself was wrong and will be wrong forever."],
["p","The first is worth retrying later. The second never is. A client that cannot tell them apart will either retry forever or give up immediately, and both of those are your fault, not theirs."],
D("Model the domain as things, not actions",{say:"I model the domain as nouns — payments, refunds, customers — and let the HTTP verb carry the action. That makes the API predictable, and every cache and proxy already understands what a GET means.",
use:["Any REST API."],
avoid:["Putting verbs in the URL, like /createPayment. It is a sign the underlying model has not been worked out, and it leaves the result of the action with no identity of its own."],
consider:["The shape is POST /v1/payments to create one, GET /v1/payments/{id} to read it, POST /v1/payments/{id}/refunds to refund it. A refund is a thing with its own id and status, so you can list refunds and retry a failed one.","Status codes have to mean specific things, because clients act on them. 201 created. 404 unknown. 409 the request was fine but the world is not in the right state. 422 the request itself was wrong. 429 slow down. 503 try later.","Validate at the boundary. An amount of minus five hundred, or a currency of dollars rather than usd, should never reach the code that moves money."],
cases:["A refund larger than the original charge should be a 409, not a server error.","An unrecognised field arrives in the request. Decide whether you ignore it or reject it, and write that decision down."],
nuance:"Be specific about which field failed validation, and deliberately vague about authentication failures. Never say the account does not exist — say the credentials are invalid."})
]},
{id:"pagination",title:"Offset or cursor pagination",blocks:[
["p","GET /v1/payments returns a list. How much of it?"],
["p","This sounds like the least interesting decision in the chapter. It is the one most likely to be wrong in a way nobody notices for a year."],
["p","Take the obvious approach. Page one is the twenty newest payments. Page two is OFFSET 20. A user opens page one and reads it. While they read, three payments arrive. They click through to page two — and the three payments they already saw on page one have been pushed down into it. They see three duplicates, and three other payments they will never see at all."],
["p","That is not an edge case. That is what happens to any list that grows while somebody is reading it, which is every list worth paginating."],
["p","A cursor fixes it by remembering where you were rather than how far in you were. Encode the sort key of the last item returned, and the next page asks for everything after that point. New rows arriving above your position no longer shift you, because your position was never a count."],
["p","It is also dramatically cheaper. OFFSET 100000 does not skip a hundred thousand rows — it walks them and throws them away, every time, so the last page of a long list is the slowest query in your system."],
["p","What you give up is jumping to page forty. That is a genuine loss for a human clicking through an admin table and no loss whatsoever for a script walking an export. Humans and small tables, offset. Machines and unbounded tables, cursor."],
["p","One trap worth knowing. The sort key has to be unique, or the cursor will silently skip or repeat rows at the boundary. A timestamp alone is not unique — two payments in the same millisecond are entirely ordinary — which is why the cursor carries the id alongside it as a tiebreaker."],
D("Cursor pagination — remember where you were, not how far in",{say:"Machines walk this list and it grows without limit, so I return an opaque marker representing the last item sent. The next page continues from that point. It costs the same no matter how deep you go, and new rows arriving do not shift what you see.",
use:["Feeds, logs, exports, webhooks — anything a client reads all the way through.","Any table that grows without bound."],
avoid:["Admin screens where a person wants to click straight to page forty."],
consider:["The value you sort by has to be unique, or the marker will skip or repeat rows at the boundary. A timestamp alone is not unique, because two records in the same millisecond are ordinary, so include the id as a tiebreaker.","There is no way to jump to an arbitrary page, because the client only knows where it stopped.","Keep the marker opaque — encode it — so clients cannot build their own and depend on its internals."],
fails:"Sorting on a column that is not unique silently skips or duplicates rows at page boundaries. And a marker that exposes raw ids lets somebody work out how many records you have and guess at others."}),
D("Offset pagination — skip a count, take the next twenty",{say:"This is a small table that a person browses, so asking for page three is fine and lets them move around freely.",
use:["Small tables browsed by people.","Cases where jumping to a specific page matters more than perfect consistency."],
avoid:["Large tables. Skipping a hundred thousand rows does not skip them — the database walks and discards every one, on every request.","Lists that change while being read. New rows arriving push everything down, so the reader sees some records twice and never sees others at all."]}),
D("Only offer filters and sorts you have an index for",{say:"I expose only the filters and sort orders that an index can serve, and I treat adding a new filter parameter as a schema change rather than a small feature.",
use:["Filters that map onto an index you already have."],
avoid:["Letting clients sort by any column they like. That is a full table scan wearing a query parameter."],
consider:["The order of columns in a multi-column index has to match how the query filters and sorts, which Chapter 04 goes into."]})
]},
{id:"idempotency",title:"Idempotency keys",blocks:[
["p","This is the most important section in the chapter, and it exists because of the four outcomes from Chapter 01."],
["p","A client sends POST /v1/payments. The card is charged. The response is lost on the way back — a load balancer recycles, a phone switches from wifi to cellular, anything at all. The client sees a timeout. What should it do?"],
["p","It has two options and both are wrong. Retry, and possibly charge the customer twice. Do not retry, and possibly never charge them while telling them it worked."],
["p","There is no third option available to the client. Which means the third option has to be built by the server."],
["p","An idempotency key is that third option. The client generates a unique value, sends it with the request, and promises to send the same value on every retry of that same intent. The server records the key with the response. When the key arrives a second time, the server does not do the work again — it replays what it said the first time."],
["p","Now retrying is safe. Because retrying is safe, the client can always retry. Because the client can always retry, the lost response stops being a dilemma and becomes routine."],
["p","One detail decides whether any of this works. Claiming the key and doing the work must not be separable in the wrong order. If you charge the card and then write the key, a crash in the gap leaves a charge with no record of it, and the retry charges again — which is precisely the bug the mechanism was built to prevent."],
["p","So claim the key first, with a unique constraint, before anything irreversible happens. That is the same move as the shortener's colliding code in Chapter 01: do not coordinate, let the database refuse."],
["p","Keys need an expiry, and it is worth naming one. Too short and a genuinely slow retry is treated as a new request. Twenty-four hours is the usual answer, and saying it shows you have thought about the fact that this table grows forever otherwise."],
D("Idempotency key — make a retry safe to send",{say:"A lost response makes the client retry, so every request that creates or charges carries a unique value the client generates. We store the response against that value and replay it if the same value arrives again, which means a retry can never charge twice.",
use:["Payments, orders, transfers, sending messages — any change a client might reasonably resend.","Requests that carry many items, where each item gets its own key."],
avoid:["Reads and deletes, and updates that set a value outright. Those are already safe to repeat.","Low-stakes events like analytics, where an occasional duplicate costs nothing."],
consider:["Claiming the key and doing the work must not be separable in the wrong order. If you charge the card and then record the key, a crash in between leaves a charge nobody knows about, and the retry charges again — the exact bug this was meant to prevent. Claim it first, using a uniqueness rule so two simultaneous attempts cannot both succeed.","If the first attempt is still running when the retry arrives, return 409 rather than starting a second one.","Scope keys per customer so two customers cannot collide by chance.","Store the entire response, not just a note that it succeeded, so the retry receives identical output.","Keys need an expiry. Twenty-four hours is usual. Too short and a genuinely slow retry is treated as new; too long and the table grows forever."],
fails:"The key store becomes unavailable. Now you choose: refuse all payments, or process them and risk duplicates. Decide which in advance and say so.",
alt:"Have the client generate the resource id itself and enforce uniqueness on it — the same idea with one table fewer. For work triggered by messages rather than requests, Chapter 07 covers the equivalent.",
cases:["A user double-clicks Pay, so the same key arrives twice and gets the same response.","A client retries with the same key but a different body, which should be rejected as a conflict.","Two browser tabs generate two different keys for the same intent, producing two charges. That is the client's bug, but document it so they know."]}),
["ex","POST /v1/payments\nIdempotency-Key: 8f1c2e0a-…\n{ \"amount\": 4200, \"currency\": \"usd\", \"customer\": \"c_42\" }"],
["t","One extra table and one TTL to choose, versus double charges under exactly the failure that is hardest to reproduce. For money it's mandatory; for a like button it's optional."]
]},
{id:"versioning-auth",title:"Versioning, auth placement and rate limiting",blocks:[
["p","You are going to change this API. The only question is whether the change breaks somebody."],
["p","Adding a field is safe if — and only if — clients ignore fields they do not recognise. That is a rule you have to publish, loudly, because a client that validates strictly will turn your harmless new optional field into an outage on their side and a support ticket on yours."],
["p","What you are asking for has a name: forwards compatibility, meaning old code has to tolerate data written by new code. It is the harder direction of the two, because the old code was written before anyone knew what was coming, and the only way to get it is to have told people the rule in advance."],
["p","Everything that cannot be done additively is a v2, with a deprecation window and usage metrics on v1 — because you cannot switch off a version you are not measuring, and you will not be brave enough to try."],
["h","Who you are, and what you may touch"],
["p","Two words that get used interchangeably and must not be."],
["p","Authentication is who you are. Authorization is what you may do, and crucially, to which object."],
["p","The gateway can settle the first once, for everybody. It cannot settle the second, because it does not know that payment pay_8813 belongs to account acct_42. Only the payments service knows that."],
["p","So if the gateway validates the token and the service then trusts it blindly, a completely valid token can read every payment in the system by changing one id in a URL. This is the single most common finding in real API security audits. It is not an exotic attack. It is changing a number."],
D("Versioning — change the API without breaking anyone",{say:"Anything additive ships inside the current version. Anything that breaks existing clients becomes a new version, with a published end date for the old one and usage figures so we know who is still on it.",
use:["Any API with clients outside your own team."],
avoid:["Changing what an existing field means without changing the version. Clients cannot detect that, so it fails silently in their code.","Versioning individual fields. Keep versions coarse."],
consider:["Tell clients in writing to ignore fields they do not recognise. Without that rule, adding an optional field breaks anyone validating strictly — and it will be your fault by the time it reaches support.","Putting the version in the path is more visible; putting it in a header is cleaner. Either works. Pick one and be consistent."]}),
D("Check who you are once; check what you may touch every time",{say:"The gateway validates the token once, for everybody. The service then checks on every request that this specific payment belongs to this specific caller — otherwise a perfectly valid token reads anyone's data by changing a number in the URL.",
use:["Every API, without exception."],
avoid:["Treating a valid token as proof of permission. This is consistently the most common serious finding in real API security audits, and it is not a sophisticated attack — it is editing a URL."],
consider:["Authentication is who you are. Authorization is what you may do, and to which specific object. The gateway can settle the first and cannot possibly settle the second, because it does not know who owns what.","Chapter 10 covers how tokens themselves work."]}),
D("Rate limiting — cap how fast any one caller can ask",{say:"Each API key gets an allowance that refills steadily and permits short bursts. Going over it returns 429 with a header saying when to try again, and the expensive endpoints get a tighter allowance than the cheap ones.",
use:["Every public endpoint.","Protecting yourself from your own customers' bugs, which cause more incidents than deliberate abuse does."],
avoid:["Limiting only by network address. A whole office shares one address, so you would throttle an entire company because of one person.","Applying the limit after the request has already done the expensive work. Reject early, before it costs anything."],
consider:["The counters have to be shared across all your servers, which usually means Redis — and that makes Redis something your API now depends on. Decide what happens when it is unavailable: fall back to a rough per-server limit rather than failing every request.","Counting requests is simple to explain. Charging by how expensive each request is, is more accurate and much harder to explain. Start simple and add weights for the two or three endpoints that actually hurt."]}),
D("Batch endpoints — many items in one request",{say:"Sending fifty payments in one call removes forty-nine round trips. Each item carries its own idempotency key and gets its own result, so a partial failure is reported per item rather than failing the whole batch.",
use:["High-volume clients, and mobile clients syncing after being offline."],
avoid:["Cases where the items must all succeed or all fail together. That is a transaction, and a batch is not one."],
consider:["Some items succeeding while others fail is the normal case, not an error case. Return a status for each one.","Put a limit on batch size, or somebody will send a hundred thousand items in one request."]})
]},
{id:"boundaries",title:"Monolith, modular monolith or microservices",blocks:[
["p","Now the biggest question in the chapter, and the one most often answered by fashion rather than reasoning."],
["p","You have a payments API. Should payments be its own service?"],
["p","The answer that scores is not yes or no. It is being able to name what the split buys, because a split always costs the same four things, and the costs do not vary by company."],
["p","A function call becomes a network call with four outcomes. A transaction becomes a saga with visible intermediate states. One log becomes distributed tracing. One deploy becomes a coordination problem between teams."],
["p","Against that fixed price you need a specific benefit, and there are only four that count: independent deployment, independent scaling, fault isolation, or a compliance boundary. If you cannot say which of those four you are buying, you are paying the price for nothing."],
["p","Payments buys two of them outright. It carries a PCI compliance scope that is much cheaper to keep small, and its failures are ones you badly want isolated from catalogue browsing, which generates no revenue and should not be able to take payments down with it."],
["p","So payments splits. The catalogue does not, because nobody can name which of the four it would buy."],
["p","And the failure mode of getting this wrong has a name worth carrying: the distributed monolith. Services that must be deployed together, that call each other synchronously in long chains, that share one database underneath. You have paid every cost of splitting and kept every constraint of not splitting."],
D("Monolith — one deployable unit, one database",{say:"One application, one database, one transaction boundary. It is the fastest way to build and the right default until a specific boundary can justify becoming its own service.",
use:["Small teams, early products, and domains whose shape is not settled yet.","Workflows that need a single transaction across the whole domain."],
avoid:["Teams that block each other on every release.","Components with genuinely different scaling needs or regulatory requirements."],
consider:["Enforce module boundaries inside the codebase anyway. That gives you most of the organisational benefit and makes extracting a service later a realistic option rather than a rewrite."]}),
D("Microservices — separate deployables with separate data",{say:"Payments becomes its own service because it needs stricter consistency, a regulatory scope worth keeping small, and the ability to deploy without waiting for anyone. The catalogue stays where it is, because splitting it would buy nothing.",
use:["A boundary that buys one of exactly four things — independent deployment, independent scaling, isolation from another component's failures, or a smaller compliance scope — and you can say which.","Data owned by exactly one service, with a small and stable interface in front of it."],
avoid:["Domains whose boundaries are not yet clear. You will draw them wrong, and moving them afterwards means moving data across a network.","Workflows that needed one transaction across the split.","Small teams. The operational overhead is real and it is paid by the same people writing the features."],
consider:["A function call becomes a network call with four possible outcomes instead of two.","A transaction becomes a multi-step process with visible intermediate states, which Chapter 05 covers.","One log file becomes a tracing problem, which Chapter 09 covers.","You now need a gateway, a way for services to find each other, and something managing traffic between them."],
fails:"The distributed monolith: services that must be released together, that call each other in long synchronous chains, and that share one database. You have paid every cost of splitting and kept every restriction of not splitting.",
alt:"A monolith with enforced internal boundaries, then extracting one service at a time starting with the clearest.",
cases:["Two services constantly need each other's data inside one transaction. The boundary is in the wrong place.","Two services share a database. That is not two services; it is one, with a network in the middle."]}),
["t","Microservices trade a compile-time problem (a large codebase) for a runtime problem (a distributed system). The runtime problem is harder. Name the benefit before you split."]
]},
{id:"plumbing",title:"Gateway, discovery and statelessness",blocks:[
["p","Three pieces of infrastructure appear as soon as there is more than one service. Two are plumbing. One hides a decision that matters more than the other two combined."],
["p","The gateway is one front door: it terminates TLS, checks the token, applies rate limits and routes. Discovery means callers find healthy instances through a registry rather than a hard-coded address, so instances can come and go freely."],
["p","The one that matters is statelessness, and it is routinely misunderstood."],
["p","A stateless service is not one with no state. Payments obviously has state — that is the entire point of it. A stateless service is one where no request depends on which instance handled the previous request."],
["p","That single property is what makes almost everything else in this book affordable. Scaling becomes adding a box. Deploying becomes killing one. A crash costs one request rather than a user's session. Load balancing needs no memory of anything."],
["p","So where does the state go? Into the datastore, into the cache, or into a signed token the client carries. Never into the process."],
["p","There is one honest exception: a connection that is itself the state, like the WebSocket gateway from Chapter 01. There you have knowingly given the property up, and the price is that you now have to plan draining, reconnection and failover by hand."],
D("API gateway — one front door for many services",{say:"A single entry point handles encryption, authentication, rate limiting and routing once, rather than every service doing it slightly differently. Services trust the identity it passes through, and still check ownership themselves.",
use:["More than two or three services behind one public surface."],
avoid:["A single application, where the load balancer already does everything you need.","Letting business logic accumulate in it. It becomes a monolith that every team has to change and nobody owns."],
consider:["Everything goes through it, so it must be redundant and fast.","If its timeout is shorter than a backend's, callers see failures for work that actually completed. Make sure the numbers line up.","It is the natural place to assign the request id that Chapter 09 relies on."]}),
D("Service discovery — finding healthy instances without hardcoding",{say:"Callers look up healthy instances through a registry rather than a fixed address, so instances can be added, removed and replaced without anyone editing configuration.",
use:["Any system with more than a couple of services."],
consider:["The simple version is DNS with short cache times. The more capable version is a registry that services register themselves with. The most capable version puts a small proxy beside every service that also handles retries and encryption between them."]}),
D("Stateless services — any instance can serve any request",{say:"No request depends on which instance handled the previous one, because everything that must persist lives in the datastore, the cache, or a signed token the client carries. Scaling becomes adding a machine and deploying becomes removing one.",
use:["Every request-serving tier, as the default."],
avoid:["Only where the connection itself is the state, such as the servers holding WebSocket connections. There you have given the property up deliberately, and you now owe the system a plan for draining and reconnection."],
consider:["Never hold a half-finished payment in memory between requests. If the process dies, nobody knows it existed.","Pinning users to a particular server is a warning sign. Put the session in a shared store, or in a signed token, and the problem disappears."]})
]},
{id:"sync-async-planes",title:"Sync vs async per call, and the two planes",blocks:[
["p","Every call your payment service makes is one of two kinds: something it needs an answer to, or something it merely needs to have happened."],
["p","The fraud score is the first kind. The answer changes what you do next — approve or decline — so you wait for it, with a timeout, and you decide in advance what to do when fraud is unavailable. Approve small amounts and hold large ones, perhaps. The point is to have an answer, not to have the right one."],
["p","The receipt email is the second kind. Nothing about the payment depends on it. If you make the payment wait for the mail service, you have coupled the availability of taking money to the availability of sending email — a trade nobody would agree to if it were stated in those words, and one that is made accidentally all the time."],
["p","So the test is short. Does the answer change what happens next? Then wait. Otherwise publish an event and move on."],
["p","Getting this backwards is the most common architecture mistake there is, and it is expensive in both directions. Synchronous where it should be asynchronous ties your uptime to your least important dependency. Asynchronous where it should be synchronous means telling a user something succeeded when you do not actually know yet."],
D("Synchronous call — wait, because the answer changes what you do",{say:"Payments waits for the fraud score because the answer decides whether we approve or decline. It gets a hundred and fifty millisecond timeout, and a stated fallback if fraud is unavailable.",
use:["Anything where the caller needs the result to decide what happens next: a fraud check, a stock check, an authorisation."],
avoid:["Side effects the caller does not need confirmed — sending email, recording analytics, updating a search index."],
consider:["Waiting ties your availability and your speed to theirs. If they are down, you are down; if they are slow, you are slow.","Every waiting call needs a timeout and a decision about what to do when it expires. Chapter 08 covers how to choose both."]}),
D("Asynchronous event — publish it and move on",{say:"Once the charge succeeds we publish a payment-succeeded event. The ledger, the receipt service and analytics each react on their own, so payments never waits for any of them.",
use:["Cases where the caller only needs the work accepted, not completed.","One fact that several different systems need to react to."],
avoid:["Cases where the caller must know the outcome before it can respond to the user."],
consider:["Receipt sent is now something that will become true shortly rather than something that is true. Expose a status rather than implying it already happened.","Debugging now crosses a queue, so every message needs to carry the request id, as Chapter 07 covers."]}),
D("Control plane and data plane — separate changing config from using it",{say:"The data plane processes charges. The control plane changes settings and limits. The data plane keeps its last known configuration locally, so a control plane outage means we cannot change settings — not that we cannot take payments.",
use:["Any system whose configuration changes while it is running."],
avoid:["Reading configuration from the control plane on the path of every request. You have just made a rarely-used system a dependency of your most important one."],
consider:["The two have opposite requirements. The data plane must be fast and always available. The control plane changes rarely and can tolerate being down for minutes.","Every data plane machine should keep the last configuration that worked, and keep using it if it cannot fetch a newer one."]}),
["t","Sync where the answer changes the outcome; async where the caller only needs acceptance. Getting this backwards in either direction is the most common architecture mistake in interviews."]
]}
]};
