const D = (name, o) => ["dec", { name, ...o }];
export default {id:"apis",num:"02",title:"APIs and service architecture",example:"a payments API",
tagline:"The contract between clients and services, and where one service ends — every choice as: what to say, when, when not, what it costs, how it fails.",
terms:["Cursor vs offset","Idempotency key","Versioning","Rate limiting","Monolith vs microservices","API gateway","Stateless","Control vs data plane"],
objectives:["Pick a pagination style from who walks the list","Make a mutation safe to retry and say where the key lives and for how long","Version and rate-limit without breaking clients","Argue monolith vs microservices from a nameable boundary benefit","Choose sync vs async per call and separate control plane from data plane"],
sections:[
{id:"contract",title:"Resource modelling, status codes and validation",blocks:[
D("Resource-oriented endpoints",{say:"I model the domain as nouns — payments, refunds, customers — and let HTTP verbs carry the action, so the API is predictable and every proxy and cache understands it.",
use:["Any REST API"],
avoid:["Verbs in URLs (/createPayment) — a sign the resource model isn't thought through"],
consider:["POST /v1/payments · GET /v1/payments/{id} · POST /v1/payments/{id}/refunds","Status codes with meaning: 201 created · 404 unknown · 409 conflicts with state · 422 semantically invalid · 429 limited · 503 back off","Validate at the boundary: amount −500 or currency 'dollars' never reaches business logic"],
cases:["Refund larger than the charge → 409, not 500","Unknown field in request → ignore or 400? Decide and document"],
nuance:"Be precise in validation errors (which field) and vague in auth errors ('invalid credentials', never 'no such account')."})
]},
{id:"pagination",title:"Offset or cursor pagination",blocks:[
D("Cursor pagination",{say:"Machines walk this list and it grows without bound, so I'll return an opaque cursor — the encoded sort key of the last item — which is O(1) per page and stable under inserts.",
use:["Feeds, logs, exports, webhooks, anything a client iterates fully","Tables that grow without bound"],
avoid:["Admin tables where a human jumps to page 40"],
consider:["Sort key must be stable and unique — (created_at, id), since timestamps collide","No jump-to-page N","Cursor is opaque; never let clients construct it"],
fails:"Cursor on a non-unique column skips or repeats rows; cursor exposing raw ids leaks enumeration."}),
D("Offset pagination",{say:"This is a small admin table clicked by humans, so ?page=3 is fine and lets them jump around.",
use:["Small, human-browsed tables","When jump-to-page matters more than stability"],
avoid:["Large tables — OFFSET 100000 walks and discards 100k rows","Lists that change while being read — inserts shift pages, items repeat or vanish"]}),
D("Filtering and sorting",{say:"I'll expose only the filters and sort orders that have an index, and treat a new filter parameter as a schema change.",
use:["Filters that map to an existing index"],
avoid:["Arbitrary ?sort=anything — it's a full scan in disguise"],
consider:["Composite index column order must match the query (Chapter 04)"]})
]},
{id:"idempotency",title:"Idempotency keys",blocks:[
D("Idempotency key",{say:"A lost response makes the client retry, so every POST that creates or charges carries a client-generated key; we store the response against it and replay it on retry — the retry can never charge twice.",
use:["Payments, orders, transfers, message sends — any mutation a client might retry","Batch endpoints: one key per item"],
avoid:["GET, DELETE, idempotent PUT — already safe","Fire-and-forget analytics where a rare duplicate is acceptable"],
consider:["Lookup-and-record must be atomic (unique constraint / conditional write) or two first attempts both run","Return 409 while the first attempt is still in progress","Scope per account so tenants can't collide","Store the full response, not just 'done', so the retry gets identical output","TTL: 24 h is typical — too short duplicates a slow retry, too long grows the table"],
fails:"Key stored after the charge instead of before → crash between them → duplicate. Key store down → either fail closed (no payments) or fail open (risk duplicates); say which.",
alt:"Client-generated resource ids with a unique constraint (same idea, one table fewer). For async paths: idempotent consumers (Chapter 07).",
cases:["User double-clicks Pay → same key → same response","Client retries with a different body under the same key → 422","Two tabs, two keys, same intent → two charges; that's the client's problem — document it"]}),
["ex","POST /v1/payments\nIdempotency-Key: 8f1c2e0a-…\n{ \"amount\": 4200, \"currency\": \"usd\", \"customer\": \"c_42\" }"],
["t","One extra table and one TTL to choose, versus double charges under exactly the failure that is hardest to reproduce. For money it's mandatory; for a like button it's optional."]
]},
{id:"versioning-auth",title:"Versioning, auth placement and rate limiting",blocks:[
D("API versioning",{say:"Additive changes ship within /v1; a breaking change is /v2 with a published deprecation window and usage metrics on the old version before it's turned off.",
use:["Any API with external clients"],
avoid:["Changing behaviour silently under the same version","Versioning every field — coarse major versions only"],
consider:["Tell clients to ignore unknown fields so additive changes are safe","Header versioning is cleaner; path versioning is more visible. Either, consistently"]}),
D("Authentication at the edge, authorization in the service",{say:"The gateway validates the token once; the service checks on every request that this payment belongs to this caller — otherwise a valid token reads anyone's data by changing the id.",
use:["Every API"],
avoid:["Trusting a valid token as proof of permission (broken object-level authorization — the #1 API audit finding)"],
consider:["Authentication = who; authorization = what, on which object","Chapter 10 has the token mechanics"]}),
D("Rate limiting",{say:"A token bucket per API key at the gateway: sustained rate plus a burst; 429 with Retry-After; expensive endpoints limited tighter.",
use:["Every public endpoint","Protecting yourself from your own clients' bugs, not just abuse"],
avoid:["Only per-IP — NAT'd offices share one IP","Limiting after the request has consumed application capacity"],
consider:["Counters in a shared store (Redis) — it becomes a hot dependency; degrade to local approximate buckets if it's down","Per-key fairness is simple; cost-based limits are accurate and harder to explain — start simple, weight the 2–3 endpoints that hurt"]}),
D("Batch endpoints",{say:"Fifty payments in one call cuts round trips fifty-fold, so each item carries its own idempotency key and gets its own result — never all-or-nothing.",
use:["High-volume clients; mobile sync"],
avoid:["When items must be atomic together — that's a transaction, not a batch"],
consider:["Partial failure is the normal case; return per-item status","Cap batch size"]})
]},
{id:"boundaries",title:"Monolith, modular monolith or microservices",blocks:[
D("Monolith",{say:"One deployable, one database, one transaction boundary — the fastest way to build and the right default until a specific boundary earns its own service.",
use:["Small teams, early products, unclear domains","Workflows that need one transaction across the whole domain"],
avoid:["Teams that block each other on every deploy","Components with genuinely different scaling or compliance needs"],
consider:["Enforce internal module boundaries anyway — the modular monolith — so extraction is possible later"]}),
D("Microservices",{say:"Payments is its own service because it needs strict consistency, a PCI compliance boundary and independent deploys; the catalogue stays in the monolith because splitting it buys nothing yet.",
use:["A boundary that buys one of: independent deploy, independent scaling, fault isolation, compliance scope — and you can name which","Data owned by exactly one service with a small stable interface"],
avoid:["Unclear domains — you'll draw the boundaries wrong and pay network costs to move them","Workflows needing one transaction across the split","Small teams — the ops overhead is real"],
consider:["Function call → network call with the four outcomes","Transaction → saga (Chapter 05)","One log → distributed tracing (Chapter 09)","Needs gateway, discovery, mesh or equivalent"],
fails:"The distributed monolith: services that must deploy together, chatty synchronous chains, one slow service stalling everything (Chapter 08).",
alt:"Modular monolith; extract one service at a time starting with the clearest boundary.",
cases:["Two services constantly need each other's data in one transaction → the boundary is wrong","A shared database between services → not microservices, a monolith with extra network"]}),
["t","Microservices trade a compile-time problem (a large codebase) for a runtime problem (a distributed system). The runtime problem is harder. Name the benefit before you split."]
]},
{id:"plumbing",title:"Gateway, discovery and statelessness",blocks:[
D("API gateway",{say:"One front door does TLS, auth, rate limiting and routing once; services trust its identity headers and do object-level authorization themselves.",
use:["More than two or three services behind one public surface"],
avoid:["A single monolith — the load balancer is enough","Letting business logic accumulate in it"],
consider:["It's hot and must be redundant and fast","Gateway timeout shorter than a backend's → phantom failures","Emits one access log with a request id (Chapter 09)"]}),
D("Service discovery",{say:"Callers find healthy instances through a registry or mesh, never a hard-coded IP, so instances can scale and deploy freely.",
use:["Any multi-service system"],
consider:["DNS with short TTLs (simple), registry (Consul/etcd), mesh sidecars (Envoy) that also do retries and mTLS"]}),
D("Stateless services",{say:"Any instance can serve any request because state lives in the store, cache or queue — so scaling is adding a box and deploys are killing one.",
use:["Default for every request-serving tier"],
avoid:["Only where the connection itself is the state: WebSocket gateways, game servers — and then plan draining and failover explicitly"],
consider:["Never keep a payment half-processed in memory across requests","Sticky sessions are a smell; shared session store or signed token instead"]})
]},
{id:"sync-async-planes",title:"Sync vs async per call, and the two planes",blocks:[
D("Synchronous call",{say:"Payments waits for the fraud score because the answer changes the outcome; 150 ms timeout, conservative fallback if fraud is down.",
use:["The caller needs the result to proceed: fraud check, inventory check, auth"],
avoid:["Side effects the caller doesn't need to confirm: email, analytics, indexing"],
consider:["Couples availability and latency of caller to callee","Every sync call needs a timeout and a fallback decision (Chapter 08)"]}),
D("Asynchronous event",{say:"After the charge succeeds we publish PaymentSucceeded; ledger, receipts and analytics consume it independently, so payments never waits on them.",
use:["The caller only needs 'accepted'","Multiple downstream reactions to one fact"],
avoid:["When the caller must know the outcome now"],
consider:["'Receipt sent' is now eventually true — expose status, not a promise","Debugging runs through a queue — trace ids on every message (Chapter 07)"]}),
D("Control plane vs data plane",{say:"The data plane processes charges; the control plane changes config and rate limits. The data plane caches its config locally, so a control-plane outage means 'can't change settings', not 'can't take payments'.",
use:["Any system with configuration that changes at runtime"],
avoid:["Reading config from the control plane on the hot path"],
consider:["Opposite requirements: data plane fast and always up; control plane rarely changes, tolerates minutes of downtime","Last-known-good config on every data-plane node"]}),
["t","Sync where the answer changes the outcome; async where the caller only needs acceptance. Getting this backwards in either direction is the most common architecture mistake in interviews."]
]}
]};
