const D = (name, o) => ["dec", { name, ...o }];
export default {id:"scaling",num:"03",title:"Load balancing and scaling",example:"a news site on election night",
tagline:"From one server to many without a new single point of failure — each technique as: what to say, when, when not, cost, failure mode.",
terms:["Vertical vs horizontal","L4 vs L7","Least connections","Consistent hashing","Sticky sessions","Health checks","Active-active","Autoscaling","Hot partition"],
objectives:["Justify every box in the standard request path from a requirement","Pick L4 or L7 and a routing algorithm from traffic shape","Explain consistent hashing well enough to say why only 1/N keys move","Design health checks that don't cascade","Choose active-passive vs active-active and reason about multi-region","Recognise a hot partition and name three fixes"],
sections:[
{id:"up-or-out",title:"Scale up or scale out",blocks:[
["p","It is eight in the evening on election night. Your news site normally serves two thousand requests a second. Tonight it will serve fifty thousand, almost all of them for a single page, and the traffic will arrive over roughly four minutes."],
["p","Every technique in this chapter is a response to some part of that sentence."],
["p","Start with the crudest fix available: buy a bigger machine. It is unfashionable and it is genuinely underrated. It requires no code changes, no distributed anything, and no new failure modes, and it will get a typical service from five hundred requests a second to several thousand over a weekend."],
["p","It has exactly two limits, and they are hard ones. There is a biggest machine you can buy. And one machine is one failure — every upgrade is a restart, and every crash is an outage."],
["p","Scaling out removes both limits and introduces one precondition that is very easy to skip past: the servers have to be interchangeable."],
["p","If a logged-in user's session lives in server three's memory, then the servers are not interchangeable. Adding a fourth does not add capacity for that user; it adds a machine that cannot serve them, and a fifty percent chance of logging them out on every request."],
["p","So the first real work of scaling out is not adding servers. It is taking the state out of the ones you already have."],
D("Vertical scaling",{say:"We're at 500 rps on one box; a bigger box gets us to 5k with zero code changes, so I'd do that first and use the time to make the tier stateless.",
use:["Early stage, moderate load","Databases — the write leader scales up long before it scales out"],
avoid:["High availability needs — one box is one failure","Past the biggest instance available"],
consider:["Every upgrade is a restart","Cost grows faster than capacity at the top end"]}),
D("Horizontal scaling",{say:"Traffic exceeds one machine and we need to survive a failure, so we add stateless servers behind a balancer and move state into shared stores.",
use:["Traffic beyond one machine","Availability — a failure costs 1/N capacity, not all"],
avoid:["Before the tier is stateless — otherwise every server holds different truth"],
consider:["State must live somewhere all servers reach: DB, cache, queue","Coordination problems move to the datastore"]}),
["ex","Client → DNS → CDN → Load balancer → App servers → Cache → Database\nCDN      static and cacheable pages never reach origin\nLB       one address; servers come and go\nServers  stateless; any one takes any request\nCache    the DB is the slowest, least elastic component\nDatabase source of truth, protected by everything above"],
["t","Scale the stateless tier out and the database up until forced to shard. Justify each box or erase it."]
]},
{id:"balancer",title:"L4 or L7, and which algorithm",blocks:[
["p","Traffic arrives, and something has to decide where it goes."],
["p","The first choice is about what the balancer is allowed to look at. A layer 4 balancer sees addresses and ports — it forwards a TCP connection without ever knowing what is inside it. That makes it fast, protocol-agnostic, and completely blind."],
["p","A layer 7 balancer reads the request. It costs CPU per request and it has to understand the protocol, and in exchange it can do the thing you need tonight: route /live-results to a pool of its own, with its own cache and its own capacity, so that a stampede on one page cannot starve everything else on the site."],
["p","The second choice is how it picks a server, and it comes down to one question: are your requests alike?"],
["p","Round robin assumes they are. Each server gets every Nth request, and if requests take roughly the same time, the load lands evenly. It is simple and it is right far more often than people expect."],
["p","Tonight they are not alike. A results page served from cache takes two milliseconds. An article page with a cold cache and a slow query takes two hundred. Under round robin, the server that happens to receive several slow requests in a row keeps receiving new ones anyway, because round robin has no idea it is struggling."],
["p","Least connections notices. It tracks how many requests each server currently has open and sends the next one to whoever is least busy, which is a rough proxy for whoever is coping. When request durations vary by two orders of magnitude, that proxy is worth the bookkeeping."],
D("L7 load balancer",{say:"An L7 balancer lets me route /live-results to a dedicated pool with a hotter cache, retry idempotent GETs, and shed load per endpoint.",
use:["HTTP at the edge","Routing by path, host, header or cookie","Per-endpoint limits and retries"],
avoid:["Databases, brokers, non-HTTP — use L4"],
consider:["Terminates connections; CPU per request","Must understand every protocol it carries","Itself needs redundancy — anycast/DNS in front"]}),
D("L4 load balancer",{say:"For the database and broker traffic we use L4 — fast, protocol-agnostic, blind to content.",
use:["TCP/UDP services","Raw throughput"],
avoid:["When routing needs to see the request"]}),
["tbl",{cols:["Algorithm","Use when","Tradeoff"],rows:[["Round robin","Uniform, short requests","Ignores load"],["Least connections","Requests vary in duration","Per-backend state; favours idle servers"],["Weighted","Mixed machine sizes; canaries at 1%","Weights drift from reality"],["Random two choices","Large fleets","Nearly least-connections, no coordination"],["Hash on key","Cache locality per user/URL","Uneven under skew"]]}],
D("Sticky sessions",{say:"I'd rather not: pin users only for WebSockets; sessions go in a shared store or a signed cookie so any server can serve anyone.",
use:["Genuinely stateful connections (WebSockets)"],
avoid:["In-memory sessions — server dies, users logged out; heavy users pile on one box"],
consider:["Breaks even distribution and failover"]})
]},
{id:"consistent-hashing",title:"Consistent hashing",blocks:[
["p","You have twelve cache nodes and you need fourteen. How much of the cache survives the change?"],
["p","With the obvious scheme — hash the key, take it modulo the number of nodes — almost none of it."],
["p","Modulo twelve and modulo fourteen are unrelated functions. Nearly every key now maps to a different node than it did a second ago. Around ninety-two percent of your cached entries are effectively gone: still in memory somewhere, but nobody will ever look for them there again."],
["p","Which means ninety-two percent of reads become misses, and every one of those misses goes to the database — at the precise moment you were adding capacity because you were already struggling. The act of scaling up caused the outage."],
["p","Consistent hashing avoids this by not putting the node count into the calculation at all."],
["p","Picture the hash space as a circle. Each node is placed at several points around it. Each key is placed at one point, and belongs to the first node clockwise from where it landed. Nothing in that description mentions how many nodes there are."],
["p","Now add a node. It lands somewhere on the circle and takes ownership of the keys in the arc between itself and the node behind it. Those keys move. Every other key on the circle is exactly where it was, still owned by the same node, still a cache hit."],
["p","The fraction that moves is roughly one over N — about eight percent going from twelve to fourteen. That is not a clever optimisation, it is the theoretical floor: you cannot add capacity without moving some work onto it."],
["p","The several points per node matter more than they look. With one point each, the arcs come out wildly uneven, so some nodes own three times what others do — and worse, removing a node dumps its entire share onto whichever single neighbour sits next to it. A hundred or more virtual points per node smooths both problems away."],
["p","Now the limitation, and tonight it is the one that counts. Consistent hashing distributes keys evenly. It does not distribute load evenly. If forty thousand of your fifty thousand requests are for one key, that key lives on one node, and no hashing scheme ever invented will help. Which is the last section of this chapter."],
D("Consistent hashing",{say:"Cache nodes will be added under load, so I hash keys and nodes onto a ring with virtual nodes; adding a node moves ~1/N of keys instead of ~90% with mod-N.",
use:["Distributed caches, sharded stores, any tier where nodes join and leave and locality matters"],
avoid:["Tiny fixed clusters — fixed slots are simpler","Skewed workloads where one key dominates — hashing spreads keys, not load"],
consider:["Ring is lumpy with few nodes → 100+ virtual nodes per server","Replicate each key to the next K nodes clockwise for redundancy","Clients with inconsistent ring views route the same key differently"],
fails:"Hot key still lands on one node; removing a node without virtual nodes dumps its whole load on one neighbour.",
alt:"Fixed virtual partitions (1,024 slots assigned to nodes, moved whole); directory lookup service.",
cases:["12 cache nodes → 14 on election night: ~14% of entries refill, not 100%","One article is 30% of traffic → the node owning it saturates regardless — see hotspots"]}),
["ex","Adding 2 nodes to 10\nmod-N hashing        ~92% of keys move → every cache cold\nconsistent hashing   ~8% of keys move → the theoretical minimum"]
]},
{id:"health-checks",title:"Health checks and redundancy",blocks:[
["p","A server stops responding. Something has to notice, and the way you build that noticing is a surprisingly good way to cause an outage."],
["p","Here is the version that does it. Every server exposes a health endpoint, and to prove it is really working, that endpoint runs a query against the database."],
["p","The database has a two-second hiccup. Every health check fails at once. The load balancer, working exactly as designed, removes every server from rotation. The site is now down — and the database recovered a second ago."],
["p","The lesson generalises: a health check that depends on something shared turns one component's bad moment into total failure. Liveness checks should be shallow. Is this process alive and able to answer? Nothing more."],
["p","There is a second distinction that matters even more under load. Busy is not dead."],
["p","A server at a hundred percent utilisation is still doing useful work. If your check times out and the balancer evicts it, its traffic moves to the remaining servers — which are also at a hundred percent — so they slow down too, and fail their checks, and are evicted. Ninety seconds later everything is out of rotation and nothing has actually broken."],
["p","That is a cascade, and on election night it is the single most likely way for the site to fall over. It is also why a saturated server should shed load — refuse cheaply and immediately — rather than quietly fail a health check and get itself removed. Chapter 08 takes this apart properly."],
D("Health checks",{say:"Shallow liveness for the balancer so a GC pause doesn't evict a server; deep readiness for deploys so a new instance takes traffic only when its caches and pools are warm.",
use:["Every balanced tier"],
avoid:["Deep checks that hit the DB on every probe — a DB hiccup fails every server at once and the balancer removes all of them"],
consider:["Remove after N consecutive failures, restore after M successes","A busy server should shed load, not fail its check — distinguish 'dead' from 'overloaded'"],
fails:"Aggressive checks + high utilisation = cascade: one eviction overloads the rest, they fail checks, repeat (Chapter 08).",
cases:["5 servers at 80% each; one evicted → remaining at 100%. Plan capacity for losing the largest unit."]}),
D("Active-passive",{say:"The database leader is active-passive: a synchronous standby takes over on failure; simple to reason about, at the cost of idle capacity and a failover moment.",
use:["Stateful systems where write reconciliation is hard"],
avoid:["Stateless tiers — no reason not to be active-active"],
consider:["Standby never serves production until the moment it matters — exercise failover regularly","Failover = detect + promote + repoint: seconds to minutes of downtime"]}),
D("Active-active",{say:"Every app server serves; a failure is just less capacity and every replica is proven daily.",
use:["All stateless tiers","Stateful tiers only with conflict resolution (Chapter 04)"],
consider:["Writes in two places must be reconciled","Capacity headroom must cover losing a whole zone"]}),
D("Multi-region",{say:"Users are global, so reads come from a nearby region; writes go to one leader region — I accept 100 ms on writes to avoid multi-leader conflicts.",
use:["Global user base (latency)","Business cannot survive a regional outage (DR)"],
avoid:["Because it sounds robust — it roughly doubles cost and makes every consistency question hard"],
consider:["Stateless + CDN replicate effortlessly; the database is the problem","Single-leader: distant writes slow. Multi-leader: conflicts. Pick per dataset","Multi-zone within a region is the cheap default; multi-region is the expensive exception"]}),
["p","And notice what autoscaling cannot do for you tonight."],
["p","It reacts in minutes: observe the load, decide, start instances, boot them, warm their caches, add them to the pool. The result arrives in seconds. By the time the new capacity is serving traffic, the moment that needed it has passed and the moment that follows is a different shape entirely."],
["p","Autoscaling handles the shape of an ordinary Tuesday, and it does that well. For a spike you know is coming, you pre-scale hours ahead and pay for capacity you have not used yet. That is not a failure of the tooling; it is what buying insurance looks like."],
D("Autoscaling",{say:"Autoscaling follows the daily curve; for election night I pre-scale 5× hours ahead and let it handle the descent — it reacts in minutes, not seconds.",
use:["Predictable curves, steady growth","Worker pools scaling on queue depth"],
avoid:["Flash crowds and launches — pre-scale","Scaling the database — it doesn't; protect it with caches and queues"],
fails:"Scale-down during a lull then a second wave; scaling on CPU when the bottleneck is the DB."})
]},
{id:"hotspots",title:"Hot partitions and uneven traffic",blocks:[
["p","Everything so far has quietly assumed that traffic spreads out. Tonight it does not."],
["p","Forty thousand of your fifty thousand requests are for one results page. Every technique in this chapter distributes requests evenly across servers — and then every one of those servers turns around and needs the same cache entry from the same cache node. You have balanced the requests perfectly and concentrated the load perfectly."],
["p","This is the difference between a scale problem and a hotspot, and it is worth being able to say out loud: adding servers does not fix a hotspot, because the servers were never the constraint. The constraint is that one piece of data is wanted by everybody at once, and it can only live somewhere."],
["p","There are only a handful of real moves, and all of them trade locality against balance."],
["tbl",{cols:["Fix","Use when","Tradeoff"],rows:[
["Cache closer (CDN / in-process)","Hot object is public or per-server staleness is OK","Hardest to invalidate; 10 s edge TTL removes 99.9% of origin traffic"],
["Replicate the key","One cache node saturates","Write to K nodes, read from any; K× cache writes"],
["Salt the key","Counter or list written/read at extreme rate","results:0…9 spreads load; fan-in on read"],
["Coalesce requests","Hot key expires under load","One refill, others wait ms; needs a lock or single-flight"],
["Better partition key","Hotspot is structural (partition by date)","Partition by article id spreads writes; loses range-by-time locality"],
["Dedicated pool","One tenant/event dominates","Isolation; capacity may idle"]]}],
["p","On election night the move that does most of the work is the first one: cache closer. A ten-second TTL at the CDN sounds uselessly short until you do the arithmetic. Ten seconds means the origin serves that page six times a minute — regardless of whether fifty people are reading it or fifty million."],
["p","Ten seconds of staleness on a page whose numbers change every thirty seconds is invisible to a reader, and it removes something like 99.9% of the traffic before it reaches anything you own. That is the whole trade: a small, bounded lie about freshness in exchange for three orders of magnitude."],
D("Naming the hotspot",{say:"The results page is the hot key. CDN with a 10 s TTL and stale-while-revalidate; counter salted across 8 keys refilled by one worker; the DB sees one write per update, not one read per visitor.",
use:["Name the hotspot before the interviewer does, in every design"],
consider:["Sources: one object (viral), one tenant (bulk import), one time range (today's partition), one accidental key (anonymous user id 0)"],
cases:["Celebrity posts (Ch. 11 fan-out)","Ticket on-sale for one event (Ch. 16)","Today's date partition in a time-range-sharded table (Ch. 04)"]}),
["t","Hotspot mitigation is locality vs balance: caching close is fastest and hardest to invalidate; salting spreads load and costs a fan-in on every read."]
]}
]};
