const D = (name, o) => ["dec", { name, ...o }];
export default {id:"databases",num:"04",title:"Databases and storage",example:"an e-commerce order system",
tagline:"Where truth lives, how it is found, copied and split — every store and technique as a decision with its use-when, don't-use-when, cost and failure.",
terms:["SQL vs NoSQL families","Composite index","Isolation levels","B-tree vs LSM","Leader-follower","Quorum","Shard key","Rebalancing"],
objectives:["Choose a store from access pattern, consistency need and growth axis","Decide which indexes exist and in what column order","Pick an isolation level or conditional write for the one operation that must be airtight","Choose a replication model and handle its lag","Pick a shard key and predict the queries it makes expensive"],
sections:[
{id:"choosing-store",title:"Choosing the store",blocks:[
["p","Four questions, in order: what are the access patterns? what must be consistent with what? how big, along which axis? how flexible must the schema be? 'NoSQL scales better' answers none of them."],
D("Relational database",{say:"Orders need a transaction across order lines and inventory and a CHECK that quantity ≥ 0 — constraints the app can't be trusted to enforce — so they stay relational; I'd shard by customer when writes approach 10k/s.",
use:["Transactions across rows/tables","Constraints and joins","Data with relationships and invariants","Almost every system's core records — it's the default"],
avoid:["Blobs (object storage)","100k+ writes/s of append-only events (wide-column / log)","Objects read whole with no joins and a schema that varies per record (document)"],
consider:["Single writer per shard; horizontal partitioning is a project","Vertical + read replicas carry you to ~10k writes/s"],
fails:"Missing composite index → scan; write skew under snapshot isolation; long transactions holding locks; replication lag after failover."}),
D("Key-value store",{say:"The cart is get/put by user id with a TTL and nothing else — a key-value store, trivially partitionable.",
use:["Sessions, carts, rate-limit counters, caches, feature flags","Lookup by key at any scale"],
avoid:["Any query that isn't 'by key' — 'all carts containing product X' is impossible"],
consider:["Redis (in-memory, rich types), DynamoDB (durable, partitioned)"]}),
D("Document store",{say:"The catalogue is read whole, rarely written, never joined at request time, and its shape varies by category — a document per product, with a cache in front.",
use:["Objects read and written whole","Schema that varies per record","Fast iteration on shape"],
avoid:["Relationships and constraints the DB must enforce","Data that's updated in many small pieces by many writers"],
consider:["Denormalised by design — you maintain copies","Indexes on nested fields exist but cost"]}),
D("Wide-column store",{say:"Order history per customer is write-heavy and read as 'everything for this key in this range' — partition by customer, cluster by time.",
use:["Massive write volume","Partition-then-range access: messages per conversation, events per device, history per user"],
avoid:["Ad-hoc queries; joins; anything not shaped like the partition key"],
consider:["Queries must match the data model exactly — design tables per query","LSM engines: great writes, compaction tax (see engines)"]}),
D("Graph, time-series, search",{say:"Recommendations traverse 'bought together' three hops deep — a graph store; metrics go to a time-series store; the search box is an inverted index fed by change events — never the source of truth.",
use:["Graph: traversals, fraud rings, permission hierarchies","Time-series: metrics, sensors, prices — append-heavy, range by time, downsampled","Search: full text, ranking, facets"],
avoid:["Graph for general storage; search engine as the record of truth"],
consider:["Each extra store is another thing to operate, back up, secure and keep in sync"]}),
D("Object storage",{say:"Product images go to object storage via presigned upload; the database keeps the key and metadata; the CDN serves the bytes.",
use:["Anything over a few hundred KB: images, video, backups, exports"],
avoid:["Records updated in place; low-latency small reads"],
consider:["Effectively unlimited, cents/GB, replicated across zones","Lifecycle rules for cost; no partial updates"]}),
["t","Polyglot persistence gives each workload its ideal store and gives you four databases to run. Every extra store must earn its place with an access pattern the others can't serve."]
]},
{id:"schema-indexes",title:"Schema shape and indexes",blocks:[
D("Normalise vs denormalise",{say:"Products are normalised so a name change happens once; order_lines copies price_cents because the receipt must be frozen at purchase time — a deliberate denormalisation for history, not speed.",
use:["Normalise: single source for facts that change","Denormalise: read performance, or historical accuracy (frozen snapshots)"],
avoid:["Denormalising without saying which copies you now keep in sync and how"],
consider:["Analytical copies are denormalised aggressively — written once by a pipeline, read constantly"]}),
D("Indexes",{say:"The order-history query is WHERE customer_id = ? ORDER BY created_at DESC, so a composite (customer_id, created_at) index serves it in one range scan; I index only what queries filter and sort on.",
use:["Every column your queries filter or sort on — and nothing else"],
avoid:["Indexing everything — each write pays once per index","Low-cardinality booleans; write-heavy tables with indexes nobody reads"],
consider:["Composite index order = query's leading column; (customer_id, created_at) is useless for created_at alone","Covering index = query never touches the table; fastest read, most expensive write","B-tree depth ~4 at a billion rows; a lookup is a handful of page reads"],
fails:"'It has an index' but the column order doesn't match the query; stale statistics make the planner scan; skewed data (one customer with 1M orders) picks a bad plan.",
cases:["New filter parameter on the API → index review, not just a WHERE clause"]}),
["ex","customers  (id, email UNIQUE, name)\nproducts   (id, sku UNIQUE, name, price_cents)\ninventory  (product_id → products, quantity CHECK (quantity >= 0))\norders     (id, customer_id → customers, status, created_at)\norder_lines(order_id, product_id, qty, price_cents)  -- price frozen\nINDEX orders (customer_id, created_at DESC)"]
]},
{id:"transactions",title:"Transactions, isolation and the one airtight operation",blocks:[
D("Local transaction",{say:"Placing an order writes orders, order_lines and decrements inventory in one transaction — all or nothing; the WAL makes the commit durable before the ack.",
use:["Multiple changes in one database that must succeed together"],
avoid:["Across services or shards — that's Chapter 05","Long-running work inside a transaction (holds locks)"],
consider:["ACID: atomic, consistent (constraints hold), isolated, durable (write-ahead log, fsync before ack)","MVCC: readers see a snapshot without blocking writers; only writers to the same row conflict","Deadlocks still happen — the DB aborts one; your code retries"]}),
D("Isolation level and conditional writes",{say:"Everything runs at read committed except the inventory decrement, which is a conditional UPDATE … WHERE quantity >= 1 — atomic, no lock held across the request, and it's the one place a wrong answer costs money.",
use:["Conditional write / SELECT FOR UPDATE / serializable: the one or two operations protecting an invariant (inventory, seats, balances)","Read committed: everything else"],
avoid:["Serializable everywhere — aborts and retries under contention","Read uncommitted — dirty reads, almost never wanted"],
consider:["Read committed: two reads in one txn can differ","Snapshot/repeatable read: consistent snapshot; allows write skew","Serializable: as if one at a time; conflicting txns abort"],
fails:"Write skew: two buyers each read quantity = 1, both write 0 under snapshot isolation — two units sold, one existed.",
cases:["Last unit bought twice → conditional write","Two seats, one payment → transaction spanning both rows, or reservation with expiry","Balance check then debit → same txn or conditional debit WHERE balance >= amount"]}),
["ex","-- the airtight version\nUPDATE inventory SET quantity = quantity - 1\nWHERE product_id = ? AND quantity >= 1;\n-- 0 rows affected → sold out; no lock held across the request"],
["t","Stronger isolation = fewer anomalies + more aborted transactions. Make the one critical operation airtight with a conditional write and leave the rest fast."]
]},
{id:"engines",title:"Storage engine: B-tree or LSM",blocks:[
D("B-tree engine",{say:"Reads are latency-sensitive and updates are in place, so a B-tree engine — Postgres, InnoDB — gives predictable lookups.",
use:["Read-heavy, latency-sensitive, in-place updates — most relational workloads"],
avoid:["Extreme sequential write volume (event logs, time series)"],
consider:["Writes are random I/O: a page somewhere gets rewritten","Predictable read latency: a few page reads to any key"]}),
D("LSM-tree engine",{say:"Order events arrive at 100k/s and are appended, never updated — an LSM engine turns every disk write into a sequential one.",
use:["Write-heavy, append-mostly: events, messages, metrics — Cassandra, RocksDB, LevelDB"],
avoid:["Read-latency-critical point lookups with many overwrites"],
consider:["Memtable → sorted immutable SSTables → background compaction","Reads check several files; Bloom filters skip files that can't have the key","Compaction consumes I/O and can stall writes if it falls behind — the LSM tax"],
nuance:"Sequential vs random I/O is the whole story: spinning disks do ~100s random reads/s vs 100s MB/s sequential. SSDs shrink the gap, don't close it, and wear with random writes. This explains the WAL, LSM trees, Kafka, and bulk loads."})
]},
{id:"replication",title:"Replication: leader-follower, multi-leader or leaderless",blocks:[
D("Leader-follower replication",{say:"One synchronous follower for durability, async followers for reads; a customer's reads route to the leader for a few seconds after a write so they see their own order.",
use:["Almost every primary datastore — reads scale out, a failure doesn't lose data, one place to reason about writes"],
avoid:["Write availability during partitions matters more than consistency (leaderless)","Local write latency in every region is required (multi-leader)"],
consider:["Async: fast, follower lags, leader death loses unreplicated writes","Sync: no lag, no loss, slow follower slows every write; one sync + rest async is the norm","Read-your-writes: route reads to leader after a write, or carry the write's log position and wait for a follower to reach it","Monotonic reads: pin a session to one replica"],
fails:"Failover promotes a lagging follower → lost writes. Old leader comes back → split brain. Needs consensus + fencing (Chapter 05).",
cases:["Customer places order, refreshes, follower 300 ms behind, order missing, places it again → read-your-writes"]}),
D("Multi-leader replication",{say:"Each region accepts writes for local latency; I accept conflict resolution for the catalogue because two merchants rarely edit the same product and last-writer-wins is acceptable there.",
use:["Multi-region with local writes","Offline-capable clients (each device is a leader)"],
avoid:["Data where conflicts lose money — orders, balances"],
consider:["Conflict resolution: last-writer-wins (loses data), merge functions, CRDTs"]}),
D("Leaderless / quorum replication",{say:"N=3, W=2, R=2: every read overlaps every write, so we get consistency without a leader and keep writing during a single-node failure.",
use:["High write availability; Dynamo-style stores (Cassandra, Riak, DynamoDB)"],
avoid:["Transactions, constraints, secondary indexes with strong guarantees"],
consider:["W + R > N for the overlap guarantee; lower W for write speed, lower R for read speed, lose the guarantee at ≤ N","Read repair and anti-entropy fix stale replicas"]}),
["t","Leader-follower: simple, one write point, followers lag. Multi-leader/leaderless: availability and locality, conflicts and repair are yours. Orders → one leader; a globally edited catalogue → maybe not."]
]},
{id:"sharding",title:"Partitioning: whether, how and by what key",blocks:[
D("Sharding",{say:"Partition by customer_id since 95% of queries are per-customer; inventory is per-product and stays on its own smaller store; reporting runs off replicas into the warehouse. The B2B buyer with a million orders is the hotspot risk — I'd split them by (customer_id, year) if needed.",
use:["Data or write rate exceeds one machine — and you can name the growth axis and the dominant access pattern"],
avoid:["Before you can name those — you'll freeze the wrong key","When cross-shard transactions would be common — redesign the boundary instead"],
consider:["Hash partitioning: even, range queries become scatter-gather","Range partitioning: range queries local; monotonic keys (time, sequence) make the newest shard hot","Directory: a lookup service; total flexibility, an extra hop, must be highly available","Consistent hashing or fixed virtual partitions keep rebalancing proportional (Chapter 03)"],
fails:"Hot shard (celebrity, today's date). Wrong key → reshard under load: dual-write, backfill, verify, cut over — weeks. Global secondary index lags because it's itself partitioned and async.",
alt:"Bigger machine + replicas; archive old data; move only the one hot table.",
cases:["Query without the shard key → asks every shard and merges","'All orders for product P' with customer sharding → global secondary index on product_id, eventually consistent","Adding nodes → move whole virtual partitions, not rows"]}),
["ex","Weak:   \"We'll shard the database.\"\nStrong: \"Partition by user_id because most requests are scoped to one\n        user. Cost: global search and celebrity users create cross-\n        shard queries and hotspots — search gets its own index and\n        celebrities get a cache.\""],
["t","Sharding early wastes effort and freezes a key you don't understand; sharding late means migrating under load. The moment is when you can name the axis and the dominant query — usually well before the single node's limit."]
]}
]};
