const D = (name, o) => ["dec", { name, ...o }];
export default {id:"databases",num:"04",title:"Databases and storage",example:"an e-commerce order system",
tagline:"Where truth lives, how it is found, copied and split — every store and technique as a decision with its use-when, don't-use-when, cost and failure.",
terms:["SQL vs NoSQL families","Composite index","Isolation levels","B-tree vs LSM","Leader-follower","Quorum","Shard key","Rebalancing"],
objectives:["Choose a store from access pattern, consistency need and growth axis","Decide which indexes exist and in what column order","Pick an isolation level or conditional write for the one operation that must be airtight","Choose a replication model and handle its lag","Pick a shard key and predict the queries it makes expensive"],
sections:[
{id:"choosing-store",title:"Choosing the store",blocks:[
["p","A customer clicks Buy. What has to be true one second later?"],
["p","The order exists. Its lines exist. The inventory for each item has gone down by exactly the right amount. Their cart is empty. And if any one of those failed, none of them happened."],
["p","That last sentence is the reason this chapter opens with relational databases rather than a menu of alternatives to them."],
["p","The instinct in interviews is to choose a store from the word scale. Scale is the last input, not the first. Four questions come before it, in order. What are the access patterns? What has to be consistent with what? How big does this get, and along which axis? And how much does the shape vary from record to record?"],
["p","Run them on the order. Access patterns: write several related rows together, read them back by order id or by customer. Consistency: the order, its lines and the inventory must agree or none of them may exist. Size: millions of rows a year, which is small. Shape: identical every time. That is a relational database, and it is not a close call."],
["p","Now run the same four questions on the shopping cart, which lives in the same product and gets a completely different answer. Access pattern: get and put by user id, and nothing else — nobody has ever needed to know which carts contain a blue umbrella. Consistency: with nothing at all; a cart is one person's scratch paper. Size: small, and it expires by itself. Shape: uniform."],
["p","That is a key-value store, and putting it in the orders database would spend the one thing the orders database is good at on a workload that does not need it."],
["p","This is the actual skill in this section, and it is not memorising which database is which. It is noticing that one system contains several workloads and they do not all want the same thing. Orders are relational. Carts are key-value. Product images are object storage with a pointer in the database. The search box is an inverted index that is never, under any circumstances, the source of truth."],
["p","And every one of those costs something real: another system to run, back up, secure, monitor, and keep in step with the others. Polyglot persistence is not free sophistication. Make each store earn its place with an access pattern the others genuinely cannot serve."],
D("Relational database",{say:"Orders need a transaction across order lines and inventory and a CHECK that quantity ≥ 0 — constraints the app can't be trusted to enforce — so they stay relational; I'd shard by customer when writes approach 10k/s.",
use:["Transactions across rows/tables","Constraints and joins","Data with relationships and invariants","Almost every system's core records — it's the default"],
avoid:["Blobs (object storage)","100k+ writes/s of append-only events (wide-column / log)","Objects read whole with no joins and a schema that varies per record (document)"],
consider:["Single writer per shard; horizontal partitioning is a project","Vertical + read replicas carry you to ~10k writes/s"],
fails:"Missing composite index → scan; write skew under snapshot isolation; long transactions holding locks; replication lag after failover."}),
D("Key-value store",{say:"The cart is get/put by user id with a TTL and nothing else — a key-value store, trivially partitionable.",
use:["Sessions, carts, rate-limit counters, caches, feature flags","Lookup by key at any scale"],
avoid:["Any query that isn't 'by key' — 'all carts containing product X' is impossible"],
consider:["Redis (in-memory, rich types), DynamoDB (durable, partitioned)"]}),
D("Document store",{say:"The catalogue is read whole, rarely written, never joined at request time, and its shape varies by category — a document per product, with a cache in front.",
use:["Objects read and written whole","Schema that varies per record","Fast iteration on shape"],
avoid:["Relationships and constraints the DB must enforce","Data that's updated in many small pieces by many writers"],
consider:["Denormalised by design — you maintain copies","Indexes on nested fields exist but cost"]}),
D("Wide-column store",{say:"Order history per customer is write-heavy and read as 'everything for this key in this range' — partition by customer, cluster by time.",
use:["Massive write volume","Partition-then-range access: messages per conversation, events per device, history per user"],
avoid:["Ad-hoc queries; joins; anything not shaped like the partition key"],
consider:["Queries must match the data model exactly — design tables per query","LSM engines: great writes, compaction tax (see engines)"]}),
D("Graph, time-series, search",{say:"Recommendations traverse 'bought together' three hops deep — a graph store; metrics go to a time-series store; the search box is an inverted index fed by change events — never the source of truth.",
use:["Graph: traversals, fraud rings, permission hierarchies","Time-series: metrics, sensors, prices — append-heavy, range by time, downsampled","Search: full text, ranking, facets"],
avoid:["Graph for general storage; search engine as the record of truth"],
consider:["Each extra store is another thing to operate, back up, secure and keep in sync"]}),
D("Object storage",{say:"Product images go to object storage via presigned upload; the database keeps the key and metadata; the CDN serves the bytes.",
use:["Anything over a few hundred KB: images, video, backups, exports"],
avoid:["Records updated in place; low-latency small reads"],
consider:["Effectively unlimited, cents/GB, replicated across zones","Lifecycle rules for cost; no partial updates"]}),
["t","Polyglot persistence gives each workload its ideal store and gives you four databases to run. Every extra store must earn its place with an access pattern the others can't serve."]
]},
{id:"schema-indexes",title:"Schema shape and indexes",blocks:[
["p","Here is one row from the order history, written out one fact per line: the customer's name, the customer's email, the product's name, the product's price, the quantity ordered, and the time the order was placed."],
["p","Six facts sitting side by side. They look like facts of the same kind because they are on the same line. They are not."],
["p","Ask which of them change if that customer orders that product again next year. The customer's name: no. Their email: possibly, and if it does change it should change everywhere at once. The product's name: possibly. The product's price: almost certainly."],
["p","Now the harder question. When the price changes, what should happen to last year's order?"],
["p","Nothing at all. The receipt has to keep saying what was actually paid. Which means the price on the order line and the price on the product are not the same fact — they were equal at one instant, and they were never the same thing."],
["p","That is why order_lines carries its own price_cents. It looks like duplication and it is not. Normalising says every fact should live in exactly one place; this is a different fact that happened to start life with the same value. Freezing it is not denormalisation for speed. It is denormalisation for truth."],
["p","Get this wrong and you produce one of the most quietly destructive bugs there is: changing a product's price silently rewrites every historical invoice, and nobody notices until an auditor does."],
D("Normalise vs denormalise",{say:"Products are normalised so a name change happens once; order_lines copies price_cents because the receipt must be frozen at purchase time — a deliberate denormalisation for history, not speed.",
use:["Normalise: single source for facts that change","Denormalise: read performance, or historical accuracy (frozen snapshots)"],
avoid:["Denormalising without saying which copies you now keep in sync and how"],
consider:["Analytical copies are denormalised aggressively — written once by a pipeline, read constantly"]}),
["p","Indexes follow from queries, and the direction of that sentence matters. You do not index a table. You index a question."],
["p","The order-history page asks one: this customer's orders, newest first, twenty at a time. An index on customer_id alone will find the right rows and then have to sort them — every time, for every page. An index on customer_id and created_at together finds them already in order, so the database walks a contiguous run of entries and stops after twenty."],
["p","Column order inside a composite index is not cosmetic. An index on (customer_id, created_at) is useless for a query about created_at on its own, because the entries are sorted by customer first. A phone book sorted by surname is not much help for finding everyone whose first name is James."],
["p","And every index is paid for on every write. Indexing everything is not thoroughness — it is a permanent tax on inserts, collected in exchange for queries nobody runs."],
D("Indexes",{say:"The order-history query is WHERE customer_id = ? ORDER BY created_at DESC, so a composite (customer_id, created_at) index serves it in one range scan; I index only what queries filter and sort on.",
use:["Every column your queries filter or sort on — and nothing else"],
avoid:["Indexing everything — each write pays once per index","Low-cardinality booleans; write-heavy tables with indexes nobody reads"],
consider:["Composite index order = query's leading column; (customer_id, created_at) is useless for created_at alone","Covering index = query never touches the table; fastest read, most expensive write","B-tree depth ~4 at a billion rows; a lookup is a handful of page reads"],
fails:"'It has an index' but the column order doesn't match the query; stale statistics make the planner scan; skewed data (one customer with 1M orders) picks a bad plan.",
cases:["New filter parameter on the API → index review, not just a WHERE clause"]}),
["ex","customers  (id, email UNIQUE, name)\nproducts   (id, sku UNIQUE, name, price_cents)\ninventory  (product_id → products, quantity CHECK (quantity >= 0))\norders     (id, customer_id → customers, status, created_at)\norder_lines(order_id, product_id, qty, price_cents)  -- price frozen\nINDEX orders (customer_id, created_at DESC)"]
]},
{id:"transactions",title:"Transactions, isolation and the one airtight operation",blocks:[
["p","One unit left in stock. Two customers click Buy in the same millisecond. What stops you selling it twice?"],
["p","Most people answer with a transaction. A transaction on its own does not stop it, and this is worth going through slowly, because it is the most commonly misunderstood idea in the chapter."],
["p","Here is the naive version, wrapped in a perfectly correct transaction: read the quantity; check that it is at least one; subtract one; write it back."],
["p","Both transactions read quantity as 1. Both observe that 1 is at least 1. Both write 0. Two units sold, one existed — and neither transaction misbehaved. Each was atomic. Each was durable. Each was internally consistent from its own point of view."],
["p","This has a name: write skew. Two transactions each read something, each make a decision based on what they read, and each write something that invalidates the other's decision. It survives snapshot isolation, which is the default in a great many databases, because snapshot isolation promises you a consistent view of the data. It does not promise that the view is still true by the time you act on it."],
["p","There are three real fixes. Collapse the check and the write into one atomic statement — UPDATE inventory SET quantity = quantity - 1 WHERE product_id = ? AND quantity >= 1 — and treat zero rows affected as sold out. Or take an explicit lock with SELECT FOR UPDATE and hold it for the length of the transaction. Or run at serializable isolation and retry the transaction when the database aborts it."],
["p","The first is usually right, and it is worth seeing why. The condition and the mutation are evaluated together, by the database, in a single step. There is no gap between deciding and doing for another transaction to slip into, and no lock is held across a network round trip while your application thinks about what to do next."],
["p","Notice that this is the same move as the unique constraint in Chapter 01 and the idempotency key in Chapter 02. Three chapters, three different problems, one shape underneath: never check-then-act in application code. Make the database do both at once, and be willing to be told no."],
["p","One more thing, because it decides where you spend your effort: you do not need this everywhere. Nearly every operation in an order system is perfectly safe at read committed. There are usually one or two that are not — the ones touching money or inventory — and those are the ones you make airtight. Serializable everywhere is not caution. It is a throughput problem you chose to have."],
D("Local transaction",{say:"Placing an order writes orders, order_lines and decrements inventory in one transaction — all or nothing; the WAL makes the commit durable before the ack.",
use:["Multiple changes in one database that must succeed together"],
avoid:["Across services or shards — that's Chapter 05","Long-running work inside a transaction (holds locks)"],
consider:["ACID: atomic, consistent (constraints hold), isolated, durable (write-ahead log, fsync before ack)","MVCC: readers see a snapshot without blocking writers; only writers to the same row conflict","Deadlocks still happen — the DB aborts one; your code retries"]}),
D("Isolation level and conditional writes",{say:"Everything runs at read committed except the inventory decrement, which is a conditional UPDATE … WHERE quantity >= 1 — atomic, no lock held across the request, and it's the one place a wrong answer costs money.",
use:["Conditional write / SELECT FOR UPDATE / serializable: the one or two operations protecting an invariant (inventory, seats, balances)","Read committed: everything else"],
avoid:["Serializable everywhere — aborts and retries under contention","Read uncommitted — dirty reads, almost never wanted"],
consider:["Read committed: two reads in one txn can differ","Snapshot/repeatable read: consistent snapshot; allows write skew","Serializable: as if one at a time; conflicting txns abort"],
fails:"Write skew: two buyers each read quantity = 1, both write 0 under snapshot isolation — two units sold, one existed.",
cases:["Last unit bought twice → conditional write","Two seats, one payment → transaction spanning both rows, or reservation with expiry","Balance check then debit → same txn or conditional debit WHERE balance >= amount"]}),
["ex","-- the airtight version\nUPDATE inventory SET quantity = quantity - 1\nWHERE product_id = ? AND quantity >= 1;\n-- 0 rows affected → sold out; no lock held across the request"],
["t","Stronger isolation = fewer anomalies + more aborted transactions. Make the one critical operation airtight with a conditional write and leave the rest fast."]
]},
{id:"engines",title:"Storage engine: B-tree or LSM",blocks:[
["p","Two databases can offer identical SQL and behave completely differently under load, because underneath they are writing to disk in opposite ways."],
["p","A B-tree updates in place. To change a row it locates the page holding it and rewrites that page. Reads are predictable — a handful of page reads reaches any key, at any table size — and writes are scattered randomly across the disk."],
["p","An LSM tree never updates anything. Writes land in an in-memory table which is periodically flushed to disk as a sorted, immutable file. Changing a row appends a new entry. Deleting one appends a tombstone. Nothing already on disk is ever modified."],
["p","That sounds wasteful, and it is the opposite, for one physical reason. Sequential writes are enormously faster than random ones. A spinning disk manages a few hundred random operations a second and a few hundred megabytes a second sequentially — three orders of magnitude apart. SSDs narrow that gap without closing it, and random writes wear them out faster."],
["p","The bill arrives on reads and in the background. A read may have to check several files, which is why LSM engines keep a Bloom filter on each one: a small structure that can cheaply say this key is definitely not in here, letting the read skip the file entirely."],
["p","And those files have to be merged, continuously, forever. That is compaction, and it consumes disk throughput that your incoming writes also want. When compaction falls behind, reads get slower, and eventually writes stall waiting for it. This is the LSM tax, and it is what operators actually complain about at three in the morning."],
["p","So: orders are read-heavy, latency-sensitive and updated in place, which is a B-tree. A stream of order events arriving at a hundred thousand a second and never modified afterwards is an LSM. Same system, different verbs, different engine."],
D("B-tree engine",{say:"Reads are latency-sensitive and updates are in place, so a B-tree engine — Postgres, InnoDB — gives predictable lookups.",
use:["Read-heavy, latency-sensitive, in-place updates — most relational workloads"],
avoid:["Extreme sequential write volume (event logs, time series)"],
consider:["Writes are random I/O: a page somewhere gets rewritten","Predictable read latency: a few page reads to any key"]}),
D("LSM-tree engine",{say:"Order events arrive at 100k/s and are appended, never updated — an LSM engine turns every disk write into a sequential one.",
use:["Write-heavy, append-mostly: events, messages, metrics — Cassandra, RocksDB, LevelDB"],
avoid:["Read-latency-critical point lookups with many overwrites"],
consider:["Memtable → sorted immutable SSTables → background compaction","Reads check several files; Bloom filters skip files that can't have the key","Compaction consumes I/O and can stall writes if it falls behind — the LSM tax"],
nuance:"Sequential vs random I/O is the whole story: spinning disks do ~100s random reads/s vs 100s MB/s sequential. SSDs shrink the gap, don't close it, and wear with random writes. This explains the WAL, LSM trees, Kafka, and bulk loads."})
]},
{id:"replication",title:"Replication: leader-follower, multi-leader or leaderless",blocks:[
["p","The orders database now has followers. What did that buy, and what did it cost?"],
["p","It bought two things that get conflated constantly. Availability: if the leader dies, the data still exists somewhere. And read capacity: any follower can serve a read."],
["p","It did not buy write capacity. Every write still goes through one leader, and every follower then performs that same write itself. Replication copies data. It does not divide it, and no number of followers will make writes go faster."],
["p","The cost shows up immediately, and it is why this section exists. A customer places an order. The write goes to the leader. Their browser reloads the order list — which is a read, so it goes to a follower, which happens to be three hundred milliseconds behind. The order is not there. So they place it again."],
["p","Replication lag is not a malfunction. Asynchronous replication is lag, by definition. It is precisely what you traded away when you decided not to make every write wait for every follower."],
["p","The fix is not to make everything synchronous. It is to notice that this particular reader needs to see this particular write, and to route only that read differently. Send a user's reads to the leader for a few seconds after they write, or have them carry the log position of their write and wait for a follower to catch up to it. Everybody else can keep reading stale data from followers, because nobody else knows the order was placed."],
["p","That is the general shape of all consistency work, and Chapter 05 does it properly. The question is never is this system consistent. It is which reader needs to see which write, and by when."],
["p","One synchronous follower with the rest asynchronous is the usual compromise: no acknowledged write can be lost, and one slow follower cannot stall the leader."],
["p","And the failure worth naming out loud: if the leader dies and you promote a follower that was behind, the writes it never received are simply gone — acknowledged to customers, absent from the database. If the old leader then returns still believing it is the leader, you have two of them. That is split brain, and preventing it is what consensus is for, in the next chapter."],
D("Leader-follower replication",{say:"One synchronous follower for durability, async followers for reads; a customer's reads route to the leader for a few seconds after a write so they see their own order.",
use:["Almost every primary datastore — reads scale out, a failure doesn't lose data, one place to reason about writes"],
avoid:["Write availability during partitions matters more than consistency (leaderless)","Local write latency in every region is required (multi-leader)"],
consider:["Async: fast, follower lags, leader death loses unreplicated writes","Sync: no lag, no loss, slow follower slows every write; one sync + rest async is the norm","Read-your-writes: route reads to leader after a write, or carry the write's log position and wait for a follower to reach it","Monotonic reads: pin a session to one replica"],
fails:"Failover promotes a lagging follower → lost writes. Old leader comes back → split brain. Needs consensus + fencing (Chapter 05).",
cases:["Customer places order, refreshes, follower 300 ms behind, order missing, places it again → read-your-writes"]}),
D("Multi-leader replication",{say:"Each region accepts writes for local latency; I accept conflict resolution for the catalogue because two merchants rarely edit the same product and last-writer-wins is acceptable there.",
use:["Multi-region with local writes","Offline-capable clients (each device is a leader)"],
avoid:["Data where conflicts lose money — orders, balances"],
consider:["Conflict resolution: last-writer-wins (loses data), merge functions, CRDTs"]}),
D("Leaderless / quorum replication",{say:"N=3, W=2, R=2: every read overlaps every write, so we get consistency without a leader and keep writing during a single-node failure.",
use:["High write availability; Dynamo-style stores (Cassandra, Riak, DynamoDB)"],
avoid:["Transactions, constraints, secondary indexes with strong guarantees"],
consider:["W + R > N for the overlap guarantee; lower W for write speed, lower R for read speed, lose the guarantee at ≤ N","Read repair and anti-entropy fix stale replicas"]}),
["t","Leader-follower: simple, one write point, followers lag. Multi-leader/leaderless: availability and locality, conflicts and repair are yours. Orders → one leader; a globally edited catalogue → maybe not."]
]},
{id:"sharding",title:"Partitioning: whether, how and by what key",blocks:[
["p","Everything so far scales reads. Eventually the writes stop fitting on one machine, and you have to divide the data itself."],
["p","The moment to do that is not when the disk is full. It is when you can name two things: the axis the data grows along, and the query that dominates. If you cannot name both, sharding now means committing to a key you do not yet understand — and the key is very close to permanent."],
["p","For orders, ninety-five percent of queries are scoped to a single customer: their history, their open orders, their returns. Partition by customer_id and almost every query lands on exactly one shard."],
["p","Now say the cost out loud, because there always is one, and being able to state it is what separates a decision from a guess."],
["p","All orders for product P no longer has a home. It has to ask every shard and merge the answers, and it gets slower each time you add a shard. If that query matters to the business, you build a second index partitioned by product instead — and that index is maintained asynchronously, so it lags behind the truth."],
["p","And the wholesale customer with a million orders is now one shard's problem, alone. That is a hot partition, and it is election night again in a different costume: distributing keys evenly is not the same as distributing load evenly."],
["p","The choice between hashing and ranging is the same trade seen from the other side. Hash partitioning spreads writes beautifully and destroys range queries — orders from last Tuesday becomes a question you must ask everybody. Range partitioning keeps ranges local and manufactures hot spots, because if you partition by time then every new write goes to whichever shard is newest."],
["p","That last one is the most common sharding mistake there is, and it is worth stating as a rule: a monotonically increasing partition key guarantees that one partition receives all of the writes. Time is monotonically increasing. So is an auto-increment id."],
["p","Resharding afterwards is the thing to avoid. It means dual-writing, backfilling, verifying and cutting over on a live system, for weeks. Which is the real argument for waiting until you can name the axis — and then not waiting a great deal longer."],
D("Sharding",{say:"Partition by customer_id since 95% of queries are per-customer; inventory is per-product and stays on its own smaller store; reporting runs off replicas into the warehouse. The B2B buyer with a million orders is the hotspot risk — I'd split them by (customer_id, year) if needed.",
use:["Data or write rate exceeds one machine — and you can name the growth axis and the dominant access pattern"],
avoid:["Before you can name those — you'll freeze the wrong key","When cross-shard transactions would be common — redesign the boundary instead"],
consider:["Hash partitioning: even, range queries become scatter-gather","Range partitioning: range queries local; monotonic keys (time, sequence) make the newest shard hot","Directory: a lookup service; total flexibility, an extra hop, must be highly available","Consistent hashing or fixed virtual partitions keep rebalancing proportional (Chapter 03)"],
fails:"Hot shard (celebrity, today's date). Wrong key → reshard under load: dual-write, backfill, verify, cut over — weeks. Global secondary index lags because it's itself partitioned and async.",
alt:"Bigger machine + replicas; archive old data; move only the one hot table.",
cases:["Query without the shard key → asks every shard and merges","'All orders for product P' with customer sharding → global secondary index on product_id, eventually consistent","Adding nodes → move whole virtual partitions, not rows"]}),
["ex","Weak:   \"We'll shard the database.\"\nStrong: \"Partition by user_id because most requests are scoped to one\n        user. Cost: global search and celebrity users create cross-\n        shard queries and hotspots — search gets its own index and\n        celebrities get a cache.\""],
["t","Sharding early wastes effort and freezes a key you don't understand; sharding late means migrating under load. The moment is when you can name the axis and the dominant query — usually well before the single node's limit."]
]}
]};
