const D = (name, o) => ["dec", { name, ...o }];
export default {id:"distributed",num:"05",title:"Distributed systems theory",example:"a bank transfer between two accounts",
tagline:"Consistency, coordination and cross-machine transactions as decisions — which model per operation, which mechanism, what it costs, how it fails.",
terms:["Linearizable vs eventual","Read-your-writes","CAP / PACELC","Raft","Quorum","Fencing token","2PC vs saga","Outbox / CDC"],
objectives:["Choose the weakest consistency model each operation tolerates","State CAP and PACELC as per-operation choices, not a system label","Choose consensus, quorum or a single leader for coordination and prevent split brain","Choose 2PC or a saga for a concrete cross-service workflow","Guarantee event publication with an outbox and achieve effectively-once end to end"],
sections:[
{id:"consistency",title:"Choosing a consistency model per operation",blocks:[
["p","The invariant for the transfer: the sum of balances never changes. Every model below is a promise about what a reader can see, and each step up costs latency and availability."],
["tbl",{cols:["Model","Use when","Tradeoff · example"],rows:[
["Linearizable (strong)","Stale or wrong data is unacceptable","Coordination on every write · account balance, seat ownership"],
["Serializable","Transactions must not interleave badly (not about recency)","Aborts under contention · the debit+credit transaction"],
["Causal","Related operations must appear in order","Extra metadata · reply never shown before its parent"],
["Read-your-writes","Users must see their own change now","Routing or version tracking · profile edit, 'my transfers' list"],
["Monotonic reads","Never see time go backwards","Session pinning · a feed that shouldn't lose items on refresh"],
["Eventual","Temporary staleness is fine","Stale reads · like counts, analytics, search index"]]}],
D("Strong consistency for the critical operation",{say:"The debit and credit are linearizable with respect to the balance check — a read that sees the debit but not the credit is exactly how money vanishes. The transaction list can lag by seconds.",
use:["Money, inventory, seats, uniqueness (usernames), permissions"],
avoid:["Counters, feeds, search, analytics — you pay latency and availability for nothing users notice"],
consider:["Costs a synchronous round trip to a replica or a consensus group per write","Blanket 'strong everywhere' is as much a red flag as 'eventual everywhere'"],
cases:["Transfer shows on A's statement but B's balance not yet updated → causal or read-your-writes scoped to the transfer id","Two transfers race on one account → conditional debit WHERE balance >= amount"]}),
D("CAP and PACELC, correctly",{say:"For the balance write I choose consistency: during a partition the minority side refuses writes. For the transaction list I choose availability: serve the last known list with a 'may be delayed' note. In normal operation I accept a few ms per write to wait for a synchronous replica.",
use:["State it per operation, as above"],
avoid:["'Pick two of three' — partitions aren't optional; the choice is what to do during one","Labelling a whole system 'CP' or 'AP'"],
consider:["CAP: during a partition, answer possibly stale (A) or refuse (C)","PACELC: else, in normal operation, choose latency (L) or consistency (C) — the choice users feel every day","CAP-available means every non-failed node answers; refusing writes is often the right choice"],
nuance:"For money an error is recoverable and wrong data is not; for a social feed the reverse."})
]},
{id:"coordination",title:"Coordination: consensus, quorums, leases",blocks:[
D("Consensus (Raft / Paxos)",{say:"Leader election and config go through a 3-node Raft group; a majority is required so only one side of a partition can lead, and the term number fences out a stale leader.",
use:["Leader election, configuration stores, replicated state machines, distributed SQL ranges — coordination state"],
avoid:["Application data at volume — clusters are 3–5 nodes; every commit is a majority round trip"],
consider:["2F+1 nodes tolerate F failures","Leader heartbeats; randomised election timeout; a new leader always has every committed entry","etcd, ZooKeeper, Consul, CockroachDB, Kafka controller"],
fails:"Minority side stalls; a slow disk on the leader slows every commit; misconfigured 2-node cluster has no majority on any failure."}),
D("Quorum reads and writes",{say:"N=3, W=2, R=2 gives overlap, so every read sees the latest write without a leader.",
use:["Leaderless stores (Chapter 04); tunable per operation"],
consider:["W + R > N is the guarantee; drop it for speed on non-critical ops","Sloppy quorums and hinted handoff trade the guarantee for availability"]}),
D("Distributed lock → lease with fencing token",{say:"Two workers must not process the same transfer, so a worker takes a lease with a monotonic token and the account store rejects any write carrying a stale token — a paused worker that wakes late is fenced out.",
use:["Exclusive processing of a job/entity across workers","Leader duties in a worker pool"],
avoid:["Trusting a lock without the store checking the token — that's a lock that lies"],
consider:["Lease must expire (holder may die) — and expiry is exactly what lets two holders overlap","Fencing token: strictly increasing; the protected resource rejects lower tokens"],
fails:"Worker 1 takes lock (30 s), GC-pauses 40 s; lock expires; worker 2 processes; worker 1 wakes and processes again. Without a token: double transfer.",
cases:["Scheduler picking due jobs (Ch. 11)","Single active consumer per partition","Failover promoting exactly one leader"]}),
D("Clocks",{say:"I won't order writes by wall-clock timestamps — clocks skew and jump — so ordering comes from a per-entity sequence or a logical clock.",
use:["Logical/Lamport clocks or per-key sequence numbers for ordering","Hybrid logical clocks when you need both"],
avoid:["Last-writer-wins by timestamp for anything that matters"],
consider:["NTP can step time backwards","Spanner's TrueTime needs atomic clocks — you don't have it"]}),
["t","Consensus is correct and slow; use it for the small amount of state that must never disagree (who leads, config), and shard application data into many independent groups."]
]},
{id:"cross-service",title:"Transactions across services: 2PC or saga",blocks:[
D("Two-phase commit",{say:"Inside one datacenter for a short transaction across two shards I'd use the database's 2PC; across services or regions I wouldn't — the coordinator blocks everyone while it's down.",
use:["Inside a distributed database (XA, distributed SQL) for short transactions","Both participants in one datacenter"],
avoid:["Across services, across regions, anything long-running"],
consider:["Prepare (write, hold locks, vote) → commit/rollback on the coordinator's decision","Coordinator crash after prepare leaves participants locked until it returns"]}),
D("Saga",{say:"Debit A, credit B, mark complete — each a local transaction idempotent on the transfer id; if credit fails, compensate by re-crediting A. The transfer has a visible PENDING state and I model it honestly.",
use:["Workflows spanning services: order → payment → shipment; transfers across shards","Long-running processes"],
avoid:["Steps that can't be compensated (an email sent, a card physically shipped) without designing the compensation as a business action","When intermediate states are unacceptable to expose"],
consider:["Orchestrated (one saga service drives and records progress — easier to debug) vs choreographed (each service reacts to events — no central component)","Every step idempotent on the saga id","PENDING/FAILED states in the data model; reconciliation job"],
fails:"Compensation itself fails → needs retry + alerting; orchestrator crashes mid-saga → durable saga table; non-idempotent step retried → duplicate.",
cases:["Payment succeeds, shipment service down → order stays PAID_AWAITING_SHIPMENT; retry, not refund","Credit B fails after debit A → re-credit A; mark FAILED; notify"]}),
["ex","Transfer as a saga\n1. Create transfer T, PENDING           (transfer service, local tx)\n2. Debit A referencing T                (shard 1, local tx)  fail → T FAILED\n3. Credit B referencing T               (shard 2, local tx)  fail → re-credit A; T FAILED\n4. T COMPLETED\nEvery step idempotent on T.id — any step can be retried safely."],
["t","2PC gives atomicity and holds locks across a network round trip. Sagas give availability and expose intermediate states your data model must represent. Money systems mostly run sagas with explicit pending states and reconciliation."]
]},
{id:"outbox",title:"Publishing events reliably: outbox, CDC, effectively-once",blocks:[
D("Transactional outbox",{say:"The transfer row and the TransferCompleted event commit in one local transaction; a relay publishes from the outbox; consumers dedupe on event id — effectively once, end to end.",
use:["Any service that must emit events after a DB change"],
avoid:["Dual-write (write row, then publish) — a crash between them loses or fabricates events. Never."],
consider:["Relay delivers at least once → consumers must be idempotent","Partition the relay by aggregate id to keep per-entity order","Clean up sent rows"],
alt:"Change data capture.",
fails:"Relay lag hides events for minutes; outbox table grows unbounded; consumer not idempotent → double effects."}),
D("Change data capture",{say:"Debezium tails the WAL and turns every committed change into an event, so no outbox code — at the cost of coupling consumers to our table schema unless we transform the stream.",
use:["Feeding search indexes, caches, warehouses from an existing DB","Many tables to publish"],
avoid:["When you want a clean domain event, not a row change"],
consider:["Schema evolution becomes a consumer problem","Snapshot + stream for bootstrapping"]}),
D("Effectively-once processing",{say:"No broker delivers exactly once to a consumer that can crash between acting and acknowledging. We get at-least-once delivery plus a consumer that records the event id in the same transaction as its side effect — that's exactly-once effects.",
use:["Every consumer that has side effects"],
avoid:["Believing 'exactly-once' is a broker setting"],
consider:["Dedup table keyed (consumer, event id) with TTL","Deterministic side effects (same output path) make duplicates harmless without a table"]}),
["t","Outbox + relay + idempotent consumer is three moving parts. The alternative silently loses or duplicates events under exactly the failures you can't reproduce. For money, it's not optional."]
]}
]};
