const D = (name, o) => ["dec", { name, ...o }];
export default {id:"server",num:"05",part:"II · How a request reaches a server",title:"What a server does with a request",example:"a URL shortener",
tagline:"One machine, many requests at once. Threads and event loops, why work that waits and work that computes want opposite things, and why servers must not remember anything.",
terms:["Process","Thread","Race condition","Deadlock","Blocking vs non-blocking","Concurrency vs parallelism","I/O-bound","CPU-bound"],
objectives:["Explain why coordinating in application memory fails across several servers","Choose threads or an event loop from whether the work waits or computes","Say why one slow computation freezes an event loop","Explain what makes a server stateless and why it matters"],
sections:[
{id:"concurrency",title:"Processes, threads and I/O models",blocks:[
["p","Two requests arrive in the same millisecond and both generate the short code a7Gk2Qp. What happens?"],
["p","The tempting answer is to coordinate: keep a set of issued codes in memory, check it before writing, and refuse the second one. It is tempting, it is wrong, and understanding exactly why is worth more than the fix itself."],
["p","It is wrong because that set lives in one process\'s memory, and you have five API servers. Each holds its own set. Each believes it. None of them knows anything about the other four. You have not prevented the collision — you have made it invisible, which is worse, because now it produces a wrong answer instead of an error."],
["p","The fix is to stop coordinating and let the database refuse. Put a unique constraint on the code column, insert, and handle the failure. One of the two requests gets a constraint violation, generates a fresh code and retries. No lock, no shared memory, no agreement between servers — the invariant is enforced in the one place all five servers already trust."],
["p","Hold on to the shape of that move, because you are going to make it repeatedly. It is the same move as the conditional inventory decrement in Chapter 08, the seat reservation in Chapter 26, and the idempotency key in Chapter 09. When several actors have to agree about something, do not build agreement between them. Push the decision down to the single component they all already talk to, and let it say no."],
["h","CPU-bound and I/O-bound want opposite things"],
["p","A redirect handler computes almost nothing. It looks up a code and writes a header. Essentially all of its wall-clock time is spent waiting — on the cache, on the database, on the network. It is I/O-bound."],
["p","Give that work a thread per request and most of your threads are asleep, while the operating system burns real CPU switching between sleeping threads. Give it an event loop and a single thread holds thousands of waiting requests, waking only when data actually arrives."],
["p","Now put an image resizer on that same event loop. It computes for two hundred milliseconds without ever yielding, and for those two hundred milliseconds every other connection on the loop is frozen. The event loop is not slow. It is single-threaded by design, and CPU-bound work violates the design."],
["p","So: I/O-bound work wants concurrency, which means more requests in flight per core. CPU-bound work wants parallelism, which means more cores. Those are different needs with different remedies, and putting both on one pool guarantees neither gets what it wanted."],
D("Threads sharing memory — cheap to coordinate, easy to corrupt",{say:"Threads share memory, so passing data between them is nearly free — and that is exactly what creates the problem. Anything shared is either never modified, protected by a lock, or handed to the database to settle.",
use:["Doing genuine computation in parallel within one process.","Handling requests in servers that give each request its own thread."],
avoid:["Thousands of threads that are mostly waiting on the network, because the operating system burns real processing time switching between sleeping threads.","Keeping anything correctness-critical in one process's memory when you run several servers. Each has its own copy and none of them knows about the others."],
consider:["A race happens when two threads read the same value, both decide based on what they read, and both write. The fix is an operation that reads and writes as one step.","A deadlock happens when each thread holds what the other needs. Always take locks in the same order and it cannot occur.","Separate processes contain a crash; threads in one process do not."],
cases:["Two requests generate the same short code at the same instant. Do not try to coordinate in memory — insert with a uniqueness rule and let one of them be rejected and try again."]}),
D("Event-loop I/O — one thread holding thousands of waiting requests",{say:"This work is nearly all waiting on the database rather than computing, so a single loop can hold thousands of requests in flight at once instead of dedicating a thread to each one that then sits idle.",
use:["Services whose time goes on waiting: APIs, proxies, gateways, and the servers holding chat connections.","Anything holding many connections that are mostly idle."],
avoid:["Handlers that do heavy computation — resizing images, hashing, rendering reports — on the same loop. One long calculation freezes every other connection on it."],
consider:["This does not make a single request faster. The database still takes exactly as long. It lets one machine handle far more requests at the same time.","Move computation-heavy work onto a separate pool of threads or into a queue, so it cannot block the loop."],
nuance:"Work limited by computation wants more cores. Work limited by waiting wants more requests in flight per core. They are different needs, and sharing one pool between them means neither gets what it needed."}),
["ex","Latency ladder — the numbers behind every 'put it in a cache'\nL1 cache         1 ns\nMemory         100 ns\nSSD read       100 µs\nDC round trip  500 µs\nDisk seek       10 ms\nUS coast↔coast  70 ms\nUS↔Europe      150 ms\n\nShortener consequence: a billion links × ~100 B fits in ~100 GB —\nthe whole mapping lives in memory; the DB is the durable copy."]
]}
]};
