const D = (name, o) => ["dec", { name, ...o }];
export default {id:"distributed",num:"05",title:"Distributed systems theory",example:"a bank transfer between two accounts",
tagline:"Consistency, coordination and cross-machine transactions as decisions — which model per operation, which mechanism, what it costs, how it fails.",
terms:["Linearizable vs eventual","Read-your-writes","CAP / PACELC","Raft","Quorum","Fencing token","2PC vs saga","Outbox / CDC"],
objectives:["Choose the weakest consistency model each operation tolerates","State CAP and PACELC as per-operation choices, not a system label","Choose consensus, quorum or a single leader for coordination and prevent split brain","Choose 2PC or a saga for a concrete cross-service workflow","Guarantee event publication with an outbox and achieve effectively-once end to end"],
sections:[
{id:"consistency",title:"Choosing a consistency model per operation",blocks:[
["p","Alice sends Bob fifty pounds. What must never be true?"],
["p","That the money left Alice and did not arrive at Bob. Or that it arrived at Bob and never left Alice. Every mechanism in this chapter exists to protect a sentence of that shape."],
["p","Notice the shape carefully. It is not the system is consistent. It is a specific claim about a specific pair of facts that must not be allowed to disagree. Consistency is not a setting you turn on. It is a per-operation choice, and different operations in the same product should choose differently."],
["p","In this bank the balance is linearizable: every reader sees the effect of every completed transfer, in order, without exception. The list of past transfers may lag by a few seconds, because nobody is harmed by a statement that is briefly incomplete. The monthly interest projection can be an hour stale and no one will ever know."],
["p","One product, three answers. Being able to say which operation gets which is most of the skill here."],
["p","So the instruction is: name the weakest model each operation can tolerate, then name the mechanism that provides it. Strong consistency is not the safe default. It costs a coordination round trip on every write and it reduces availability during a partition, and paying that for a like count is not caution — it is waste with a respectable-sounding name."],
["tbl",{cols:["Model","Use when","Tradeoff · example"],rows:[
["Linearizable (strong)","Stale or wrong data is unacceptable","Coordination on every write · account balance, seat ownership"],
["Serializable","Transactions must not interleave badly (not about recency)","Aborts under contention · the debit+credit transaction"],
["Causal","Related operations must appear in order","Extra metadata · reply never shown before its parent"],
["Read-your-writes","Users must see their own change now","Routing or version tracking · profile edit, 'my transfers' list"],
["Monotonic reads","Never see time go backwards","Session pinning · a feed that shouldn't lose items on refresh"],
["Eventual","Temporary staleness is fine","Stale reads · like counts, analytics, search index"]]}],
D("Strong consistency for the critical operation",{say:"The debit and credit are linearizable with respect to the balance check — a read that sees the debit but not the credit is exactly how money vanishes. The transaction list can lag by seconds.",
use:["Money, inventory, seats, uniqueness (usernames), permissions"],
avoid:["Counters, feeds, search, analytics — you pay latency and availability for nothing users notice"],
consider:["Costs a synchronous round trip to a replica or a consensus group per write","Blanket 'strong everywhere' is as much a red flag as 'eventual everywhere'"],
cases:["Transfer shows on A's statement but B's balance not yet updated → causal or read-your-writes scoped to the transfer id","Two transfers race on one account → conditional debit WHERE balance >= amount"]}),
["h","CAP, stated so that it means something"],
["p","You will be asked about CAP. The version most people recite — pick two of the three — is wrong in a way that makes it useless."],
["p","You do not get to pick whether partitions happen. A cable is cut, a switch reboots, a rack loses connectivity. Partitions are events, not options, and no amount of architecture opts out of them."],
["p","So the theorem is not offering three things to choose two from. It is telling you that when a partition occurs, you must pick one of two behaviours. Answer anyway, with data that may be stale or may later conflict. Or refuse to answer until you can be certain. Those are the only two, because the third — remain correct and available while cut off from the other half — is exactly what the theorem says cannot exist."],
["p","For the balance, refuse. An error is recoverable; a wrong balance that somebody acts on is not. For the transfer list, answer with what you have and mark it as possibly delayed."],
["p","Then there is the part CAP says nothing about, which matters far more day to day. There is no partition happening right now. What are you doing the other 99.9% of the time?"],
["p","That is what PACELC adds: else, choose between latency and consistency. Waiting for a synchronous replica on every write costs a few milliseconds forever, partition or no partition. That is the cost your users actually feel, every single day, and the famous theorem is silent about it."],
D("CAP and PACELC, correctly",{say:"For the balance write I choose consistency: during a partition the minority side refuses writes. For the transaction list I choose availability: serve the last known list with a 'may be delayed' note. In normal operation I accept a few ms per write to wait for a synchronous replica.",
use:["State it per operation, as above"],
avoid:["'Pick two of three' — partitions aren't optional; the choice is what to do during one","Labelling a whole system 'CP' or 'AP'"],
consider:["CAP: during a partition, answer possibly stale (A) or refuse (C)","PACELC: else, in normal operation, choose latency (L) or consistency (C) — the choice users feel every day","CAP-available means every non-failed node answers; refusing writes is often the right choice"],
nuance:"For money an error is recoverable and wrong data is not; for a social feed the reverse."})
]},
{id:"coordination",title:"Coordination: consensus, quorums, leases",blocks:[
["p","Two workers wake up and both conclude they are responsible for processing transfer T. How do you ensure only one of them proceeds?"],
["p","The obvious answer is a lock. The obvious answer contains a subtle and famous bug, and it is worth walking through in full because it changes how you think about every distributed mechanism after it."],
["p","Worker one takes a lock with a thirty-second expiry and begins work. Then its process pauses. Not crashes — pauses. A garbage collection, a hypervisor scheduling it out, a burst of page faults. It is simply not running for forty seconds."],
["p","The lock expires. Worker two acquires it entirely legitimately and processes the transfer. Then worker one resumes. From its own point of view, no time has passed. It believes it still holds the lock, because the last thing it knew was that it did, and it completes its work. The transfer happens twice."],
["p","Nothing here malfunctioned. The lock service did exactly what it promised. The pause is ordinary — every managed runtime does it, and no runtime warns you first. The bug is the assumption that holding a lock a moment ago means holding it now, and a paused process has no way whatsoever to tell the difference."],
["p","The fix is a fencing token. The lock hands out a number that only ever increases: worker one gets 33, worker two gets 34. Every write to the protected resource carries its token, and the resource refuses any token lower than the highest it has already accepted. When worker one wakes and writes with token 33, the account store rejects it — not because it noticed the pause, but because it simply does not take old tokens."],
["p","That is the move worth extracting. Correctness does not depend on anyone detecting the failure. It depends on the protected resource being able to refuse. A lock that nothing checks is a lock that lies."],
["h","And do not trust the clock either"],
["p","The same distrust applies to time. It is tempting to order two transfers by their timestamps. Do not. Clocks on different machines disagree, and worse, NTP can step a clock backwards, so a later event can carry an earlier time and there is no way to detect it after the fact."],
["p","Ordering comes from a sequence the system controls: a per-account sequence number, a logical clock, a consensus log. Never a wall clock. Last-writer-wins by timestamp is a data-loss strategy with a friendly name."],
["p","Which leaves consensus — Raft, Paxos — as the way a group of machines agrees on one value when any of them may fail. It is correct and it is slow, because every decision costs a round trip to a majority. So spend it on the small amount of state that must never disagree, like who the leader is and what the configuration says, and keep your application data well away from it."],
D("Consensus (Raft / Paxos)",{say:"Leader election and config go through a 3-node Raft group; a majority is required so only one side of a partition can lead, and the term number fences out a stale leader.",
use:["Leader election, configuration stores, replicated state machines, distributed SQL ranges — coordination state"],
avoid:["Application data at volume — clusters are 3–5 nodes; every commit is a majority round trip"],
consider:["2F+1 nodes tolerate F failures","Leader heartbeats; randomised election timeout; a new leader always has every committed entry","etcd, ZooKeeper, Consul, CockroachDB, Kafka controller"],
fails:"Minority side stalls; a slow disk on the leader slows every commit; misconfigured 2-node cluster has no majority on any failure."}),
D("Quorum reads and writes",{say:"N=3, W=2, R=2 gives overlap, so every read sees the latest write without a leader.",
use:["Leaderless stores (Chapter 04); tunable per operation"],
consider:["W + R > N is the guarantee; drop it for speed on non-critical ops","Sloppy quorums and hinted handoff trade the guarantee for availability"]}),
D("Distributed lock → lease with fencing token",{say:"Two workers must not process the same transfer, so a worker takes a lease with a monotonic token and the account store rejects any write carrying a stale token — a paused worker that wakes late is fenced out.",
use:["Exclusive processing of a job/entity across workers","Leader duties in a worker pool"],
avoid:["Trusting a lock without the store checking the token — that's a lock that lies"],
consider:["Lease must expire (holder may die) — and expiry is exactly what lets two holders overlap","Fencing token: strictly increasing; the protected resource rejects lower tokens"],
fails:"Worker 1 takes lock (30 s), GC-pauses 40 s; lock expires; worker 2 processes; worker 1 wakes and processes again. Without a token: double transfer.",
cases:["Scheduler picking due jobs (Ch. 11)","Single active consumer per partition","Failover promoting exactly one leader"]}),
D("Clocks",{say:"I won't order writes by wall-clock timestamps — clocks skew and jump — so ordering comes from a per-entity sequence or a logical clock.",
use:["Logical/Lamport clocks or per-key sequence numbers for ordering","Hybrid logical clocks when you need both"],
avoid:["Last-writer-wins by timestamp for anything that matters"],
consider:["NTP can step time backwards","Spanner's TrueTime needs atomic clocks — you don't have it"]}),
["t","Consensus is correct and slow; use it for the small amount of state that must never disagree (who leads, config), and shard application data into many independent groups."]
]},
{id:"cross-service",title:"Transactions across services: 2PC or saga",blocks:[
["p","The transfer is two writes in two places: debit Alice on one shard, credit Bob on another. There is no transaction that spans them."],
["p","The textbook answer is two-phase commit. A coordinator asks every participant to prepare — do the work, hold the locks, promise you can commit — and then, once all have voted yes, tells them to commit."],
["p","Now the failure that defines the protocol. The coordinator dies after everyone has voted yes and before it says commit. Every participant is holding locks, has promised it can commit, and is not permitted to commit or abandon on its own. They wait. They keep waiting, holding those locks, until the coordinator comes back."],
["p","That is not a rare edge case; it is the protocol working as designed, and it is why 2PC lives inside a database coordinating its own shards and almost never between services you deploy separately."],
["p","The alternative is to stop trying to be atomic and to be honest instead."],
["p","A saga performs the work as a sequence of local transactions, each committing on its own. Create the transfer as PENDING. Debit Alice. Credit Bob. Mark COMPLETED. If crediting Bob fails, you do not roll back — you cannot, the debit already committed — you compensate, by crediting Alice again, and mark the transfer FAILED."],
["p","The price is a state a user can observe. For a moment, the money has left Alice and not reached Bob. You cannot hide that, so you model it: PENDING is a real column value and a real word on the screen. Every real bank shows it to you, and now you know why."],
["p","The second price is that compensation is business logic rather than a database feature, and it can fail too. Which is why a saga always ships with a reconciliation job — something that periodically hunts for transfers stuck in PENDING and drives them to an end state."],
["p","That is worth sitting with, because it is the general lesson of the whole chapter. You do not eliminate the bad intermediate states. You make them visible, bounded, and recoverable."],
D("Two-phase commit",{say:"Inside one datacenter for a short transaction across two shards I'd use the database's 2PC; across services or regions I wouldn't — the coordinator blocks everyone while it's down.",
use:["Inside a distributed database (XA, distributed SQL) for short transactions","Both participants in one datacenter"],
avoid:["Across services, across regions, anything long-running"],
consider:["Prepare (write, hold locks, vote) → commit/rollback on the coordinator's decision","Coordinator crash after prepare leaves participants locked until it returns"]}),
D("Saga",{say:"Debit A, credit B, mark complete — each a local transaction idempotent on the transfer id; if credit fails, compensate by re-crediting A. The transfer has a visible PENDING state and I model it honestly.",
use:["Workflows spanning services: order → payment → shipment; transfers across shards","Long-running processes"],
avoid:["Steps that can't be compensated (an email sent, a card physically shipped) without designing the compensation as a business action","When intermediate states are unacceptable to expose"],
consider:["Orchestrated (one saga service drives and records progress — easier to debug) vs choreographed (each service reacts to events — no central component)","Every step idempotent on the saga id","PENDING/FAILED states in the data model; reconciliation job"],
fails:"Compensation itself fails → needs retry + alerting; orchestrator crashes mid-saga → durable saga table; non-idempotent step retried → duplicate.",
cases:["Payment succeeds, shipment service down → order stays PAID_AWAITING_SHIPMENT; retry, not refund","Credit B fails after debit A → re-credit A; mark FAILED; notify"]}),
["ex","Transfer as a saga\n1. Create transfer T, PENDING           (transfer service, local tx)\n2. Debit A referencing T                (shard 1, local tx)  fail → T FAILED\n3. Credit B referencing T               (shard 2, local tx)  fail → re-credit A; T FAILED\n4. T COMPLETED\nEvery step idempotent on T.id — any step can be retried safely."],
["t","2PC gives atomicity and holds locks across a network round trip. Sagas give availability and expose intermediate states your data model must represent. Money systems mostly run sagas with explicit pending states and reconciliation."]
]},
{id:"outbox",title:"Publishing events reliably: outbox, CDC, effectively-once",blocks:[
["p","One more thing must happen once the transfer completes: other systems need to know. Statements, the fraud model, notifications."],
["p","The obvious implementation is two lines — commit the transaction, then publish the event — and it is broken in both directions."],
["p","Crash between them and the transfer happened while nobody was told. Publish first and let the transaction fail, and you have announced a transfer that does not exist."],
["p","There is no ordering of those two operations that is safe, because they are two different systems and you cannot commit to both at once. This is the dual-write problem, and it has no clever fix."],
["p","What it has is a reframing. Write the event into the same database, in the same transaction as the transfer itself, into a table called the outbox. Now there is one commit, and it is atomic by construction: either the transfer and its event both exist, or neither does."],
["p","A separate relay process then reads unsent rows and publishes them. If it crashes mid-publish it will republish on restart, so consumers may see the same event twice."],
["p","Which brings the last idea in the chapter, and it is worth being firm about. Exactly-once delivery does not exist. A consumer can always crash in the gap between acting and acknowledging, and no broker setting closes that gap."],
["p","What you can have is exactly-once effect: at-least-once delivery, plus a consumer that records which event ids it has already handled in the same transaction as whatever it does about them. Deliver repeatedly, act once."],
["p","At-least-once delivery and an idempotent consumer. That combination is what people mean when they say exactly-once, and saying it precisely instead of loosely is worth a great deal in an interview."],
D("Transactional outbox",{say:"The transfer row and the TransferCompleted event commit in one local transaction; a relay publishes from the outbox; consumers dedupe on event id — effectively once, end to end.",
use:["Any service that must emit events after a DB change"],
avoid:["Dual-write (write row, then publish) — a crash between them loses or fabricates events. Never."],
consider:["Relay delivers at least once → consumers must be idempotent","Partition the relay by aggregate id to keep per-entity order","Clean up sent rows"],
alt:"Change data capture.",
fails:"Relay lag hides events for minutes; outbox table grows unbounded; consumer not idempotent → double effects."}),
D("Change data capture",{say:"Debezium tails the WAL and turns every committed change into an event, so no outbox code — at the cost of coupling consumers to our table schema unless we transform the stream.",
use:["Feeding search indexes, caches, warehouses from an existing DB","Many tables to publish"],
avoid:["When you want a clean domain event, not a row change"],
consider:["Schema evolution becomes a consumer problem","Snapshot + stream for bootstrapping"]}),
D("Effectively-once processing",{say:"No broker delivers exactly once to a consumer that can crash between acting and acknowledging. We get at-least-once delivery plus a consumer that records the event id in the same transaction as its side effect — that's exactly-once effects.",
use:["Every consumer that has side effects"],
avoid:["Believing 'exactly-once' is a broker setting"],
consider:["Dedup table keyed (consumer, event id) with TTL","Deterministic side effects (same output path) make duplicates harmless without a table"]}),
["t","Outbox + relay + idempotent consumer is three moving parts. The alternative silently loses or duplicates events under exactly the failures you can't reproduce. For money, it's not optional."]
]}
]};
