const D = (name, o) => ["dec", { name, ...o }];
export default {id:"stores",num:"06",part:"III · Storing data",title:"Choosing where data lives",example:"an e-commerce order system",
tagline:"The families of datastore and how to pick one — from the access pattern, the consistency the operation needs and the axis the data grows along, never from the word scale.",
terms:["Relational","Key-value","Document","Wide-column","Graph","Search index","Object storage","Access pattern"],
objectives:["Choose a store from four questions asked in order","Recognise that one product contains several workloads wanting different stores","Say what each extra datastore costs to run","Explain why a search index is never the source of truth"],
sections:[
{id:"choosing-store",title:"Choosing the store",blocks:[
["p","A customer clicks Buy. What has to be true one second later?"],
["p","The order exists. Its lines exist. The inventory for each item has gone down by exactly the right amount. Their cart is empty. And if any one of those failed, none of them happened."],
["p","That last sentence is the reason this chapter opens with relational databases rather than a menu of alternatives to them."],
["p","The instinct in interviews is to choose a store from the word scale. Scale is the last input, not the first. Four questions come before it, in order. What are the access patterns? What has to be consistent with what? How big does this get, and along which axis? And how much does the shape vary from record to record?"],
["p","Run them on the order. Access patterns: write several related rows together, read them back by order id or by customer. Consistency: the order, its lines and the inventory must agree or none of them may exist. Size: millions of rows a year, which is small. Shape: identical every time. That is a relational database, and it is not a close call."],
["p","Now run the same four questions on the shopping cart, which lives in the same product and gets a completely different answer. Access pattern: get and put by user id, and nothing else — nobody has ever needed to know which carts contain a blue umbrella. Consistency: with nothing at all; a cart is one person's scratch paper. Size: small, and it expires by itself. Shape: uniform."],
["p","That is a key-value store, and putting it in the orders database would spend the one thing the orders database is good at on a workload that does not need it."],
["p","This is the actual skill in this section, and it is not memorising which database is which. It is noticing that one system contains several workloads and they do not all want the same thing. Orders are relational. Carts are key-value. Product images are object storage with a pointer in the database. The search box is an inverted index that is never, under any circumstances, the source of truth."],
["p","And every one of those costs something real: another system to run, back up, secure, monitor, and keep in step with the others. Polyglot persistence is not free sophistication. Make each store earn its place with an access pattern the others genuinely cannot serve."],
D("Relational database — tables, with rules the database enforces",{say:"Orders need several rows written together and a rule that stock can never go negative — a rule the application cannot be trusted to remember everywhere. So orders stay relational, and I would split them across machines by customer when writes approach ten thousand a second.",
use:["Changes across several rows or tables that must all succeed or all fail.","Rules the database itself should enforce, like stock never dropping below zero or an email being unique.","Data with real relationships between records.","Almost every system's core records. This is the default you move away from, not toward."],
avoid:["Large files. Those go to object storage with a pointer here.","Hundreds of thousands of appended events a second, which suits a different engine entirely.","Records read whole, never joined, whose shape differs from one record to the next."],
consider:["One machine accepts all writes. Splitting writes across machines is a project, not a setting.","A larger machine plus copies for reading gets you to roughly ten thousand writes a second, which is further than most systems ever need."],
fails:"A query without a matching index scans the whole table. Two transactions can each read a value, each decide it is safe to act, and each write — a problem covered below. Long transactions hold locks that block everyone else. And after a failover, copies that were behind may be missing writes that were already confirmed."}),
D("Key-value store — look it up by its key, nothing else",{say:"The cart is fetched and saved by user id, and nothing else is ever asked of it. That is a key-value store, and it splits across machines trivially because every request already names exactly one key.",
use:["Sessions, shopping carts, rate-limit counters, caches, feature flags.","Lookups by a single known key, at any scale."],
avoid:["Any question that is not by key. Which carts contain a blue umbrella is not answerable — there is no way to ask it without reading everything."],
consider:["Redis holds data in memory and offers richer value types. DynamoDB stores durably and splits across machines automatically. Both are the same shape of tool."]}),
D("Document store — whole records with varying shapes",{say:"The catalogue is read whole, written rarely, never joined at request time, and its fields differ by product category. So each product is one document, with a cache in front of it.",
use:["Records that are read and written as a complete unit.","Records whose fields genuinely differ from one to the next.","Early development, where the shape is still changing weekly."],
avoid:["Relationships and rules you want the database to enforce.","Records updated in many small pieces by many writers at once."],
consider:["It is denormalised by design, which means when the same fact appears in several documents, keeping them in step is your job rather than the database's.","You can index fields inside a document, but each index costs write speed and some queries still cannot use them."]}),
D("Wide-column store — grouped by key, ordered within the group",{say:"Order history per customer is write-heavy and always read the same way: everything for one customer, within a date range. So we group rows by customer and keep them ordered by time inside that group.",
use:["Very high write volume.","Access that is always find one key, then read a range: messages in a conversation, events from a device, history for one user."],
avoid:["Ad-hoc questions, joins, or anything not shaped like the key you chose."],
consider:["Queries must match how the data is laid out, so you design a table per question rather than a table per thing.","These usually use the append-only storage engine described below, which gives excellent write speed and a continuous background merging cost."]}),
D("Graph, time-series and search stores — three specialists",{say:"Recommendations traverse bought-together relationships several steps deep, which is a graph store. Metrics go to a time-series store. The search box is a separate index fed by change events, and it is never the source of truth.",
use:["Graph stores when following relationships is the query itself: fraud rings, permission hierarchies, recommendations.","Time-series stores for metrics and readings — appended constantly, read by time range, and summarised as they age.","Search indexes for free-text queries, ranking and filters."],
avoid:["A graph store as your general storage.","A search index as your record of truth. Losing it should mean rebuilding it, never losing data."],
consider:["Each additional store is another system to run, back up, secure, monitor and keep in step. Make each one earn its place."]}),
D("Object storage — cheap, durable storage for large files",{say:"Product images go to object storage, uploaded directly by the browser using a temporary signed URL. The database keeps the key and the metadata, and the content delivery network serves the bytes.",
use:["Anything beyond a few hundred kilobytes: images, video, backups, exports."],
avoid:["Records you update in place, or small values you need back in under a millisecond."],
consider:["Effectively unlimited, costs cents per gigabyte per month, and is copied across data centres automatically.","There is no partial update. Changing one byte means writing the whole object again.","Set rules to move old objects to cheaper storage or delete them, or the bill grows forever."]}),
["t","Polyglot persistence gives each workload its ideal store and gives you four databases to run. Every extra store must earn its place with an access pattern the others can't serve."]
]}
]};
