const D = (name, o) => ["dec", { name, ...o }];
export default {id:"caching",num:"06",title:"Caching",example:"a product page on a shopping site",
tagline:"Which layer, which pattern, how wrong you can afford to be — every caching decision with its use-when, don't-use-when, cost and failure.",
terms:["CDN vs local vs distributed","Cache-aside","Write-through","Write-behind","TTL vs invalidation","Stampede","Negative caching","Hot key"],
objectives:["Pick the cache layer from how stale the data may be and how far it may travel","Pick cache-aside, read-through, write-through or write-behind per data type","Answer the six cache questions for any cache you draw","Design invalidation and state the staleness window it permits","Name and prevent stampedes, penetration, hot keys and cold starts"],
sections:[
{id:"layer",title:"Which layer: browser, CDN, local, distributed",blocks:[
["p","Ten million loads a day, a few edits a week. Each layer closer to the user is faster and harder to invalidate — decide which layers a datum may live in by how stale it may be."],
D("CDN",{say:"Images and the rendered product page for anonymous users sit at the edge with a short TTL and stale-while-revalidate; origin sees a fraction of a percent of traffic.",
use:["Static assets, media, cacheable public pages and API responses","Global users"],
avoid:["Personalised or private responses unless the cache key includes the user — and then usually not worth it","Data that must be fresh within seconds"],
consider:["Purge is slow and coarse; use short TTLs for semi-dynamic content","Cache key must include every header the response varies on or one user sees another's page","Egress cost scales with traffic"],
fails:"Stale page after a deploy; missing Vary leaks one user's data; hot object on one edge POP is fine — that's what CDNs are for."}),
D("Application-local (in-process) cache",{say:"The top few thousand products live in an in-process LRU on every server — microsecond reads and no network — accepting that servers may briefly disagree.",
use:["Extremely hot, small working set","Absorbing hot keys so the shared cache sees each server once per TTL"],
avoid:["Data that must be identical across servers at every instant","Large working sets — it's per-server memory"],
consider:["Every server has its own copy and its own staleness","Short TTL (seconds); no invalidation possible except via pub/sub broadcast"]}),
D("Distributed cache (Redis / Memcached)",{say:"Product documents are cache-aside in Redis with a 1 h TTL and delete-on-edit; the DB sees misses and writes only.",
use:["Shared, read-heavy data with tolerable staleness","Sessions, timelines, rate-limit counters, precomputed views"],
avoid:["As the source of truth unless durable Redis is a deliberate, stated choice","Data that must be fresh on every read — read the DB"],
consider:["Sub-ms network round trip; one copy all servers see","A new component whose failure sends full load to the DB — plan for it"],
fails:"Cold start after deploy, stampede on expiry, hot key on one node, stale-write race (see failure modes)."}),
["t","CDN → local → distributed → DB buffer pool: each step back is slower and more consistent. A price change reaches Redis with one delete, local caches at TTL, the CDN on purge, the browser on reload."]
]},
{id:"pattern",title:"Which pattern: aside, read-through, write-through, write-behind",blocks:[
D("Cache-aside",{say:"App checks cache, misses, reads DB, writes cache with a TTL. Only requested data is cached; staleness is bounded by TTL plus explicit deletes on edit.",
use:["General read-heavy data — the default pattern","Data that tolerates cache loss (it just refills)"],
avoid:["Data that must never be stale (skip the cache)","When many code paths read the same data and will implement it inconsistently — consider read-through"],
consider:["Logic lives in your code — every read path must do it the same way","Stale-write race: request A reads DB (old), edit deletes cache, A writes old value with full TTL. Mitigate: short TTL, delayed second delete, or compare-and-set"]}),
D("Read-through",{say:"The cache loads misses itself, so callers only talk to the cache and the logic exists once.",
use:["Many callers; you want one loader implementation"],
avoid:["When the cache can't know your data source"],
consider:["Same semantics as cache-aside, tighter coupling"]}),
D("Write-through",{say:"Prices are written to cache and DB synchronously so a read is never stale for data we wrote — slower writes, never a wrong price.",
use:["Cache must stay in sync with storage for written data","Reads must be warm immediately after write"],
avoid:["Write-heavy data that's rarely read — you fill the cache with junk"],
consider:["Doesn't help data changed outside this path (bulk imports) — still need TTL"]}),
D("Write-behind",{say:"View counts are incremented in cache and flushed every 10 s — fast writes and 100× less DB load, accepting loss of up to 10 s of counts if the node dies.",
use:["Very high write rates where loss of a small window is acceptable: counters, metrics, last-seen"],
avoid:["Orders, payments, anything you can't lose"],
consider:["Durability window = flush interval","Flush worker failure = silent loss"]}),
["ex","Product page, placed\nProduct document   cache-aside · TTL 1 h · delete on edit\nStock count        read-through · TTL 30 s · checkout re-reads the DB\nPrice              cache-aside · TTL 5 min · delete on change (legal risk)\nView counter       write-behind · flush 10 s\nImages             CDN · TTL 1 y · content-hashed filenames"],
["t","Cache-aside is simple and survives cache loss; write-through buys freshness with write cost; write-behind buys write speed with durability. Mixing patterns per data type on one page is normal — say which and why."]
]},
{id:"six-questions",title:"The six questions and the eviction choice",blocks:[
["ex","For every cache you draw\n1 Key?          product:{id}:v3  (version so schema changes miss cleanly)\n2 Stored what?  the assembled response (most savings, hardest partial invalidation) or the row?\n3 TTL?          1 h description · 30 s stock · 5 min price\n4 Invalidated?  delete product:{id}:* on save; TTL is the backstop\n5 Unavailable?  fall through to DB — can it survive? if not, this isn't a cache, it's a dependency\n6 Stale OK?     description yes · price minutes · stock at checkout no"],
D("TTL and invalidation together",{say:"Invalidation gives freshness on the write paths we remembered; the TTL bounds the damage on the ones we forgot. I always have both.",
use:["Every cache"],
avoid:["TTL-only for data anyone edits urgently","Invalidation-only — one forgotten admin script leaves stale data forever"],
consider:["Delete, don't update, on write — the next read refills from truth","Event-driven invalidation (ProductUpdated → delete) catches writes from anywhere, ms of lag","Versioned keys: bump a version, old entries become unreachable — no delete storms, one extra lookup"]}),
D("Eviction: LRU or LFU",{say:"Size the cache so eviction is rare for the working set; LRU by default, LFU if a one-time scan would otherwise flush the popular set.",
use:["LRU: temporal locality","LFU: stable popularity; resists scans"],
avoid:["Relying on eviction as your invalidation strategy"],
consider:["LRU is fooled by a full-catalogue crawl","LFU adapts slowly when popularity shifts","Most real caches run sampled approximations"]})
]},
{id:"failure-modes",title:"Stampedes, penetration, hot keys, cold starts",blocks:[
D("Cache stampede",{say:"When a hot key expires, one request refills while the others wait a few ms — or we serve stale and refresh in the background — so 5,000 misses never become 5,000 DB reads.",
use:["Any hot key with a TTL"],
consider:["Request coalescing / single-flight lock","Probabilistic early refresh before expiry","Stale-while-revalidate"],
fails:"Popular entry expires; thousands miss simultaneously; DB that sees one read/hour for this row falls over."}),
D("Cache penetration and negative caching",{say:"Requests for ids that don't exist miss every time, so we cache the absence for 30 s and put a Bloom filter of valid ids in front.",
use:["Public id spaces that can be guessed or scraped","Deleted-object lookups"],
consider:["Negative entries need a short TTL or a recreated object looks missing","Bloom filter rejects impossible keys with zero lookups"]}),
D("Hot key",{say:"The home-page product is read 100k/s from one Redis node, so it's replicated to several nodes and held in each server's in-process cache; the shared cache sees each server once per TTL.",
use:["Any key whose read rate saturates one node's network"],
consider:["Replicate the entry; in-process layer; salt with a suffix and spread (Chapter 03)"]}),
D("Cold start and warming",{say:"A new cache is empty and the DB hasn't seen full traffic since the cache existed; we warm the top N keys before taking traffic and ramp gradually.",
use:["Every deploy or restart of a load-bearing cache"],
avoid:["Cutting traffic to an empty cache"],
consider:["Replay recent keys from a log; pre-load top products","A load-bearing cache needs failover planning like a database"]}),
["t","Every one of these is invisible on a normal day and total on a bad one. Naming the stampede and the cold start before being asked is worth more than any Redis vocabulary."]
]}
]};
