const D = (name, o) => ["dec", { name, ...o }];
export default {id:"scaling",num:"07",title:"Load balancing and scaling",example:"a news site on election night",
tagline:"From one server to many without a new single point of failure — each technique as: what to say, when, when not, cost, failure mode.",
terms:["Vertical vs horizontal","L4 vs L7","Least connections","Consistent hashing","Sticky sessions","Health checks","Active-active","Autoscaling","Hot partition"],
objectives:["Justify every box in the standard request path from a requirement","Pick L4 or L7 and a routing algorithm from traffic shape","Explain consistent hashing well enough to say why only 1/N keys move","Design health checks that don't cascade","Choose active-passive vs active-active and reason about multi-region","Recognise a hot partition and name three fixes"],
sections:[
{id:"up-or-out",title:"Scale up or scale out",blocks:[
["p","It is eight in the evening on election night. Your news site normally serves two thousand requests a second. Tonight it will serve fifty thousand, almost all of them for a single page, and the traffic will arrive over roughly four minutes."],
["p","Every technique in this chapter is a response to some part of that sentence."],
["p","Start with the crudest fix available: buy a bigger machine. It is unfashionable and it is genuinely underrated. It requires no code changes, no distributed anything, and no new failure modes, and it will get a typical service from five hundred requests a second to several thousand over a weekend."],
["p","It has exactly two limits, and they are hard ones. There is a biggest machine you can buy. And one machine is one failure — every upgrade is a restart, and every crash is an outage."],
["p","Scaling out removes both limits and introduces one precondition that is very easy to skip past: the servers have to be interchangeable."],
["p","If a logged-in user's session lives in server three's memory, then the servers are not interchangeable. Adding a fourth does not add capacity for that user; it adds a machine that cannot serve them, and a fifty percent chance of logging them out on every request."],
["p","So the first real work of scaling out is not adding servers. It is taking the state out of the ones you already have."],
D("Scaling up — buy a bigger machine",{say:"We are at five hundred requests a second on one machine. A larger machine gets us to several thousand with no code changes at all, so I would do that first and spend the time it buys making the tier stateless.",
use:["Early stage, or moderate and predictable load.","Databases, which scale up comfortably long before they can be split apart."],
avoid:["Situations where staying available matters, because one machine is one thing that can fail.","Past the largest machine you can rent, which is a real ceiling and closer than people expect."],
consider:["Every upgrade means a restart, so every upgrade is a short outage unless you have somewhere else to send traffic.","Price rises faster than capacity at the top of the range. The biggest machine is rarely the best value."]}),
D("Scaling out — add more machines",{say:"Traffic is beyond what one machine can serve and we need to survive losing one, so we run several identical servers behind a load balancer and move anything they need to remember into a shared store.",
use:["Traffic beyond one machine.","Availability, because losing one server costs a fraction of capacity rather than everything."],
avoid:["Doing it before the servers are interchangeable. If a user's session lives in one server's memory, adding another does not add capacity for that user — it adds a machine that cannot serve them."],
consider:["Whatever the servers need to remember has to live somewhere all of them can reach: a database, a cache, or a queue.","The coordination problems do not disappear. They move into whichever shared store you chose, which is usually the right place for them."]}),
["ex","Client → DNS → CDN → Load balancer → App servers → Cache → Database\nCDN      static and cacheable pages never reach origin\nLB       one address; servers come and go\nServers  stateless; any one takes any request\nCache    the DB is the slowest, least elastic component\nDatabase source of truth, protected by everything above"],
["t","Scale the stateless tier out and the database up until forced to shard. Justify each box or erase it."]
]},
{id:"balancer",title:"L4 or L7, and which algorithm",blocks:[
["p","Traffic arrives, and something has to decide where it goes."],
["p","The first choice is about what the balancer is allowed to look at. A layer 4 balancer sees addresses and ports — it forwards a TCP connection without ever knowing what is inside it. That makes it fast, protocol-agnostic, and completely blind."],
["p","A layer 7 balancer reads the request. It costs CPU per request and it has to understand the protocol, and in exchange it can do the thing you need tonight: route /live-results to a pool of its own, with its own cache and its own capacity, so that a stampede on one page cannot starve everything else on the site."],
["p","The second choice is how it picks a server, and it comes down to one question: are your requests alike?"],
["p","Round robin assumes they are. Each server gets every Nth request, and if requests take roughly the same time, the load lands evenly. It is simple and it is right far more often than people expect."],
["p","Tonight they are not alike. A results page served from cache takes two milliseconds. An article page with a cold cache and a slow query takes two hundred. Under round robin, the server that happens to receive several slow requests in a row keeps receiving new ones anyway, because round robin has no idea it is struggling."],
["p","Least connections notices. It tracks how many requests each server currently has open and sends the next one to whoever is least busy, which is a rough proxy for whoever is coping. When request durations vary by two orders of magnitude, that proxy is worth the bookkeeping."],
D("Layer 7 balancer — it reads the request before deciding",{say:"A balancer that understands HTTP lets me send the live results page to its own pool of servers with its own cache, retry safe requests automatically, and reject low-priority traffic per endpoint when we are under pressure.",
use:["HTTP traffic at the public edge.","Routing based on the path, the hostname, a header or a cookie.","Applying different limits or retry rules to different endpoints."],
avoid:["Databases, message brokers, and anything that is not HTTP. Use a layer 4 balancer for those."],
consider:["It terminates each connection and inspects the request, which costs processing power on every request.","It has to understand every protocol passing through it, so it cannot forward something it does not speak.","It is now the thing everything depends on, so it needs its own redundancy in front of it."]}),
D("Layer 4 balancer — it forwards without looking inside",{say:"For database and message broker traffic we use a balancer that works at the connection level. It is fast and works with any protocol, because it never needs to understand what it is carrying.",
use:["Anything that is not HTTP.","Cases where raw throughput matters more than routing intelligence."],
avoid:["Cases where the routing decision depends on what is actually in the request."]}),
["tbl",{cols:["Algorithm","Use when","Tradeoff"],rows:[["Round robin","Uniform, short requests","Ignores load"],["Least connections","Requests vary in duration","Per-backend state; favours idle servers"],["Weighted","Mixed machine sizes; canaries at 1%","Weights drift from reality"],["Random two choices","Large fleets","Nearly least-connections, no coordination"],["Hash on key","Cache locality per user/URL","Uneven under skew"]]}],
D("Sticky sessions — pinning a user to one server",{say:"I would rather not. Pin users only where the connection itself is the state, such as WebSockets. Otherwise put the session in a shared store or a signed cookie so any server can serve anyone.",
use:["Genuinely stateful connections, where the server is holding something that cannot be moved."],
avoid:["Sessions kept in server memory. When that server restarts, those users are logged out, and heavy users pile up on whichever machine they first landed on."],
consider:["It undermines even distribution, and it turns a single server failure into a visible problem for a specific set of users rather than a small loss of capacity."]})
]},
{id:"consistent-hashing",title:"Consistent hashing",blocks:[
["p","You have twelve cache nodes and you need fourteen. How much of the cache survives the change?"],
["p","With the obvious scheme — hash the key, take it modulo the number of nodes — almost none of it."],
["p","Modulo twelve and modulo fourteen are unrelated functions. Nearly every key now maps to a different node than it did a second ago. Around ninety-two percent of your cached entries are effectively gone: still in memory somewhere, but nobody will ever look for them there again."],
["p","Which means ninety-two percent of reads become misses, and every one of those misses goes to the database — at the precise moment you were adding capacity because you were already struggling. The act of scaling up caused the outage."],
["p","Consistent hashing avoids this by not putting the node count into the calculation at all."],
["p","Picture the hash space as a circle. Each node is placed at several points around it. Each key is placed at one point, and belongs to the first node clockwise from where it landed. Nothing in that description mentions how many nodes there are."],
["p","Now add a node. It lands somewhere on the circle and takes ownership of the keys in the arc between itself and the node behind it. Those keys move. Every other key on the circle is exactly where it was, still owned by the same node, still a cache hit."],
["p","The fraction that moves is roughly one over N — about eight percent going from twelve to fourteen. That is not a clever optimisation, it is the theoretical floor: you cannot add capacity without moving some work onto it."],
["p","The several points per node matter more than they look. With one point each, the arcs come out wildly uneven, so some nodes own three times what others do — and worse, removing a node dumps its entire share onto whichever single neighbour sits next to it. A hundred or more virtual points per node smooths both problems away."],
["p","Now the limitation, and tonight it is the one that counts. Consistent hashing distributes keys evenly. It does not distribute load evenly. If forty thousand of your fifty thousand requests are for one key, that key lives on one node, and no hashing scheme ever invented will help. Which is the last section of this chapter."],
D("Consistent hashing — add a machine without moving everything",{say:"Cache machines will be added while we are under load, so I place both keys and machines on a ring and let each key belong to the next machine clockwise. Adding a machine then moves about one key in N, instead of nearly all of them.",
use:["Distributed caches, split databases, and any tier where machines join and leave and it matters which one holds what."],
avoid:["Small fixed clusters that never change, where a simple fixed assignment is easier to reason about.","Workloads where one key gets most of the traffic. Spreading keys evenly does nothing when everyone wants the same key."],
consider:["Give each machine a hundred or more positions on the ring. With one position each, the spacing comes out uneven, and removing a machine dumps all of its work onto a single neighbour.","Store each key on the next few machines clockwise as well, so losing one does not lose the data.","If different clients disagree about which machines exist, they will send the same key to different places. The ring has to be shared."],
fails:"A single very popular key still lands on one machine, and no arrangement of the ring changes that. And without multiple positions per machine, removing one overloads exactly one neighbour rather than spreading the load.",
alt:"Divide the space into a fixed number of virtual buckets — say a thousand — and assign whole buckets to machines. Or run a lookup service that simply records where everything lives.",
cases:["Going from twelve cache machines to fourteen on election night moves about fourteen percent of entries, not all of them.","One article is thirty percent of all traffic, so the machine holding it saturates regardless. That is a hotspot, covered at the end of this chapter."]}),
["ex","Adding 2 nodes to 10\nmod-N hashing        ~92% of keys move → every cache cold\nconsistent hashing   ~8% of keys move → the theoretical minimum"]
]},
{id:"health-checks",title:"Health checks and redundancy",blocks:[
["p","A server stops responding. Something has to notice, and the way you build that noticing is a surprisingly good way to cause an outage."],
["p","Here is the version that does it. Every server exposes a health endpoint, and to prove it is really working, that endpoint runs a query against the database."],
["p","The database has a two-second hiccup. Every health check fails at once. The load balancer, working exactly as designed, removes every server from rotation. The site is now down — and the database recovered a second ago."],
["p","The lesson generalises: a health check that depends on something shared turns one component's bad moment into total failure. Liveness checks should be shallow. Is this process alive and able to answer? Nothing more."],
["p","There is a second distinction that matters even more under load. Busy is not dead."],
["p","A server at a hundred percent utilisation is still doing useful work. If your check times out and the balancer evicts it, its traffic moves to the remaining servers — which are also at a hundred percent — so they slow down too, and fail their checks, and are evicted. Ninety seconds later everything is out of rotation and nothing has actually broken."],
["p","That is a cascade, and on election night it is the single most likely way for the site to fall over. It is also why a saturated server should shed load — refuse cheaply and immediately — rather than quietly fail a health check and get itself removed. Chapter 11 takes this apart properly."],
D("Health checks — deciding which servers get traffic",{say:"A shallow check for the load balancer, so a brief pause does not evict a healthy server. A deeper check for deployment, so a new instance only receives traffic once its caches and connections are ready.",
use:["Every tier sitting behind a load balancer."],
avoid:["Checks that query the database on every probe. When the database hiccups, every server fails its check simultaneously and the balancer removes all of them — so a two-second database problem becomes a total outage."],
consider:["Remove a server after several consecutive failures, and return it only after several consecutive successes. Reacting to a single failure makes the system twitchy.","A busy server is not a dead one. It should refuse work cheaply rather than fail its health check, because failing the check moves its traffic onto servers that are equally busy."],
fails:"Aggressive checks plus high utilisation produce a cascade. One server is evicted, the rest absorb its traffic, they slow down, they fail their checks too, and ninety seconds later everything is out of rotation with nothing actually broken. Chapter 11 covers this.",
cases:["Five servers at eighty percent each. Evict one and the remaining four are at a hundred. Plan capacity so you can lose your largest failure domain at peak."]}),
D("Active-passive — one machine serves, one waits",{say:"The database has a standby kept in sync that takes over if the primary fails. It is simple to reason about, at the cost of hardware that does nothing most of the time and a gap during the handover.",
use:["Systems holding data, where having two machines accept writes would create conflicts you then have to resolve."],
avoid:["Stateless tiers, where there is no reason not to have everything serving traffic."],
consider:["The standby never handles real traffic until the moment it must, which is the worst moment to discover it does not work. Practise the failover on purpose, regularly.","Failing over means noticing, promoting, and redirecting traffic — seconds to minutes during which writes fail."]}),
D("Active-active — everything serves traffic",{say:"Every application server takes requests, so losing one costs a fraction of capacity, and every machine is proven to work because it is working right now.",
use:["All stateless tiers.","Data tiers only when you have decided how to resolve conflicting writes, which Chapter 04 covers."],
consider:["If two machines can both accept writes for the same record, you need a rule for what happens when they disagree.","Keep enough spare capacity that losing an entire availability zone still leaves you able to serve peak traffic."]}),
D("Multiple regions — copies in different parts of the world",{say:"Users are global, so reads come from a nearby region while writes go to one designated region. I accept an extra hundred milliseconds on writes in order to avoid having to resolve conflicts.",
use:["A genuinely global user base, where the speed of light is the problem.","A business that cannot survive an entire region being unavailable."],
avoid:["Doing it because it sounds robust. It roughly doubles the cost and turns every consistency question into a hard one."],
consider:["Stateless servers and cached content replicate easily. The database is the entire difficulty.","One region accepting all writes means distant users have slow writes. Several regions accepting writes means conflicts. Choose per dataset rather than for the whole system.","Spreading across availability zones within one region is the cheap default and handles most failures. Spreading across regions is the expensive exception."]}),
["p","And notice what autoscaling cannot do for you tonight."],
["p","It reacts in minutes: observe the load, decide, start instances, boot them, warm their caches, add them to the pool. The result arrives in seconds. By the time the new capacity is serving traffic, the moment that needed it has passed and the moment that follows is a different shape entirely."],
["p","Autoscaling handles the shape of an ordinary Tuesday, and it does that well. For a spike you know is coming, you pre-scale hours ahead and pay for capacity you have not used yet. That is not a failure of the tooling; it is what buying insurance looks like."],
D("Autoscaling — add machines automatically as load rises",{say:"Autoscaling handles the ordinary daily curve. For election night I would add capacity hours in advance and let autoscaling handle only the wind-down, because it reacts in minutes and the spike arrives in seconds.",
use:["Predictable daily patterns and steady growth.","Pools of workers scaling on how much work is waiting in the queue."],
avoid:["Sudden spikes and launches. Add the capacity beforehand.","Databases. They do not scale this way, so protect them with caches and queues instead."],
fails:"It scales down during a lull and a second wave arrives before the new machines are ready. Or it scales on processor usage when the actual bottleneck is the database, so it adds machines that make the problem worse."})
]},
{id:"hotspots",title:"Hot partitions and uneven traffic",blocks:[
["p","Everything so far has quietly assumed that traffic spreads out. Tonight it does not."],
["p","Forty thousand of your fifty thousand requests are for one results page. Every technique in this chapter distributes requests evenly across servers — and then every one of those servers turns around and needs the same cache entry from the same cache node. You have balanced the requests perfectly and concentrated the load perfectly."],
["p","This is the difference between a scale problem and a hotspot, and it is worth being able to say out loud: adding servers does not fix a hotspot, because the servers were never the constraint. The constraint is that one piece of data is wanted by everybody at once, and it can only live somewhere."],
["p","There are only a handful of real moves, and all of them trade locality against balance."],
["tbl",{cols:["Fix","Use when","Tradeoff"],rows:[
["Cache closer (CDN / in-process)","Hot object is public or per-server staleness is OK","Hardest to invalidate; 10 s edge TTL removes 99.9% of origin traffic"],
["Replicate the key","One cache node saturates","Write to K nodes, read from any; K× cache writes"],
["Salt the key","Counter or list written/read at extreme rate","results:0…9 spreads load; fan-in on read"],
["Coalesce requests","Hot key expires under load","One refill, others wait ms; needs a lock or single-flight"],
["Better partition key","Hotspot is structural (partition by date)","Partition by article id spreads writes; loses range-by-time locality"],
["Dedicated pool","One tenant/event dominates","Isolation; capacity may idle"]]}],
["p","On election night the move that does most of the work is the first one: cache closer. A ten-second TTL at the CDN sounds uselessly short until you do the arithmetic. Ten seconds means the origin serves that page six times a minute — regardless of whether fifty people are reading it or fifty million."],
["p","Ten seconds of staleness on a page whose numbers change every thirty seconds is invisible to a reader, and it removes something like 99.9% of the traffic before it reaches anything you own. That is the whole trade: a small, bounded lie about freshness in exchange for three orders of magnitude."],
D("Name the hotspot before you are asked about it",{say:"The results page is the hot key. It goes to the content delivery network with a ten-second expiry and the old copy served while refreshing. The counter is spread across several keys and refilled by one worker, so the database sees one write per update rather than one read per visitor.",
use:["Every design. There is always one, and finding it is most of the work."],
consider:["Hotspots come from a small number of places: one object everyone wants, one customer far larger than the rest, one time range such as today, or one accidental value like an anonymous user id of zero.","Say it before the interviewer does. Naming your own weak point is the difference between having designed something and having drawn something."],
cases:["A celebrity account posting, covered in Chapter 14.","Tickets going on sale for one event, covered in Chapter 18.","Today's date in a table split by date, covered in Chapter 04."]}),
["t","Hotspot mitigation is locality vs balance: caching close is fastest and hardest to invalidate; salting spreads load and costs a fan-in on every read."]
]}
]};
