const D = (name, o) => ["dec", { name, ...o }];
export default {id:"observability",num:"09",title:"Observability and production operations",example:"a ride-hailing dispatch service",
tagline:"Metrics detect, traces localise, logs explain. Each signal and each SRE practice as a decision: when to use it, when not, what it costs.",
terms:["Metrics vs traces vs logs","Request ID","SLI / SLO / SLA","Error budget","Golden signals","Burn rate","Postmortem"],
objectives:["Pick the signal by the question it answers during an incident","Propagate a request id across services and queues","Define an SLI, set an SLO, derive the error budget and use it to make decisions","Alert on symptoms at two burn rates and not on causes","Close a deep dive with how you'd know it broke"],
sections:[
{id:"signals",title:"Which signal for which question",blocks:[
["p","A rider waits eleven seconds for a car at three in the morning. Four services were involved. Which one was slow, for how many people, and since when?"],
["p","If you cannot answer that in two minutes, the problem is not that you are missing a dashboard. It is that the ability to answer was never designed in — and it cannot be added during the incident."],
["p","There are three kinds of signal, and the useful way to hold them is by the question each one answers."],
["p","Metrics detect. They are cheap aggregates over time — request rate, error rate, p99, saturation — so you can keep them for everything, forever, and alert on them. What they cannot do is say anything about an individual request. A metric will tell you that pricing's p99 jumped at 03:10. It will never tell you which requests, or why."],
["p","Traces localise. A trace follows one request across every service it touched and shows where the time actually went: 1,840 milliseconds in pricing, forty milliseconds everywhere else. That is precisely the question metrics cannot answer."],
["p","Logs explain. Once you know it was pricing, the log lines for that request tell you what pricing was doing while it took 1,840 milliseconds."],
["p","Detect, localise, explain. Skip one and you get a characteristic failure. Only logs, and you find out about outages from users. Only metrics, and you know something is wrong but never where. Only traces, and you are sampling a system nobody is watching."],
["p","The thing that makes all three work together costs almost nothing and is forgotten constantly: a single request id, generated at the edge, attached to every log line, propagated on every outbound call — and, the step everyone misses, carried in the headers of every queue message."],
["p","A request that crosses a queue and loses its id becomes two unrelated stories, and the asynchronous half is exactly the half that is hard to debug."],
["p","One practical note on cost. Traces are sampled, because tracing every request costs more than serving it. Sample a small fraction of successful requests and keep every slow one and every error, since that is where the information was to begin with."],
D("Metrics",{say:"Dispatch p99, error rate, saturation and request rate are metrics — cheap aggregates that detect the problem and drive alerts.",
use:["Detection and alerting; dashboards; anything you graph over time"],
avoid:["Per-request detail; high-cardinality tags (a metric per user is a database, not a metric)"],
consider:["Tag with service, region, status — few, low-cardinality dimensions","Tells you pricing's p99 jumped at 03:10; can't tell you which requests"]}),
D("Distributed traces",{say:"Every hop carries the trace id — including queue message headers — and we sample 5% plus all errors, so the trace for r-8813 shows 1,840 ms in pricing and 40 ms everywhere else.",
use:["Any system with more than two services or a queue in the request path","Localising latency"],
avoid:["A monolith — a profiler does it","100% sampling — costs more than the system"],
consider:["Head-based sampling for volume; tail-based to keep every slow/error trace","Propagation through queues is the step everyone forgets"],
fails:"One service drops the header → the trace ends there and the problem is invisible."}),
D("Structured logs",{say:"Logs are JSON with the request id, sampled for routine requests and kept for every error — they explain what a metric detected and a trace localised.",
use:["Incident investigation; audit trails (separate stream, longer retention)"],
avoid:["Free-text logs you can only grep","Logging every request at full volume — expensive; sample"],
consider:["Correlation: X-Request-Id from the edge through every service and message"]}),
["ex","Edge      X-Request-Id: r-8813\nDispatch  {req: r-8813, svc: dispatch}\nPricing   {req: r-8813, svc: pricing, dur_ms: 1840}\nQueue msg headers carry req\nNotifier  {req: r-8813, svc: notifier}\nOne search on r-8813 reconstructs the story."],
["t","Only logs: you learn about problems from users. Only metrics: you know something's wrong, not where. All three, and accept traces are sampled and logs cost."]
]},
{id:"slo",title:"SLIs, SLOs, SLAs and the error budget",blocks:[
["p","Now the harder question: what does working mean, stated precisely enough that a machine can page somebody about it?"],
["p","It means choosing one thing you measure, one target for it, and accepting the consequences of both."],
["p","The measurement is the SLI — the fraction of dispatch requests completing in under two seconds. Measure it at the edge, where the rider is, rather than inside your service where the numbers are more flattering and less true."],
["p","The target is the SLO, and this is where most teams go wrong. They pick 99.99% because it sounds professional. Each additional nine costs roughly ten times the last, and the rider's mobile network is nowhere near four nines, so you would be spending enormous sums improving something no user can perceive."],
["p","The SLA is a third, separate thing: what you promise customers contractually, with money attached. It should always be looser than your internal SLO, so that missing your own target is a warning rather than an invoice."],
["ex","SLI  fraction of dispatch requests completing under 2 s\nSLO  99.5% over 30 days\nSLA  99% to enterprise customers, with credits (looser than the SLO)\nBudget 0.5% ≈ 3.6 h of failing requests per 30 days"],
D("Setting the SLO",{say:"99.5% under two seconds — the level a rider can perceive. Not 99.99%: their phone network isn't there, and each nine costs ten times more.",
use:["One or two user-facing SLIs per service"],
avoid:["Targets set by what impresses engineers rather than what users feel","Internal SLO looser than the external SLA"],
consider:["Latency at a percentile, success rate, freshness","Measure at the edge, where the user is"]}),
["p","Subtract the SLO from a hundred percent and you have the error budget: half a percent of thirty days, which is about three and a half hours of failing requests you are permitted to spend."],
["p","That number exists to change conversations, and that is genuinely its main purpose. Budget remaining means ship the risky migration this week. Budget exhausted means launches pause until reliability recovers. Outages and risky deploys draw down the same account, which is the honest way to describe reality."],
["p","And because the number was agreed in advance by product and engineering together, the argument at three in the morning is about what to do rather than about whether reliability matters at all. That is a much better argument to be having at three in the morning."],
D("Spending the error budget",{say:"Budget remaining → ship the risky migration this week. Budget exhausted → launches freeze until reliability recovers. Product and engineering agreed to the number in advance, so 3 a.m. is about what to do, not whether it matters.",
use:["Every reliability-vs-velocity decision"],
consider:["Outages and risky deploys spend the same budget","Publish budget remaining on the dashboard"]}),
["tbl",{cols:["Nines","Downtime / year","Downtime / month"],rows:[["99%","3.65 days","7.3 h"],["99.9%","8.8 h","44 min"],["99.99%","53 min","4.4 min"],["99.999%","5.3 min","26 s"]]}]
]},
{id:"alerting",title:"Golden signals and alerting that gets read",blocks:[
["p","Four signals are worth watching on everything, with one refinement: measure latency for successful and failed requests separately. A fast error is not good latency, and averaging the two together can make an outage look like an improvement."],
["tbl",{cols:["Signal","Measure","Use"],rows:[["Latency","p99, split by success/failure","A fast error isn't good latency"],["Traffic","rps, rides/min","Context for everything else"],["Errors","5xx, wrong 200s, over-SLO responses","The symptom users feel"],["Saturation","CPU, memory, pool, queue depth","Predicts the other three"]]}],
["p","Then the single rule that decides whether your alerts get read at all: page on symptoms, not causes."],
["p","CPU at ninety percent is a cause. It might mean trouble. It might mean you are finally using the hardware you paid for. If it wakes somebody at three in the morning and everything turns out to be fine, they will learn — correctly — that the pager lies, and within a month they will be silencing it during real incidents."],
["p","Requests failing their SLO is a symptom. It always matters, because by construction it is the thing the user is experiencing."],
["p","Two burn rates, because outages arrive in two shapes. A fast burn — at this rate the whole month's budget is gone within hours — pages immediately. A slow burn — gone in weeks — opens a ticket for working hours. Without the first, a sharp outage goes unnoticed for an hour. Without the second, a persistent low-grade problem never gets fixed because it never quite crosses a line."],
["p","And review every page you send. Was it actionable? If it was not, delete the alert. An alerting system nobody trusts is worse than no alerting system, because it costs sleep and buys nothing."],
D("Page on symptoms at two burn rates",{say:"A fast-burn page: the budget will be gone in hours. A slow-burn ticket: gone in weeks. Cause-level alerts (CPU 90%) go to dashboards, never pagers.",
use:["Every service with an SLO"],
avoid:["Paging on causes — on-call learns to silence the pager within a month","Only slow-burn — a sharp outage goes unnoticed for an hour"],
consider:["Review every page: was it actionable? If not, delete it","Dashboard answers 'us or a dependency?' in ten seconds: four signals, SLO, budget, dependencies below"]})
]},
{id:"operations",title:"Capacity, incidents, postmortems",blocks:[
["p","Two practices and one closing habit."],
["p","Capacity planning is mostly a matter of noticing that some spikes are on a calendar. New Year's Eve is six times a normal Friday for dispatch. That is knowable weeks ahead, which makes it a provisioning decision rather than an incident. Provision with headroom for losing a zone at peak, and let the saturation signal tell you where the forecast was wrong."],
["p","Incident response works better with roles than with heroics. One person is the incident commander and decides; others investigate and communicate. Mitigate first — roll back, fail over, shed load — and find the root cause afterwards. The instinct to understand before acting is a good engineering instinct that costs users real minutes."],
["p","And the postmortem is blameless not because blame is impolite but because it is inaccurate. The engineer who ran the command was the last link in a chain that permitted it. Stop at them and the chain is still there, and the next person will find it."],
["p","Write what happened minute by minute, what users experienced, why the system allowed it, and what changes — with owners and dates. An incident without a postmortem is an incident you have quietly agreed to have again."],
D("Capacity planning",{say:"New Year's Eve is 6× a normal Friday for dispatch; we provision ahead with headroom for losing a zone, and the saturation signal tells us when the forecast was wrong.",
use:["Growth forecasts, launches, seasonal peaks; anything with weeks of lead time"],
consider:["Load tests validate the projection","Headroom = peak + loss of largest failure domain"]}),
D("Incident response",{say:"One incident commander decides; others investigate and communicate; mitigate first (roll back, fail over, shed), root-cause second; timeline kept as it happens.",
use:["Every page"],
avoid:["Heroics without roles; root-causing while users are down"]}),
D("Blameless postmortem",{say:"What happened minute by minute, impact in user terms, why the system allowed it, what changes — with owners and dates. Never who. An incident without a postmortem is one we've agreed to repeat.",
use:["Every incident that touched the budget"],
avoid:["Postmortems with no action items — a well-documented history of the same incidents"]}),
["ex","Closing a deep dive\n\"We trace every dispatch request end to end, page on a fast burn of\nthe 2-second SLI, watch saturation on the location index — it fails\nfirst under load — and plan New Year's Eve at 6× a normal Friday.\""]
]}
]};
