const D = (name, o) => ["dec", { name, ...o }];
export default {id:"queues",num:"09",title:"Queues, streams and asynchronous processing",example:"a video upload pipeline",
tagline:"Sync call, task queue, pub/sub or durable log — and which delivery guarantee — each as a decision with its use-when, don't-use-when, cost and failure.",
terms:["Task queue vs log","Partition","Consumer group","Offset","At-least-once","Idempotent consumer","Backpressure","DLQ","Log compaction"],
objectives:["Pick the shape of asynchrony from: needs the answer now? how many consumers? does history matter?","Choose partition count and key from ordering and parallelism needs","Choose a delivery guarantee and make the consumer idempotent","Design for lag, backpressure, poison messages and replay","Sketch the upload pipeline end to end"],
sections:[
{id:"shape",title:"Which shape of asynchrony",blocks:[
["p","Someone uploads a ten-minute video. Transcoding it into six resolutions takes about four minutes. The upload request cannot take four minutes."],
["p","So something has to be decoupled. This chapter is about choosing which shape of decoupling, and three questions settle it: does the caller need the result in order to continue, how many things need to react, and will the history matter later?"],
["p","Check that this user is allowed to upload. The answer changes what happens next, so it stays a plain synchronous call."],
["p","Generate a thumbnail. One consumer, done once, and nobody will ever need to look at that instruction again. That is a task queue: a job goes in, a worker takes it, completes it, and the job is deleted."],
["p","Now transcoding, moderation and analytics all need to know that a video was uploaded. Three independent consumers, none of which should have to know the others exist. A task queue does not fit, because whoever takes the job removes it and the other two never see it. This is publish-subscribe."],
["p","And then the question that decides between an ordinary message broker and a durable log. Six months from now you will improve the moderation model and want to re-run it across everything uploaded since launch. Can you?"],
["p","With a queue, no. A consumed message is gone — the queue's job was to deliver it, and it did. With a log, events are retained independently of whether anyone has consumed them. Consumers hold a position rather than a claim, so adding a consumer next year means starting one at whatever offset you like and letting it read through history at its own pace."],
["p","That single property is what justifies the operational weight of running a log. And if you do not need it, you should not be running one. A jobs table in the database you already have, polled by a handful of workers, is a completely respectable answer for a great many systems, and saying so out loud scores better than reaching for Kafka by reflex."],
D("Just call it and wait",{say:"Is this user allowed to upload? That is a yes or no we need before doing anything else, so it is an ordinary call with a timeout.",
use:["Cases where the caller cannot continue without the answer."],
avoid:["Anything that takes longer than a request should.","Side effects the caller does not need confirmed."]}),
D("Task queue — one job, one worker, then it is gone",{say:"Generating the thumbnail is one piece of work, done once, by whichever worker picks it up. Then the job is deleted. Workers scale on how much is waiting.",
use:["Work with exactly one consumer and no need for history: emails, thumbnails, exports, outbound webhooks."],
avoid:["Cases where several systems need to know about the same event. Whoever takes the job removes it, so the others never see it.","Cases where you will want to reprocess everything later. Once consumed, it is gone."],
consider:["A job is hidden rather than deleted while a worker holds it. If that hidden period is shorter than the work takes, the job is handed to a second worker while the first is still going.","Because jobs can be redelivered, anything not safe to run twice needs protecting.","After a few failed attempts, move the job aside rather than retrying forever."]}),
D("Publish and subscribe — one event, several independent reactions",{say:"A video-uploaded event is consumed by transcoding, by moderation and by analytics, none of which know the others exist. Adding a fourth consumer next quarter changes nothing upstream.",
use:["Several independent systems reacting to the same fact."],
avoid:["A single consumer, where a task queue is simpler.","Cases where the publisher needs to know that everyone finished. It has no way to find out."],
consider:["Every subscriber needs its own retry behaviour and its own place to put messages it cannot handle.","Debugging now spans several consumers, which is why the request id has to travel with the message."]}),
D("Durable log — events are kept, not consumed away",{say:"Transcoding takes minutes, three systems react to an upload, and we will want to reprocess everything when the moderation model improves. So the event goes into a log, keyed by video, and each consumer keeps its own position and can be rewound.",
use:["Events that must be retained, replayed, kept in order per key, and read by several independent systems.","Events that are facts about the business rather than instructions to do work."],
avoid:["A request that needs an immediate answer.","One consumer with no need for history, where a task queue is far lighter.","Teams without the appetite to operate a cluster. A jobs table polled by workers is a respectable answer and worth saying out loud."],
consider:["It is real operational weight: brokers to run, partition counts decided early, and reassignments when consumers come and go.","Everything downstream is now eventually consistent, and you should say by roughly how much."],
fails:"The backlog grows quietly while every message is processed correctly. One message that always fails blocks everything behind it in its partition. And too few partitions caps your parallelism permanently, because changing the count reshuffles which key goes where.",
alt:"A task queue plus publish-subscribe. Reading the database's change log. Or a jobs table that workers poll, which is the simplest thing that works.",
cases:["A new consumer added next year can read the last seven days from the beginning.","The moderation model was wrong for a week, so you move that consumer's position back and reprocess."]}),
["t","A task queue is simplest when work has one consumer and no history matters. A log costs a cluster and lets you add a consumer next year that reads every event since launch."]
]},
{id:"partitions",title:"Partitions, keys, consumer groups, retention",blocks:[
["p","A log is not one sequence. It is several, and how events are divided between them determines both your ordering guarantee and your ceiling on parallelism."],
["p","Order exists inside a partition and nowhere else. Two events in the same partition are read in the order they were written. Two events in different partitions have no defined order at all — not a weak one, none."],
["p","So the key is whatever needs ordering. Here that is video_id: uploaded, transcoded and published for one video land in one partition and are seen in sequence, while events for different videos sit in different partitions and are processed simultaneously."],
["p","Notice what you deliberately did not ask for. A single global order across every event in the system would require a single partition, and a single partition means a single consumer, which means no parallelism whatsoever. That is why nobody sells it."],
["p","Ordering is not free. It is bought by giving up concurrency, and the craft is buying exactly as much as the invariant needs and not one unit more. This is head-of-line blocking from Chapter 05 wearing different clothes: ordering within a scope, and the scope is the part you choose."],
["p","Two practical consequences follow. Partition count is close to permanent, because changing it re-maps keys to different partitions — so ordering breaks across the change and a single key's history ends up split between two places. Pick for the parallelism you will want in two years, not the parallelism you need this week."],
["p","And a consumer group can never usefully have more instances than partitions. Forty-eight partitions means at most forty-eight transcoders doing work; the forty-ninth starts up, is assigned nothing, and sits there costing money."],
D("Partition key — what decides ordering and parallelism",{say:"Every event is keyed by video id, so all events for one video land in the same partition and are read in order — uploaded, then transcoded, then published — while different videos are processed at the same time.",
use:["Choose the key as whatever must be ordered: a conversation, an account, a video."],
avoid:["A key with only a handful of possible values, which sends most traffic to one partition.","No key at all when order matters, because messages are then spread arbitrarily."],
consider:["Order exists inside a partition and nowhere else. Two events in different partitions have no defined order at all.","A single global order would need a single partition, which means a single consumer and no parallelism. That is why nobody offers it."]}),
D("How many partitions — a decision you cannot easily undo",{say:"Forty-eight partitions. That is the ceiling on how many transcoders can work at once, and it needs to cover the next two years, not this quarter.",
use:["Set it for the parallelism you expect at peak, well beyond today."],
avoid:["Changing it later. Keys are assigned by hashing, so changing the count moves keys to different partitions — which breaks ordering across the change and splits a key's history."],
consider:["More partitions mean more parallelism and also more files, more connections, and slower reassignment when consumers change.","Consumers beyond the partition count sit idle. The forty-ninth transcoder starts up, is given nothing, and costs money."]}),
D("Consumer groups — each system keeps its own position",{say:"Transcoding and moderation are separate groups reading the same events, each with its own position in the log. Neither can slow the other down or consume the other's messages.",
use:["One group per independent system that needs the events."],
consider:["Within a group, partitions are shared out between the running instances. Adding or removing an instance triggers a reshuffle, during which processing briefly pauses.","Record your position after processing, not before. Before means a crash loses the message; after means a crash repeats it, which is the safer of the two."]}),
D("Retention — how long events are kept",{say:"Event topics keep seven days so we can replay. The topic holding current video metadata is compacted instead, so it always holds the latest state per video and can rebuild a cache from nothing.",
use:["Time-based retention for a history of things that happened.","Compaction for topics representing current state, where only the newest value per key matters."],
consider:["Retention is independent of whether anyone has read the messages. That independence is exactly what makes replay possible.","Compaction keeps the most recent record per key indefinitely and discards the older ones, so the topic stays bounded while remaining complete."]}),
["ex","video.uploaded     key video_id · 48 partitions · 7 d\nvideo.transcoded   key video_id · 48 partitions · 7 d\nvideo.metadata     key video_id · compacted"]
]},
{id:"guarantees",title:"Delivery guarantees and idempotent consumers",blocks:[
["p","The transcoder finishes a video, writes the output, and crashes before acknowledging the message. What happens?"],
["p","It gets redelivered. That is not a bug; it is the only safe behaviour available. The broker cannot know whether you finished, because the acknowledgement is the thing that would have told it, and the acknowledgement is exactly what went missing. Offered a choice between possibly losing the message and possibly delivering it twice, at-least-once chooses twice."],
["p","Which means duplicates are not an exceptional condition to be handled if there is time at the end of the sprint. They are routine, and they are guaranteed — every deploy, every consumer rebalance, every time a worker is killed."],
["p","So the design question is not how do I stop duplicates. It is: what happens when this handler runs twice?"],
["p","For the transcoder there is a lovely answer. Write outputs to a deterministic path derived from the video id and version. A second run produces identical bytes at the identical location and harmlessly overwrites itself. The work is wasted; the result is unchanged. That is idempotence obtained for free, purely by choosing the path scheme carefully."],
["p","When the effect is not naturally repeatable — charging a card, sending an email, incrementing a total — you fall back to recording the processed event id in the same transaction as the effect, exactly as in Chapter 10. Deliver many times, act once."],
["tbl",{cols:["Guarantee","Use when","Tradeoff"],rows:[["At-most-once","Losing beats duplicating (metrics samples)","Ack before processing; messages vanish on crash"],["At-least-once","Must eventually be processed — everything serious","Ack after processing; duplicates on crash-before-ack"],["Effectively once","Duplicates must not change the result","At-least-once + idempotent consumer"]]}],
D("Idempotent consumer — safe to run the same message twice",{say:"The transcoder writes its output to a location derived from the video id and version. Running the same message twice produces identical bytes in the same place, so a redelivery is harmless — wasted work, unchanged result.",
use:["Every consumer that changes anything. Assume duplicates, because they are guaranteed."],
avoid:["Assuming exactly-once delivery is available. It is not, and the gap is between acting and acknowledging, which the broker cannot see."],
consider:["Either record the processed event id in the same transaction as the effect, or make the effect naturally repeatable by writing to a computed location.","A table of processed ids per consumer, with an expiry, works for effects that are not naturally repeatable.","Producer-side deduplication only removes duplicates between the producer and the broker. It does nothing about the consumer crashing."],
fails:"The check for whether you have seen this message and the effect itself are not in one transaction, so a crash in between lets the duplicate through anyway.",
cases:["A reshuffle mid-job hands the same message to a different instance.","A deploy restarts workers, so everything in flight is redelivered.","You replay a week deliberately after fixing a bug, so every event arrives again on purpose."]}),
["t","At-least-once plus idempotency costs one lookup per message. Without it every retry, redeploy and rebalance is a potential double effect. Ask of every handler: what happens when this runs twice?"]
]},
{id:"operating",title:"Lag, backpressure, poison messages, replay",blocks:[
["p","The pipeline is built. Now the part that decides whether it survives contact with production."],
["p","The health metric for a queue is not the error rate. It is lag."],
["p","A pipeline failing loudly is fine — you will hear about it within minutes. A pipeline succeeding at ninety percent of the rate work arrives is silently accumulating a backlog while processing every single message correctly. Nothing errors. Nothing alerts. The only symptom is that a creator's video has said processing for an hour, and by the time anyone investigates, the backlog is six hours deep and will take all night to drain."],
["p","So alert on lag, and measure it in seconds rather than messages. A backlog of a hundred thousand messages means nothing at all until you know how fast you drain them."],
["p","When lag does grow there are exactly three levers, and it is worth having them ranked before you need them. Add consumers, up to the partition count. Do less work per message — drop the 4K rendition first, since almost nobody watches it. Or slow the producers, which for an upload pipeline means telling users their video will take longer than usual."],
["p","There is no fourth lever. A queue is a buffer, not infinite capacity, and a buffer that never drains is just a slower way to run out of disk."],
["p","One more failure worth designing for in advance. A single corrupt upload that crashes the transcoder will be redelivered forever, and because ordering is per partition, it blocks every message behind it in that partition. Three attempts, then move it aside to a dead-letter queue with the error attached, and alert on how deep that queue gets. Retrying forever on a message that can never succeed is not resilience. It is a stuck pipeline that looks busy."],
D("Lag — the number that tells you a pipeline is sick",{say:"We alert on how far behind the consumers are, measured in minutes, rather than on the error rate. A backlog looks like nothing is wrong right up until a creator's video has said processing for an hour.",
use:["Every pipeline."],
consider:["Measure it both in messages and in seconds. A hundred thousand messages means nothing until you know how fast you drain them.","A pipeline succeeding at ninety percent of the arrival rate is silently falling behind while processing every message correctly. Nothing errors and nothing alerts."]}),
D("Backpressure — what to do when you cannot keep up",{say:"When the backlog grows: add workers up to the partition count; if still behind, stop producing the highest-quality rendition; if still behind, tell people uploads are delayed. The queue is a buffer, not unlimited capacity.",
use:["Any producer capable of outrunning its consumers, which is most of them."],
avoid:["Letting the backlog grow until the broker runs out of disk. That converts a slow pipeline into an outage."],
consider:["There are only three levers: process faster, do less work per message, or slow the producers. Rank them before you need them."]}),
D("Dead-letter queue — somewhere to put messages that always fail",{say:"A corrupt upload that crashes the transcoder goes aside after three attempts, with the error attached, so the partition keeps moving and a person can look at it later.",
use:["Every consumer."],
avoid:["Retrying forever. Because ordering is per partition, one message that can never succeed blocks everything behind it."],
consider:["Alert on how many messages are sitting there. A queue nobody looks at is just a slower way to lose data.","Build the path for reprocessing them once fixed, or they accumulate forever."]}),
D("Replay — reprocessing history on purpose",{say:"Fix the model, move the moderation consumer's position back a week, and let it reprocess. This is safe precisely because the consumer was already written to tolerate duplicates.",
use:["Fixing a bug retroactively, adding a new consumer, or rebuilding a derived store from scratch."],
consider:["It requires retention and safe-to-repeat consumers, both of which you already needed for other reasons. Replay is the reward for having done them."]}),
["ex","Upload pipeline, end to end\n1 Client → presigned multipart upload → object storage\n2 API: video row UPLOADED + outbox event, one transaction     (Ch. 10)\n3 Relay → video.uploaded (key video_id)\n4 Transcoder group: GPU workers, idempotent on (video_id, version),\n  deterministic output paths → video.transcoded\n5 Moderation group reads the same topic independently\n6 Publisher: status READY, cache invalidated                   (Ch. 08)\n7 Lag alert 5 min · DLQ after 3 · 7-day replay window"]
]}
]};
