const D = (name, o) => ["dec", { name, ...o }];
export default {id:"security",num:"10",title:"Security and privacy",example:"a multi-tenant SaaS document platform",
tagline:"Where identity is checked, where permission is checked, how tenants are kept apart — each as a decision that shapes the data model, not a closing ritual.",
terms:["AuthN vs AuthZ","Session vs JWT","OAuth / OIDC","RBAC vs ABAC","Row-level security","Rate limiting","PII & deletion"],
objectives:["Place authentication at the edge and object-level authorization in the service","Choose sessions or JWTs from the revocation requirement","Pick a tenant-isolation model from tenant count and risk","Name the standard vulnerabilities and the one decision that removes each","Treat abuse as a scale problem with an adversary"],
sections:[
{id:"authn-authz",title:"Authentication at the edge, authorization on the object",blocks:[
["p","Your platform hosts documents for four thousand companies in one database. A user at company A requests document 8813, which belongs to company B. What stops them?"],
["p","Not the login. They are logged in. Their token is valid and unexpired. They are exactly who they claim to be and they have every right to be using the product. The only thing wrong with the request is the number in it."],
["p","Which is why the two words must be kept apart. Authentication is who you are. Authorization is what you may do, and to which specific object."],
["p","The gateway settles authentication once, for everybody, and it cannot settle authorization, because it has no idea that document 8813 belongs to company B. That fact lives in the document service's database and nowhere else."],
["p","So the check happens in the service, on every request, against the object being requested. Not is this user an editor — that is a role check, and roles describe categories of action rather than instances. The question is may this user edit this document."],
["p","Skipping it has a name, broken object-level authorization, and it is consistently the most common serious finding in real API security audits. It is worth being blunt about why. This is not an exotic attack requiring skill or tooling. It is changing a number in a URL."],
["p","One detail with an outsized effect: when the check fails, return 404 rather than 403. A 403 confirms the document exists, and existence is itself information — how many documents a competitor holds, whether a guessed customer id is real. Say nothing at all."],
D("Object-level authorization in the service",{say:"The gateway proves who you are; the document service checks on every read that this document belongs to your tenant and is shared with you — otherwise a valid token reads any document by changing the id.",
use:["Every resource read or write"],
avoid:["Trusting a valid token as permission (broken object-level authz — the most common API audit finding)","Role checks alone ('is editor?') without the object ('may edit THIS?')"],
consider:["Authentication = who; authorization = what, on which object","Enforce below the app where possible (row-level security)"],
cases:["Editor in tenant A requests doc in tenant B → 404, not 403 (don't confirm existence)","Shared link revoked while a viewer has the doc open → re-check on next fetch"]}),
D("RBAC vs ABAC",{say:"Three roles per tenant — viewer, editor, admin — plus one attribute rule: editors may edit documents they own or that are shared with them.",
use:["RBAC: a few roles cover the needs; easy to audit","ABAC: rules on ownership/sharing where roles over-grant"],
avoid:["Dozens of roles — a maintenance burden nobody can reason about","Attribute rules everywhere — nobody can audit them"],
consider:["Least privilege for services too: the indexer reads documents; it holds no write credential"]})
]},
{id:"tokens",title:"Sessions or JWTs; OAuth and OIDC",blocks:[
["p","How does the service know who the caller is on every request? There are two answers, and the choice is decided by a single requirement: how quickly must revocation take effect?"],
["p","A server-side session is an opaque id that the server looks up on each request. Because there is a lookup, deleting that row logs the user out instantly. This matters when an employee is removed at four in the afternoon and must lose access at four in the afternoon. The cost is a lookup per request, which turns the session store into a hot dependency you have to replicate and protect."],
["p","A JWT is signed, so any service can verify it with a public key and no lookup at all. That is exactly why it scales across many services. And it carries one consequence that people consistently under-weight: you cannot revoke it."],
["p","The token stays valid until it expires, because its validity is a mathematical property of the signature rather than a database row you can delete. So logging out, changing a password and being removed from a company do not actually end the session. They end the ability to obtain a new token."],
["p","Which is why the practical answer is both. Short-lived JWTs — fifteen minutes — plus a long-lived refresh token held server-side and therefore revocable. The worst case becomes fifteen minutes of stale access, and genuinely sensitive actions can additionally check a revocation list. You keep most of the scalability and you cap the exposure."],
["p","And one small rule with a large history behind it: verify the algorithm, the issuer and the audience, and reject alg: none outright. Every clause in that sentence exists because a real library once accepted a token that essentially said trust me, I am unsigned."],
D("Server-side sessions",{say:"Revocation must be instant here (a removed employee loses access now), so an opaque session id looked up per request — the session store becomes a hot dependency I'll replicate.",
use:["Instant revocation is a hard requirement","One application, one store"],
avoid:["Many services each needing a lookup per request"],
consider:["A lookup per request; the store must be fast and available"]}),
D("Short JWT + refresh token",{say:"15-minute JWTs any service verifies with the public key, a server-side refresh token that can be revoked, and a revocation-list check only on sensitive actions.",
use:["Multi-service systems; verification without a lookup"],
avoid:["Long-lived JWTs — a leaked token works until expiry","Storing PII in claims"],
consider:["Rotate signing keys with a kid; verify issuer and audience; reject 'alg: none'"],
fails:"Log out, change password, remove from tenant — the old token still works until expiry unless you check a list."}),
D("OAuth 2.0 and OpenID Connect",{say:"Each tenant plugs in its own identity provider via OIDC — a security feature and the enterprise-sales requirement that unlocks the biggest customers.",
use:["Delegated access to another service's data (OAuth)","Sign-in with an identity provider / enterprise SSO (OIDC)"],
avoid:["Rolling your own token exchange"],
consider:["Scoped, revocable tokens; PKCE for public clients"]}),
D("Secrets",{say:"Signing keys and DB passwords come from a secrets manager at runtime, rotate on schedule, and never appear in code, images, logs or error messages.",
use:["Every credential"],
avoid:["A signing key that can't rotate without logging everyone out — it will never be rotated"]})
]},
{id:"data",title:"Protecting data and closing the classic holes",blocks:[
["p","Most of the classic vulnerabilities have exactly one correct answer each, and in every case the answer is structural rather than a matter of being careful."],
["tbl",{cols:["Vulnerability","The one decision that removes it","Where"],rows:[["SQL injection","Parameterised queries — no other acceptable answer","Every query"],["XSS","Output encoding by context + CSP; strict allow-list sanitiser for rich text","Every render of user content"],["CSRF","SameSite cookies + per-request token","Every state-changing form/API from a browser"],["Broken object authz","Check ownership/sharing on the object, every request","Every service"],["SSRF / path traversal","Validate and allow-list at the boundary; reject, don't sanitise","Any user-supplied URL or path"]]}],
["p","The pattern running through that table is worth naming. In every row the fix is to stop constructing something and start parameterising it, or to stop sanitising input and start rejecting it against an allow-list."],
["p","Both work by removing the opportunity rather than by remembering to be vigilant, and only that kind of fix survives contact with a team of thirty people and a deadline."],
["p","Then two things that are genuine design decisions rather than checkboxes."],
["p","Per-tenant encryption keys sound like a compliance detail and are actually an architectural convenience. When a customer leaves and requires their data destroyed, you have a real problem: their rows are in replicas, in backups, in the search index and in the warehouse — and backups are immutable by design, which is the entire point of them."],
["p","Destroy the key instead, and every copy becomes unrecoverable at once. Crypto-shredding turns an impossible deletion into a single operation."],
["p","And deletion generally is a workflow rather than a statement. Deleting a user means removing them from the primary store, the replicas, the caches, the search index, the backups and the analytics warehouse, and tracking that each of those completed. A deletion that leaves the search index intact is not slow. It is a compliance failure that happens to look finished."],
D("Encryption in transit and at rest",{say:"TLS on every hop including inside the datacenter; disks, databases and backups encrypted with KMS keys; per-tenant keys so an offboarded tenant's data becomes unrecoverable everywhere at once.",
use:["Always; per-tenant keys for regulated or large tenants"],
consider:["The network you don't control isn't only the public one","Crypto-shredding: destroy the key, the backups are gone too"]}),
D("PII, retention and deletion",{say:"We classify what we store, minimise it, set retention, and make deletion actually delete — across replicas, caches, search indexes, backups and the warehouse. A deletion that leaves the search index is a compliance failure.",
use:["Any personal data"],
consider:["Audit log of who accessed personal data, kept longer than the data","Deletion as an asynchronous workflow with a completion record"],
cases:["Delete user → 7 places; a job tracks each","Backups: crypto-shred or expire; document the window"]})
]},
{id:"tenants-abuse",title:"Tenant isolation and abuse",blocks:[
["p","Four thousand companies, one database. What actually keeps them apart?"],
["tbl",{cols:["Isolation model","Use when","Tradeoff"],rows:[["Shared tables + tenant_id in app","Many tiny tenants, low risk","Cheapest; one missed WHERE leaks"],["Shared tables + row-level security","Default for most SaaS","Filter enforced by the DB; DB-specific"],["Schema per tenant","Hundreds of mid-size tenants","Stronger; migrations × tenants"],["Database per tenant","Few large or regulated tenants","Strongest; cost scales per tenant"]]}],
["p","The naive answer is that every query includes WHERE tenant_id = ?. It works, and it goes on working until one query out of ten thousand does not — written by somebody new, on a Friday, in a reporting endpoint nobody reviewed closely."],
["p","What makes this different from an ordinary bug is the failure mode. It does not raise an error. It renders a page, quickly and correctly, with another company's documents on it."],
["p","So push the filter below the application. Row-level security lets the database apply the tenant predicate itself, from the connection's context, so ten thousand queries cannot forget it — because they are no longer the ones doing the remembering."],
["p","That is the same move as the unique constraint in Chapter 01, the conditional update in Chapter 04 and the fencing token in Chapter 05: put the invariant somewhere it cannot be bypassed by forgetting."],
["p","The largest and most regulated customers get their own database and their own key, because at that size the per-tenant cost is affordable and the isolation is absolute rather than merely careful."],
["p","And test it. An automated suite that attempts cross-tenant access on every deploy is worth more than any quantity of code review, because it fails loudly at the one thing that otherwise fails silently."],
D("Row-level security as the default",{say:"Every table has tenant_id; the database adds the tenant filter from the connection's context so ten thousand queries can't forget it; the biggest customers get their own database and key.",
use:["Most multi-tenant SaaS"],
avoid:["Relying on every developer remembering the WHERE clause"],
consider:["Test isolation with automated cross-tenant access attempts on every deploy","Tenant-scoped API keys and encryption keys complete the boundary"]}),
["p","Finally, abuse, which is best understood as a scale problem with an adversary attached."],
["p","The tools are the ones from Chapters 03 and 08 — rate limits, quotas, cost-based throttling — but the presence of intent changes how you tune them. An ordinary user does not request a fifty-thousand-page export every minute. An attacker does exactly that, because your most expensive endpoint is the cheapest denial of service available to them, and they did not have to write any code to find it."],
["p","And on login failures: identical wording and identical timing whether or not the account exists. A distinct no such user message is a free account-enumeration service that you built, host and pay for."],
D("Abuse as a scale problem with an adversary",{say:"Bots scraping, credential stuffing, account enumeration, a user requesting a 50,000-page export every minute — rate limits per user/IP/endpoint, cost-based throttling, identical timing and wording on auth failures, CAPTCHAs at the limit, and an audit log so we can see what was taken.",
use:["Every public surface"],
consider:["Same tools as Chapters 03 and 08, with intent added","Never a 'no such user' message"]}),
["t","Raise security when it changes the design: the tenant boundary decides the data model; revocation decides the token strategy; moderation adds a pipeline stage. 'And we'd encrypt everything' at the end signals it wasn't part of the design."]
]}
]};
