const D = (name, o) => ["dec", { name, ...o }];
export default {id:"realtime",num:"10",part:"IV · Exposing it",title:"Real-time delivery",example:"a live click dashboard",
tagline:"Getting new information to a browser that is already open. Who needs to send, how often, and what a long-lived connection costs you.",
terms:["WebSocket","Server-Sent Events","Long polling","Persistent connection","Presence","Connection draining"],
objectives:["Choose a real-time mechanism from who initiates and how often","Explain why a persistent connection makes the gateway stateful but not the application","Say what a deploy does to every open connection","Recognise when polling is the right answer"],
sections:[
{id:"realtime",title:"Choosing the real-time mechanism: WebSockets, SSE or long polling",blocks:[
["p","The shortener needs none of this, and saying so out loud is worth a sentence in an interview. But add one feature — a dashboard where the owner of a link watches clicks arrive on it — and you have to decide how the browser finds out that something happened."],
["p","The instinct is to reach for WebSockets, because WebSockets are what real-time means to most people. Hold that instinct for one question: who actually needs to send?"],
["p","On the click dashboard, the server sends and the browser listens. The browser\'s only outbound traffic is the occasional ordinary request — change the date range, export a CSV. Frequent traffic one way, rare traffic the other. That is not a bidirectional problem, and buying a bidirectional mechanism means paying for connection management you did not need."],
["p","Now compare a chat window. The user types, the other user types, both sides send constantly, and neither is primarily a listener. There the sockets earn their cost."],
["p","So the test is not how live it feels. It is: does the client send often? If no, Server-Sent Events, which is a single long-lived HTTP response with automatic reconnection built into every browser. If yes, WebSockets. And if updates arrive every thirty seconds or slower, neither — poll, and spend the complexity somewhere it will be noticed."],
D("WebSockets — a connection either side can send on at any time",{say:"Both sides send frequently here, so a single long-lived connection beats repeatedly asking. I accept that the servers holding those connections now have something in memory that matters, so I will add a way to find which server is holding a given user.",
use:["Chat and messaging.","Multiplayer games.","Shared documents with live cursors.","Showing who is online and who is typing.","Anything where the client sends many small messages, not just the server."],
avoid:["Cases where the server pushes and the client only occasionally replies. Server-Sent Events does that with far less machinery.","Updates arriving every thirty seconds or slower. Just ask repeatedly.","Anything you wanted cached by URL at the edge."],
consider:["It starts as a normal HTTP request and then asks to be upgraded into a persistent connection, which is why it works through most existing infrastructure.","The load balancer has to keep sending a given connection to the same server, because that server is the one holding it.","Every deploy drops every connection. Let servers finish gracefully and have clients reconnect after a randomised delay.","Send a heartbeat periodically. A connection that has silently died looks exactly like an idle one until you try to use it.","Cap how many connections one server will hold, or one machine will accept far more than it can serve."],
cases:["A client disconnects and reconnects, and resumes from the last message number it saw.","Messages arrive twice or out of order, so each carries a sequence number and the client discards duplicates.","One user is connected on three devices, so a message must reach every server holding one of them.","The server holding a connection crashes. Clients reconnect elsewhere, which is safe because nothing durable was stored only on that server.","One user floods the connection with messages, so each connection gets its own rate limit."],
fails:"A server dies and a hundred thousand clients try to reconnect in the same second, which knocks over whichever server they land on. Randomise the reconnect delay. Idle connections also leak memory slowly, and some corporate networks silently close long-lived connections."}),
D("Server-Sent Events (SSE) — the server pushes, the client listens",{say:"The server sends and the client mostly listens, so I would use Server-Sent Events. It is an ordinary HTTP response that stays open, which gives us push without any of the connection management a two-way protocol needs.",
use:["Streaming a response as it is generated, a few words at a time.","Progress on a long-running job.","Live dashboards, notifications, prices and scores."],
avoid:["Cases where the client also needs to send frequently. Use WebSockets.","Binary data, since this carries text only."],
consider:["It is just a long-lived HTTP response, so it passes through existing infrastructure without special handling.","Browsers reconnect automatically and tell the server the last message they received, so resuming is built in rather than something you write.","The client sends in the other direction using ordinary requests, which is usually all it needs."],
nuance:"A job service typically uses both: POST /jobs creates the work, and GET /jobs/123/events streams its progress. Two mechanisms, one feature."}),
D("Long polling — the client holds a request open until there is news",{say:"Where persistent connections are not available, the client makes a request that the server simply does not answer until it has something to say, and then immediately makes another one.",
use:["Old clients, or networks that block newer mechanisms.","A fallback behind whatever you actually wanted to use."],
avoid:["Anything new, where Server-Sent Events or WebSockets are available."],
consider:["Every update costs a complete HTTP request and response, so the overhead per message is high.","How long the server holds the request is a direct trade against how quickly the client notices new data.","The server is holding thousands of open requests anyway, so you get the same memory pressure as a persistent connection with fewer of the benefits."]}),
["h","Important correction: 'stateful servers'"],
["p","A persistent connection means a particular connection server owns that live socket. It does not make the whole application stateful. Keep durable state in shared storage and let connection servers remember only which clients are attached."],
["ex","Client\n  ↓ WebSocket\nConnection server        (knows: which clients are attached to me)\n  ↓\nPub/sub or message broker (routes: message for user U → whichever\n                           connection servers hold U's devices)\n  ↓\nApplication services + database (own: users, messages, history)"],
["ul",["Connection-aware routing (which server holds user U?)","Pub/sub across connection servers","Heartbeats and reconnection logic","Graceful draining during deploys","A cap on connections per server"]],
["t","WebSockets buy bidirectional low latency and cost you connection management. SSE buys most of the benefit for server-push cases with none of the management. Choose SSE unless the client genuinely talks back often."]
]}
]};
