const D = (name, o) => ["dec", { name, ...o }];
export default {id:"boundaries",num:"11",part:"IV · Exposing it",title:"Service boundaries",example:"a payments API",
tagline:"Where one service ends and the next begins, what a split actually costs, and deciding per call whether the caller waits.",
terms:["Monolith","Modular monolith","Microservice","API gateway","Service discovery","Stateless","Control plane","Data plane"],
objectives:["Name which of four benefits a service split buys before making it","List the four costs every split imposes","Recognise a distributed monolith","Choose synchronous or asynchronous from whether the answer changes what happens next"],
sections:[
{id:"boundaries",title:"Monolith, modular monolith or microservices",blocks:[
["p","Now the biggest question in the chapter, and the one most often answered by fashion rather than reasoning."],
["p","You have a payments API. Should payments be its own service?"],
["p","The answer that scores is not yes or no. It is being able to name what the split buys, because a split always costs the same four things, and the costs do not vary by company."],
["p","A function call becomes a network call with four outcomes. A transaction becomes a saga — a sequence of steps each of which can be undone, with states a user can see midway, covered in Chapter 16. One log becomes distributed tracing. One deploy becomes a coordination problem between teams."],
["p","Against that fixed price you need a specific benefit, and there are only four that count: independent deployment, independent scaling, fault isolation, or a compliance boundary. If you cannot say which of those four you are buying, you are paying the price for nothing."],
["p","Payments buys two of them outright. It carries a PCI compliance scope that is much cheaper to keep small, and its failures are ones you badly want isolated from catalogue browsing, which generates no revenue and should not be able to take payments down with it."],
["p","So payments splits. The catalogue does not, because nobody can name which of the four it would buy."],
["p","And the failure mode of getting this wrong has a name worth carrying: the distributed monolith. Services that must be deployed together, that call each other synchronously in long chains, that share one database underneath. You have paid every cost of splitting and kept every constraint of not splitting."],
D("Monolith — one deployable unit, one database",{say:"One application, one database, one transaction boundary. It is the fastest way to build and the right default until a specific boundary can justify becoming its own service.",
use:["Small teams, early products, and domains whose shape is not settled yet.","Workflows that need a single transaction across the whole domain."],
avoid:["Teams that block each other on every release.","Components with genuinely different scaling needs or regulatory requirements."],
consider:["Enforce module boundaries inside the codebase anyway. That gives you most of the organisational benefit and makes extracting a service later a realistic option rather than a rewrite."]}),
D("Microservices — separate deployables with separate data",{say:"Payments becomes its own service because it needs stricter consistency, a regulatory scope worth keeping small, and the ability to deploy without waiting for anyone. The catalogue stays where it is, because splitting it would buy nothing.",
use:["A boundary that buys one of exactly four things — independent deployment, independent scaling, isolation from another component's failures, or a smaller compliance scope — and you can say which.","Data owned by exactly one service, with a small and stable interface in front of it."],
avoid:["Domains whose boundaries are not yet clear. You will draw them wrong, and moving them afterwards means moving data across a network.","Workflows that needed one transaction across the split.","Small teams. The operational overhead is real and it is paid by the same people writing the features."],
consider:["A function call becomes a network call with four possible outcomes instead of two.","A transaction becomes a multi-step process with visible intermediate states, which Chapter 16 covers.","One log file becomes a tracing problem, which Chapter 19 covers.","You now need a gateway, a way for services to find each other, and something managing traffic between them."],
fails:"The distributed monolith: services that must be released together, that call each other in long synchronous chains, and that share one database. You have paid every cost of splitting and kept every restriction of not splitting.",
alt:"A monolith with enforced internal boundaries, then extracting one service at a time starting with the clearest.",
cases:["Two services constantly need each other's data inside one transaction. The boundary is in the wrong place.","Two services share a database. That is not two services; it is one, with a network in the middle."]}),
["t","Microservices trade a compile-time problem (a large codebase) for a runtime problem (a distributed system). The runtime problem is harder. Name the benefit before you split."]
]},
{id:"plumbing",title:"Gateway, discovery and statelessness",blocks:[
["p","Three pieces of infrastructure appear as soon as there is more than one service. Two are plumbing. One hides a decision that matters more than the other two combined."],
["p","The gateway is one front door: it terminates TLS, checks the token, applies rate limits and routes. Discovery means callers find healthy instances through a registry rather than a hard-coded address, so instances can come and go freely."],
["p","The one that matters is statelessness, and it is routinely misunderstood."],
["p","A stateless service is not one with no state. Payments obviously has state — that is the entire point of it. A stateless service is one where no request depends on which instance handled the previous request."],
["p","That single property is what makes almost everything else in this book affordable. Scaling becomes adding a box. Deploying becomes killing one. A crash costs one request rather than a user's session. Load balancing needs no memory of anything."],
["p","So where does the state go? Into the datastore, into the cache, or into a signed token the client carries. Never into the process."],
["p","There is one honest exception: a connection that is itself the state, like the WebSocket gateway from Chapter 10. There you have knowingly given the property up, and the price is that you now have to plan draining, reconnection and failover by hand."],
D("API gateway — one front door for many services",{say:"A single entry point handles encryption, authentication, rate limiting and routing once, rather than every service doing it slightly differently. Services trust the identity it passes through, and still check ownership themselves.",
use:["More than two or three services behind one public surface."],
avoid:["A single application, where the load balancer already does everything you need.","Letting business logic accumulate in it. It becomes a monolith that every team has to change and nobody owns."],
consider:["Everything goes through it, so it must be redundant and fast.","If its timeout is shorter than a backend's, callers see failures for work that actually completed. Make sure the numbers line up.","It is the natural place to assign the request id that Chapter 19 relies on."]}),
D("Service discovery — finding healthy instances without hardcoding",{say:"Callers look up healthy instances through a registry rather than a fixed address, so instances can be added, removed and replaced without anyone editing configuration.",
use:["Any system with more than a couple of services."],
consider:["The simple version is DNS with short cache times. The more capable version is a registry that services register themselves with. The most capable version puts a small proxy beside every service that also handles retries and encryption between them."]}),
D("Stateless services — any instance can serve any request",{say:"No request depends on which instance handled the previous one, because everything that must persist lives in the datastore, the cache, or a signed token the client carries. Scaling becomes adding a machine and deploying becomes removing one.",
use:["Every request-serving tier, as the default."],
avoid:["Only where the connection itself is the state, such as the servers holding WebSocket connections. There you have given the property up deliberately, and you now owe the system a plan for draining and reconnection."],
consider:["Never hold a half-finished payment in memory between requests. If the process dies, nobody knows it existed.","Pinning users to a particular server is a warning sign. Put the session in a shared store, or in a signed token, and the problem disappears."]})
]},
{id:"sync-async-planes",title:"Sync vs async per call, and the two planes",blocks:[
["p","Every call your payment service makes is one of two kinds: something it needs an answer to, or something it merely needs to have happened."],
["p","The fraud score is the first kind. The answer changes what you do next — approve or decline — so you wait for it, with a timeout, and you decide in advance what to do when fraud is unavailable. Approve small amounts and hold large ones, perhaps. The point is to have an answer, not to have the right one."],
["p","The receipt email is the second kind. Nothing about the payment depends on it. If you make the payment wait for the mail service, you have coupled the availability of taking money to the availability of sending email — a trade nobody would agree to if it were stated in those words, and one that is made accidentally all the time."],
["p","So the test is short. Does the answer change what happens next? Then wait. Otherwise publish an event and move on."],
["p","Getting this backwards is the most common architecture mistake there is, and it is expensive in both directions. Synchronous where it should be asynchronous ties your uptime to your least important dependency. Asynchronous where it should be synchronous means telling a user something succeeded when you do not actually know yet."],
D("Synchronous call — wait, because the answer changes what you do",{say:"Payments waits for the fraud score because the answer decides whether we approve or decline. It gets a hundred and fifty millisecond timeout, and a stated fallback if fraud is unavailable.",
use:["Anything where the caller needs the result to decide what happens next: a fraud check, a stock check, an authorisation."],
avoid:["Side effects the caller does not need confirmed — sending email, recording analytics, updating a search index."],
consider:["Waiting ties your availability and your speed to theirs. If they are down, you are down; if they are slow, you are slow.","Every waiting call needs a timeout and a decision about what to do when it expires. Chapter 18 covers how to choose both."]}),
D("Asynchronous event — publish it and move on",{say:"Once the charge succeeds we publish a payment-succeeded event. The ledger, the receipt service and analytics each react on their own, so payments never waits for any of them.",
use:["Cases where the caller only needs the work accepted, not completed.","One fact that several different systems need to react to."],
avoid:["Cases where the caller must know the outcome before it can respond to the user."],
consider:["Receipt sent is now something that will become true shortly rather than something that is true. Expose a status rather than implying it already happened.","Debugging now crosses a queue, so every message needs to carry the request id, as Chapter 17 covers."]}),
D("Control plane and data plane — separate changing config from using it",{say:"The data plane processes charges. The control plane changes settings and limits. The data plane keeps its last known configuration locally, so a control plane outage means we cannot change settings — not that we cannot take payments.",
use:["Any system whose configuration changes while it is running."],
avoid:["Reading configuration from the control plane on the path of every request. You have just made a rarely-used system a dependency of your most important one."],
consider:["The two have opposite requirements. The data plane must be fast and always available. The control plane changes rarely and can tolerate being down for minutes.","Every data plane machine should keep the last configuration that worked, and keep using it if it cannot fetch a newer one."]}),
["t","Sync where the answer changes the outcome; async where the caller only needs acceptance. Getting this backwards in either direction is the most common architecture mistake in interviews."]
]}
]};
