const D = (name, o) => ["dec", { name, ...o }];
export default {id:"patterns",num:"11",title:"Specialised design patterns",example:"a Snapchat-style media app",
tagline:"Feeds, chat, media, search, location, payments, counters, scheduling, ML — each pattern as a decision: use when, don't, alternative, tradeoff, failure.",
terms:["Hybrid fan-out","Presence","Presigned upload","Adaptive bitrate","Inverted index","Geohash","Ledger","HyperLogLog","Feature store","Canary"],
objectives:["See the problem shape inside a product prompt: contention, fan-out, large objects, ordering, search, async","Choose push, pull or hybrid fan-out and set the threshold","Design a media pipeline from presigned upload to CDN","Choose the index that turns a hard query into a prefix or key lookup","Draw an ML serving system as a dependency with a p99 and a fallback"],
sections:[
{id:"feeds",title:"Feeds: fan-out on write, on read, or hybrid",blocks:[
D("Fan-out on write (push)",{say:"For ordinary accounts, each post is pushed into every follower's cached timeline so a feed read is one fetch.",
use:["Most users follow a manageable number of accounts; reads must be fast"],
avoid:["Accounts with millions of followers — one post = millions of cache writes"],
consider:["Timeline cache bounded (~800 ids); rebuild from the graph on miss","Write amplification = follower count"]}),
D("Fan-out on read (pull)",{say:"For celebrities we pull their recent posts at read time and merge — one insert per post, no matter how many followers.",
use:["Huge follower counts","Strictly ranked feeds where you gather candidates anyway"],
avoid:["As the only strategy — reads touch hundreds of accounts every time"],
consider:["Read latency grows with follow count; repeated work per open"]}),
D("Hybrid fan-out",{say:"Push for accounts under 10k followers; pull the few celebrities a user follows at read time; merge, rank, paginate by cursor. Stories expire by TTL filtered at read time rather than deleted from every timeline.",
use:["Any real network with a long tail and a popular head"],
avoid:["Small networks — push alone is fine"],
consider:["Threshold is a tuning knob; a rising account crosses it mid-day","Author sees own post immediately: insert into own timeline synchronously (read-your-writes)"],
fails:"Timeline cache node dies → rebuild storm; rate-limit rebuilds. Threshold too high → hot writes; too low → slow reads.",
cases:["Celebrity posts during a live event → pull path + hot cache for their posts","Unfollow → lazily filter at read, don't purge timelines","Expired story still in cache → filter by TTL at read"]})
]},
{id:"chat",title:"Chat: transport, ordering, delivery, presence",blocks:[
D("Per-conversation sequence numbers",{say:"The server assigns a sequence per conversation when it accepts a message; clients render by sequence and detect gaps. Phone clocks are not trusted.",
use:["Ordering within a conversation"],
avoid:["Wall-clock timestamps (Ch. 05)","Global ordering — one sequencer for everything is a bottleneck nobody offers"],
consider:["A conversation is small, so one sequencer per conversation is fine"]}),
D("Store-then-push delivery",{say:"Message stored durably (wide-column, partitioned by conversation, sorted by sequence) before any ack; then pushed to every gateway holding the recipient's devices; offline → push notification wakes the app, which syncs from its last sequence.",
use:["Any messaging system"],
avoid:["Pushing before persisting — a gateway crash loses the message"],
consider:["Multiple devices each sync independently from their own last-seen sequence","Receipts (delivered/read) are small messages flowing back","Group of 50k → asynchronous fan-out by a worker, not on the sender's ack path"],
cases:["Recipient offline for a week → history is on the server, phone syncs","Same message sent twice (retry) → client message id dedup","Two devices, different last-seen → each fills its own gap"]}),
D("Presence and connection routing",{say:"A presence service maps user → gateway(s); gateways are stateful only about attached sockets; everything durable is behind them (see Ch. 01's correction).",
use:["Any WebSocket-based product"],
consider:["Heartbeats, last-seen with a grace period, pub/sub across gateways"]}),
D("Collaborative editing (OT / CRDT)",{say:"Two edits to one caption arrive concurrently; OT transforms each against the other, or a CRDT makes any merge order converge. I'd name the approach, not derive it.",
use:["Real-time shared documents"],
avoid:["Last-writer-wins on text"],
consider:["OT needs a central sequencer; CRDTs don't but carry metadata"]})
]},
{id:"media",title:"Media: upload, process, deliver",blocks:[
["tbl",{cols:["Choice","Use when","Tradeoff"],rows:[["Database storage","Tiny transactional files only","Convenient, expensive, unscalable"],["Object storage","Images, video, large files","Cheap and durable; metadata elsewhere"],["Presigned direct upload","Anything over a few MB","Zero bytes through app servers; validate after"],["Async transcoding","Multiple renditions needed","Fast upload; eventually available"],["CDN + adaptive bitrate","Global playback","Instant start on bad networks; purge/egress cost"]]}],
D("Presigned multipart upload",{say:"Client asks the API for a presigned multipart URL and uploads straight to object storage, resuming per part; the API never touches the bytes; a completion event enqueues processing.",
use:["Any upload over a few MB"],
avoid:["Proxying bytes through app servers"],
consider:["Validate type/size/malware after upload, before publish","Short-lived URLs scoped to one key"],
fails:"Unvalidated uploads published; leaked long-lived URL."}),
D("Async transcoding pipeline",{say:"An event triggers workers: scan, transcode 6 renditions, thumbnail, moderate — each output to a deterministic path so retries are idempotent; video is READY when the publisher flips the pointer.",
use:["Multiple formats/qualities; moderation"],
avoid:["Transcoding synchronously in the upload request"],
consider:["Eager for common renditions, lazy for rare ones","Publish = atomic pointer swap; never serve a half-set"]}),
["ex","50 M videos/day × 8 MB = 400 TB/day originals · ×1.6 renditions ≈ 640 TB/day\n×365 ≈ 230 PB/year before expiry. Expire at 30 days → ~20 PB live.\nEphemerality is a storage strategy."]
]},
{id:"search-location",title:"Search and location: turning hard queries into index lookups",blocks:[
D("Inverted index",{say:"Search runs on an inverted index fed by change events — term → document list, intersect, rank — partitioned by document with query fan-out. It's eventually consistent with the source by design; I'll say the delay.",
use:["Full text, ranking, facets, autocomplete"],
avoid:["As the source of truth","LIKE '%term%' on the database"],
consider:["Document partitioning (simple ingestion) vs term partitioning (fewer shards per query)","Autocomplete: trie/prefix list from the query log, in memory","Typos: edit distance or n-grams"],
fails:"Rename yourself, search immediately, not found for a few seconds — state it."}),
D("Geohash / quadtree",{say:"Nearby friends: geohash turns lat/long into a string where proximity is a shared prefix, so 'within 2 km' is a prefix match on a cell and its 8 neighbours — any key-value store can do it.",
use:["Proximity queries; driver matching; nearby search"],
avoid:["Lat/long range queries on a relational index — 2-D ranges don't index well"],
consider:["Cell size from query radius; always query neighbours (boundary problem)","Quadtree adapts to density: small cells downtown, one cell for the ocean","20M location writes/s → in-memory geo store partitioned by region; losing seconds on a crash is fine"],
cases:["Rider-driver match = nearby search + contention: conditional write on driver.status with a lease so an unresponsive driver is re-offered (Ch. 05)"]})
]},
{id:"payments-counters",title:"Payments and counters",blocks:[
D("Double-entry ledger",{say:"Every payment is two balanced immutable entries; balances are a materialised view rebuilt from entries; the ledger sums to zero at all times and reconciles nightly against the processor.",
use:["Anything moving money or credits"],
avoid:["A mutable balance column — can't be audited or reconciled"],
consider:["Never update or delete; correct with reversing entries","Idempotency on every mutating call (Ch. 02), sagas for multi-step (Ch. 05), strong consistency where money moves, eventual for receipts/analytics","Fraud: streaming classifier with a timeout and conservative fallback"],
fails:"Materialised balance drifts from entries → rebuild job + alert."}),
["tbl",{cols:["Counter","Use when","Tradeoff"],rows:[["Exact row increment","Billing, inventory","Correct; hottest row in the DB"],["Sharded / buffered counter","Displayed counts at high rate","Cheap; seconds stale"],["HyperLogLog","Distinct viewers","KBs of memory; ~1% error"],["Count-Min Sketch","Frequencies / top-K","Tiny; approximate"],["Stream processing","Seconds-fresh results","Approximate, complex"],["Batch","Exact, complete","Hours late"]]}],
D("Approximate counters",{say:"View counts are salted across shards and flushed periodically; distinct viewers via HyperLogLog. Users can't tell 1,203,417 from 1,190,000; billing gets exact counts from batch.",
use:["Anything a user glances at"],
avoid:["Anything a user is billed on"],
consider:["Lambda: stream now, batch corrects later. Kappa: replay the log instead of batch"]})
]},
{id:"scheduling-ml",title:"Scheduling and production ML",blocks:[
D("Distributed scheduler",{say:"Jobs with a due time in a time-indexed store; workers claim with a lease; leader election or partitioned ownership prevents double runs; expired lease → re-offered. Duplicate execution will still happen, so every job body is idempotent.",
use:["Story expiry, reminders, delayed jobs, cron at scale, retries with backoff"],
avoid:["A single cron box"],
consider:["Lease + fencing (Ch. 05)","Bounded attempts, then DLQ"]}),
D("Model serving as a dependency",{say:"The ranking model is a service with a p99, an error rate and a deploy process: request batching to keep the GPU busy, autoscaled on queue depth, a latency budget, and a fallback to the previous model or a heuristic.",
use:["Any online inference"],
avoid:["Treating 'the ML' as a magic box off the diagram"],
consider:["Offline training → artefact in a model registry (versioned, rollback target) → online inference","Batch predictions (friend suggestions nightly) vs real-time (moderation on arrival)","Feature store so training and serving compute features identically — training-serving skew is the #1 production ML bug","Shadow (score, don't act) → canary (1%) → promote","Drift and data-quality monitoring; hold out random traffic to break feedback loops","Vector DB for embeddings; RAG = search step before generation; semantic cache keyed on prompt embedding"],
fails:"Model works in eval, fails in prod (skew); slow model blocks every request (no timeout/fallback); ranking trained on its own clicks (feedback loop)."}),
["t","Every famous system is a few problem shapes in a costume. When you get a novel prompt, ask which shapes it contains — contention, fan-out, large object, ordering, search, async — before you draw anything."]
]}
]};
