const D = (name, o) => ["dec", { name, ...o }];
export default {id:"patterns",num:"11",title:"Specialised design patterns",example:"a Snapchat-style media app",
tagline:"Feeds, chat, media, search, location, payments, counters, scheduling, ML — each pattern as a decision: use when, don't, alternative, tradeoff, failure.",
terms:["Hybrid fan-out","Presence","Presigned upload","Adaptive bitrate","Inverted index","Geohash","Ledger","HyperLogLog","Feature store","Canary"],
objectives:["See the problem shape inside a product prompt: contention, fan-out, large objects, ordering, search, async","Choose push, pull or hybrid fan-out and set the threshold","Design a media pipeline from presigned upload to CDN","Choose the index that turns a hard query into a prefix or key lookup","Draw an ML serving system as a dependency with a p99 and a fallback"],
sections:[
{id:"feeds",title:"Feeds: fan-out on write, on read, or hybrid",blocks:[
["p","A user opens the app and sees stories from the people they follow. How did that list get there?"],
["p","There are only two moments when the work can be done: when the post is written, or when the feed is read. Everything else is a blend of the two."],
["p","Fan-out on write does it at post time. When you post, the system pushes the post id into the cached timeline of each of your followers. Reading a feed is then a single fetch of an already-assembled list, which is why good feeds feel instant."],
["p","The cost is write amplification. One post becomes one small cache write per follower. For an account with two hundred followers that is two hundred writes and completely fine."],
["p","Now an account with fifty million followers posts. That is fifty million cache writes for one action. During a live event, with several such accounts posting at once, the fan-out workers become the bottleneck for the entire product."],
["p","Fan-out on read does the opposite. Store the post once, and assemble each feed at read time by fetching recent posts from everyone the reader follows. Writes become trivial. Reads now touch hundreds of accounts, and you redo that work every single time the user pulls to refresh."],
["p","Neither is right on its own, because the distribution is the actual problem: almost every account is small and a handful are enormous. So do both. Push for ordinary accounts, pull for the few above a threshold, and merge the two lists when the feed is read."],
["p","The threshold is a tuning knob rather than a constant, and an account crosses it in the middle of the afternoon on the day it goes viral. Mentioning that case before you are asked about it is worth doing."],
["p","One detail that decides whether the product feels right: insert the author's own post into their own timeline synchronously. Everybody else can wait a few seconds. The person who just posted must see it immediately, or they will post again. That is read-your-writes from Chapter 04, applied to exactly one reader."],
D("Fan-out on write (push)",{say:"For ordinary accounts, each post is pushed into every follower's cached timeline so a feed read is one fetch.",
use:["Most users follow a manageable number of accounts; reads must be fast"],
avoid:["Accounts with millions of followers — one post = millions of cache writes"],
consider:["Timeline cache bounded (~800 ids); rebuild from the graph on miss","Write amplification = follower count"]}),
D("Fan-out on read (pull)",{say:"For celebrities we pull their recent posts at read time and merge — one insert per post, no matter how many followers.",
use:["Huge follower counts","Strictly ranked feeds where you gather candidates anyway"],
avoid:["As the only strategy — reads touch hundreds of accounts every time"],
consider:["Read latency grows with follow count; repeated work per open"]}),
D("Hybrid fan-out",{say:"Push for accounts under 10k followers; pull the few celebrities a user follows at read time; merge, rank, paginate by cursor. Stories expire by TTL filtered at read time rather than deleted from every timeline.",
use:["Any real network with a long tail and a popular head"],
avoid:["Small networks — push alone is fine"],
consider:["Threshold is a tuning knob; a rising account crosses it mid-day","Author sees own post immediately: insert into own timeline synchronously (read-your-writes)"],
fails:"Timeline cache node dies → rebuild storm; rate-limit rebuilds. Threshold too high → hot writes; too low → slow reads.",
cases:["Celebrity posts during a live event → pull path + hot cache for their posts","Unfollow → lazily filter at read, don't purge timelines","Expired story still in cache → filter by TTL at read"]})
]},
{id:"chat",title:"Chat: transport, ordering, delivery, presence",blocks:[
["p","Two messages arrive at the recipient's phone in the wrong order. Whose clock was wrong?"],
["p","Both, probably, and it does not matter — because you should never have been ordering by clocks in the first place. Phone clocks drift, users set them by hand, and a message composed offline on a plane can carry a timestamp from last week."],
["p","Ordering comes from the server. When it accepts a message it assigns the next sequence number for that conversation. Clients render by sequence, and because sequence numbers are contiguous, a client can notice a gap and ask for what it missed."],
["p","Per conversation, not globally — the same scoping decision as partitions in Chapter 07. A conversation is small, so one sequencer per conversation costs nothing, while a single global sequencer would be a bottleneck for the whole product and would buy an ordering guarantee nobody asked for."],
["p","Then delivery, where there is one rule: store durably before acknowledging, always. If you push to the recipient's connection first and persist afterwards, a gateway crash in the gap loses a message the sender was already told had been sent. Losing a message that displays as sent is the one unforgivable bug in a messenger."],
["p","Offline is not an exceptional case; it is most of the time. So a device syncs from its own last-seen sequence when it reconnects, and the push notification exists only to wake the app so it can do that. Three devices means three independent positions, each filling its own gap."],
["p","And a group of fifty thousand is a fan-out problem wearing a chat costume: fifty thousand deliveries for one message, performed by workers after the sender has been acknowledged, never on the sender's critical path."],
D("Per-conversation sequence numbers",{say:"The server assigns a sequence per conversation when it accepts a message; clients render by sequence and detect gaps. Phone clocks are not trusted.",
use:["Ordering within a conversation"],
avoid:["Wall-clock timestamps (Ch. 05)","Global ordering — one sequencer for everything is a bottleneck nobody offers"],
consider:["A conversation is small, so one sequencer per conversation is fine"]}),
D("Store-then-push delivery",{say:"Message stored durably (wide-column, partitioned by conversation, sorted by sequence) before any ack; then pushed to every gateway holding the recipient's devices; offline → push notification wakes the app, which syncs from its last sequence.",
use:["Any messaging system"],
avoid:["Pushing before persisting — a gateway crash loses the message"],
consider:["Multiple devices each sync independently from their own last-seen sequence","Receipts (delivered/read) are small messages flowing back","Group of 50k → asynchronous fan-out by a worker, not on the sender's ack path"],
cases:["Recipient offline for a week → history is on the server, phone syncs","Same message sent twice (retry) → client message id dedup","Two devices, different last-seen → each fills its own gap"]}),
D("Presence and connection routing",{say:"A presence service maps user → gateway(s); gateways are stateful only about attached sockets; everything durable is behind them (see Ch. 01's correction).",
use:["Any WebSocket-based product"],
consider:["Heartbeats, last-seen with a grace period, pub/sub across gateways"]}),
D("Collaborative editing (OT / CRDT)",{say:"Two edits to one caption arrive concurrently; OT transforms each against the other, or a CRDT makes any merge order converge. I'd name the approach, not derive it.",
use:["Real-time shared documents"],
avoid:["Last-writer-wins on text"],
consider:["OT needs a central sequencer; CRDTs don't but carry metadata"]})
]},
{id:"media",title:"Media: upload, process, deliver",blocks:[
["p","A video file is fifty megabytes. Where do the bytes actually go?"],
["p","Not through your API servers. If they do, then an application tier you sized for small JSON requests is now a file transfer service, and a single upload occupies a request handler for the entire length of a phone's slow upstream connection."],
["p","Instead the client asks your API for a presigned URL and uploads directly to object storage. Your servers never touch a byte — they grant permission and later hear about the outcome. Multipart upload means a dropped connection resumes from the failed part rather than from the beginning, which on a mobile network is the difference between a feature that works and one that does not."],
["p","Processing then happens asynchronously, through the pipeline from Chapter 07, and the video carries a status while it is under way."],
["p","The subtlety worth stating is how publishing works. Six renditions are produced independently and finish at different times. If the video becomes readable as each one lands, some viewers get a broken player. So write every output to a content-addressed path and publish by flipping a single pointer once the whole set exists. The video is either the old version or the new one, and never a mixture of both."],
["p","Ephemerality, incidentally, is a storage strategy and not merely a product feature. Fifty million videos a day at eight megabytes each is four hundred terabytes a day of originals. Retained forever that is unaffordable. Expired after thirty days it is a manageable steady state. The product decision and the storage bill turn out to be the same decision."],
["tbl",{cols:["Choice","Use when","Tradeoff"],rows:[["Database storage","Tiny transactional files only","Convenient, expensive, unscalable"],["Object storage","Images, video, large files","Cheap and durable; metadata elsewhere"],["Presigned direct upload","Anything over a few MB","Zero bytes through app servers; validate after"],["Async transcoding","Multiple renditions needed","Fast upload; eventually available"],["CDN + adaptive bitrate","Global playback","Instant start on bad networks; purge/egress cost"]]}],
D("Presigned multipart upload",{say:"Client asks the API for a presigned multipart URL and uploads straight to object storage, resuming per part; the API never touches the bytes; a completion event enqueues processing.",
use:["Any upload over a few MB"],
avoid:["Proxying bytes through app servers"],
consider:["Validate type/size/malware after upload, before publish","Short-lived URLs scoped to one key"],
fails:"Unvalidated uploads published; leaked long-lived URL."}),
D("Async transcoding pipeline",{say:"An event triggers workers: scan, transcode 6 renditions, thumbnail, moderate — each output to a deterministic path so retries are idempotent; video is READY when the publisher flips the pointer.",
use:["Multiple formats/qualities; moderation"],
avoid:["Transcoding synchronously in the upload request"],
consider:["Eager for common renditions, lazy for rare ones","Publish = atomic pointer swap; never serve a half-set"]}),
["ex","50 M videos/day × 8 MB = 400 TB/day originals · ×1.6 renditions ≈ 640 TB/day\n×365 ≈ 230 PB/year before expiry. Expire at 30 days → ~20 PB live.\nEphemerality is a storage strategy."]
]},
{id:"search-location",title:"Search and location: turning hard queries into index lookups",blocks:[
["p","Two problems that look entirely different and are the same idea underneath: turn a hard query into a cheap lookup by building the right index for it."],
["p","Full-text search first. You cannot answer which documents contain the word sunset by scanning documents, because that is linear work per query over your whole corpus. So invert the relationship: build a map from each term to the list of documents containing it. Now the query is a lookup and an intersection of a few lists."],
["p","That index is fed by change events, which means it is always slightly behind the source of truth. Say so explicitly: rename yourself and search immediately, and you may not find yourself for a few seconds. It is also never the source of truth — losing the index should mean rebuilding it, never losing data."],
["p","Location second. Find friends within two kilometres. Latitude and longitude are two dimensions, and an ordinary index sorts on one, so a range query on both is close to useless: it finds a band of the planet and then filters most of it away."],
["p","Geohashing solves this by folding two dimensions into one string in which nearby places share a leading prefix. Now nearby is a prefix match, and any key-value store on earth can do that quickly."],
["p","The trap is boundaries. Two points can be metres apart and still fall into different cells with different prefixes, so you always query the cell plus its eight neighbours. Anyone who forgets this ships an app where friends across the street are invisible and nobody can work out why."],
["p","And matching a rider to a driver is this plus Chapter 04's contention problem stacked together: find nearby drivers, then assign exactly one — with a conditional write, so a driver offered two rides can accept only one, and a lease, so an unresponsive driver's offer expires and moves on to the next."],
D("Inverted index",{say:"Search runs on an inverted index fed by change events — term → document list, intersect, rank — partitioned by document with query fan-out. It's eventually consistent with the source by design; I'll say the delay.",
use:["Full text, ranking, facets, autocomplete"],
avoid:["As the source of truth","LIKE '%term%' on the database"],
consider:["Document partitioning (simple ingestion) vs term partitioning (fewer shards per query)","Autocomplete: trie/prefix list from the query log, in memory","Typos: edit distance or n-grams"],
fails:"Rename yourself, search immediately, not found for a few seconds — state it."}),
D("Geohash / quadtree",{say:"Nearby friends: geohash turns lat/long into a string where proximity is a shared prefix, so 'within 2 km' is a prefix match on a cell and its 8 neighbours — any key-value store can do it.",
use:["Proximity queries; driver matching; nearby search"],
avoid:["Lat/long range queries on a relational index — 2-D ranges don't index well"],
consider:["Cell size from query radius; always query neighbours (boundary problem)","Quadtree adapts to density: small cells downtown, one cell for the ocean","20M location writes/s → in-memory geo store partitioned by region; losing seconds on a crash is fine"],
cases:["Rider-driver match = nearby search + contention: conditional write on driver.status with a lease so an unresponsive driver is re-offered (Ch. 05)"]})
]},
{id:"payments-counters",title:"Payments and counters",blocks:[
["p","Money gets its own data model, and the rule is short: never store a balance you can edit."],
["p","A mutable balance column cannot be audited. When it is wrong — and one day it will be — there is no way to discover when it became wrong, or why, or what it should have been."],
["p","So record the movements instead, as immutable paired entries that always sum to zero, and derive the balance from them. Corrections are new reversing entries, never edits to old ones. The balance is now reproducible from history, and reconciliation against the payment processor becomes possible because there is finally a history to reconcile against."],
D("Double-entry ledger",{say:"Every payment is two balanced immutable entries; balances are a materialised view rebuilt from entries; the ledger sums to zero at all times and reconciles nightly against the processor.",
use:["Anything moving money or credits"],
avoid:["A mutable balance column — can't be audited or reconciled"],
consider:["Never update or delete; correct with reversing entries","Idempotency on every mutating call (Ch. 02), sagas for multi-step (Ch. 05), strong consistency where money moves, eventual for receipts/analytics","Fraud: streaming classifier with a timeout and conservative fallback"],
fails:"Materialised balance drifts from entries → rebuild job + alert."}),
["p","Counters are the same question with the opposite answer, and the contrast is the lesson."],
["p","A view counter implemented as an incrementing database row is the hottest row in the system: every view is a write to one place, and a viral video turns it into a hot partition of exactly one. But nobody can tell 1,203,417 from 1,190,000, and no decision anybody makes depends on the difference."],
["p","So spread the counter across shards, buffer in memory, flush periodically, and accept a number that is a few seconds stale and slightly approximate. For distinct viewers, HyperLogLog gives a count within about one percent using kilobytes, instead of storing a set containing every viewer id that ever watched."],
["p","The rule separating the two cases is worth memorising: exact where somebody is billed, approximate where somebody merely glances. Applying the ledger's rigour to a view counter melts your database. Applying the counter's looseness to money is fraud."],
["tbl",{cols:["Counter","Use when","Tradeoff"],rows:[["Exact row increment","Billing, inventory","Correct; hottest row in the DB"],["Sharded / buffered counter","Displayed counts at high rate","Cheap; seconds stale"],["HyperLogLog","Distinct viewers","KBs of memory; ~1% error"],["Count-Min Sketch","Frequencies / top-K","Tiny; approximate"],["Stream processing","Seconds-fresh results","Approximate, complex"],["Batch","Exact, complete","Hours late"]]}],
D("Approximate counters",{say:"View counts are salted across shards and flushed periodically; distinct viewers via HyperLogLog. Users can't tell 1,203,417 from 1,190,000; billing gets exact counts from batch.",
use:["Anything a user glances at"],
avoid:["Anything a user is billed on"],
consider:["Lambda: stream now, batch corrects later. Kappa: replay the log instead of batch"]})
]},
{id:"scheduling-ml",title:"Scheduling and production ML",blocks:[
["p","Two more, briefly, because both come up constantly and both are usually hand-waved."],
["p","Scheduling first. Stories expire after twenty-four hours, and something has to make that happen for millions of them. Not a cron box — that is one machine, one failure, and no safe way to run a second one alongside it."],
["p","Store jobs in a time-indexed table, have workers claim due jobs with a lease, and use the fencing tokens from Chapter 05 so that a paused worker cannot act on a claim that has already expired. Then, because duplicates remain possible no matter what you do, make every job body idempotent. You will notice that is the same conclusion as Chapter 07, reached by a different road."],
D("Distributed scheduler",{say:"Jobs with a due time in a time-indexed store; workers claim with a lease; leader election or partitioned ownership prevents double runs; expired lease → re-offered. Duplicate execution will still happen, so every job body is idempotent.",
use:["Story expiry, reminders, delayed jobs, cron at scale, retries with backoff"],
avoid:["A single cron box"],
consider:["Lease + fencing (Ch. 05)","Bounded attempts, then DLQ"]}),
["p","And machine learning, which candidates tend to draw as a box labelled ML and then walk past."],
["p","Treat it as a dependency like any other: it has a p99, an error rate, a deployment process and a fallback. If the ranking model is slow you serve the previous model or a simple heuristic. You do not block the feed on it, any more than you would block checkout on recommendations."],
["p","The failure mode worth knowing is training-serving skew. The model was trained on features computed one way — offline, in a batch job, in one language. At serving time those same features are computed by different code, under a latency budget, possibly in a different language. When the two computations disagree even slightly, the model evaluates beautifully and performs poorly in production, and nothing anywhere raises an error."],
["p","A feature store exists to make both paths use one definition, which is why it appears in every serious production ML system and in almost no tutorials."],
["p","And roll models out the way you roll out code: shadow first, scoring without acting, then a small canary, then promote — keeping the previous version as a rollback target, because you will need it."],
D("Model serving as a dependency",{say:"The ranking model is a service with a p99, an error rate and a deploy process: request batching to keep the GPU busy, autoscaled on queue depth, a latency budget, and a fallback to the previous model or a heuristic.",
use:["Any online inference"],
avoid:["Treating 'the ML' as a magic box off the diagram"],
consider:["Offline training → artefact in a model registry (versioned, rollback target) → online inference","Batch predictions (friend suggestions nightly) vs real-time (moderation on arrival)","Feature store so training and serving compute features identically — training-serving skew is the #1 production ML bug","Shadow (score, don't act) → canary (1%) → promote","Drift and data-quality monitoring; hold out random traffic to break feedback loops","Vector DB for embeddings; RAG = search step before generation; semantic cache keyed on prompt embedding"],
fails:"Model works in eval, fails in prod (skew); slow model blocks every request (no timeout/fallback); ranking trained on its own clicks (feedback loop)."}),
["t","Every famous system is a few problem shapes in a costume. When you get a novel prompt, ask which shapes it contains — contention, fan-out, large object, ordering, search, async — before you draw anything."]
]}
]};
