export default {id:"framework",num:"13",title:"The interview framework",example:"designing Twitter in 40 minutes",
tagline:"The same seven steps every time, so the structure is automatic and your attention goes to the problem — worked through a 40-minute Twitter design.",
terms:["Functional requirements","Non-functional requirements","Access patterns","Source of truth","Critical flow","Deep dive","Bottleneck"],
objectives:["Run the seven-step framework without notes and keep it to time","Turn a prompt into three functional and three non-functional requirements in under five minutes","Define the API and data model before drawing boxes","Choose two or three deep dives that the requirements actually justify","Close with bottlenecks and tradeoffs rather than trailing off"],
sections:[
{id:"seven-steps",title:"The seven steps and the clock",blocks:[
["p","Forty-five minutes, one prompt, a whiteboard or a shared document. The framework is not a script to recite; it is a way of making sure that structure costs you no attention, so all of it goes to the problem. Interviewers see hundreds of candidates and can tell within five minutes whether you have a process."],
["ex","The shape of 40 minutes\n 0–5    Clarify requirements; state assumptions\n 5–10   Estimate scale; define API and data model\n10–20   High-level design — the diagram\n20–35   Deep dives on two or three hard parts\n35–40   Bottlenecks, tradeoffs, what you'd do at 10×"],
["p","The running example is Twitter — post, follow, timeline, search — because every interviewer knows it and because it exercises fan-out, caching, partitioning and ranking in one prompt."],
["t","Spending fifteen minutes on requirements leaves nothing for the deep dive that actually scores. Spending two minutes leaves you designing the wrong product. Five is the number; practise until it feels natural."]
]},
{id:"clarify",title:"Step 1 — Clarify requirements",blocks:[
["p","Ask questions whose answers would change the design, then stop. Who are the users? Which two or three features are core? What is explicitly out of scope? How many users and how many requests? Read-heavy or write-heavy? What consistency does the critical operation need? What latency and availability are expected?"],
["ex","Twitter, clarified\nFunctional:      post a tweet; follow a user; view a home timeline\n                 (newest first, from followed accounts)\nOut of scope:    search, DMs, ads, trending, media (say so)\nNon-functional:  timeline load < 200 ms p99; 99.9% available;\n                 eventual consistency acceptable — a tweet may\n                 appear a few seconds late\nScale:           300 M DAU, 500 M tweets/day, read-heavy (100:1)"],
["h","Functional versus non-functional"],
["p","Functional requirements say what the system does: post, follow, read timeline. Non-functional requirements say how well: latency, availability, consistency, durability, cost. The non-functional ones drive the architecture — a 200 ms timeline forces a pre-computed feed; eventual consistency permits asynchronous fan-out. State three of each, and let the interviewer adjust them."],
["t","Asking every question in the book reads as stalling. Asking none reads as arrogance. Ask four or five that matter, state assumptions for the rest, and move."]
]},
{id:"estimate-api-model",title:"Steps 2 and 3 — Scale, API and data model",blocks:[
["h","Estimate"],
["p","Two minutes, rounded, with a consequence per number (Chapter 12). 500 M tweets a day is about 6,000 writes per second, 30,000 at peak — fine for a partitioned store. Timeline reads at 100 : 1 are 600,000 a second, so the timeline must be served from a cache, not assembled from the database per request."],
["h","API"],
["ex","POST /v1/tweets                    { text }            → { tweet_id }\nPOST /v1/users/{id}/follow\nGET  /v1/timeline?cursor=…&limit=20 → { tweets[], next_cursor }"],
["h","Data model and access patterns"],
["p","Entities: users, tweets, follows. Access patterns: write a tweet (by user); read a user's tweets newest first; read who a user follows and who follows them; read a home timeline. Indexes follow the access patterns: tweets by (user_id, created_at desc); follows by follower and by followee. The source of truth for tweets is a partitioned database keyed by tweet id; the home timeline is a derived, cached list of tweet ids per user — not a source of truth, rebuildable at any time."],
["t","Defining the API before the diagram forces you to decide what the system actually does and what it stores. Drawing first and defining later produces boxes with no queries and queries with no indexes."]
]},
{id:"high-level",title:"Step 4 — The high-level design",blocks:[
["p","Start from the standard path — clients, load balancer, stateless services, cache, database — and add components only when a requirement you have already stated demands one. Say the requirement as you draw the box."],
["ex","Twitter, high level\nClients → CDN → LB → API gateway\n  ├─ Tweet service   → tweets DB (partitioned by tweet_id)\n  │                   → publishes TweetCreated  (\"fan-out is async\n  │                     because eventual consistency is acceptable\")\n  ├─ Fan-out workers → timeline cache (Redis, list of ids per user)\n  │                     (\"pre-computed because 200 ms p99 at 600k rps\")\n  ├─ Timeline service → timeline cache → tweets DB / tweet cache\n  │                     (hydrate ids to tweets)\n  └─ Social graph service → follows DB (by follower, by followee)"],
["p","Walk the two critical flows across the diagram. Posting: API validates, writes the tweet, emits an event; workers read the author's followers and push the id into each follower's cached timeline. Reading: timeline service fetches the id list from cache, hydrates the first page from the tweet cache, falls back to the database on a miss, returns a cursor."],
["t","A diagram with twelve boxes and no requirement attached to nine of them is a worse answer than a diagram with six boxes each justified. Add the search index, the notification service or the ranking tier only when the interviewer asks or the requirements include them."]
]},
{id:"deep-dives",title:"Steps 5 and 6 — Critical flows and deep dives",blocks:[
["p","The interviewer will usually pick one or two deep dives; you should propose the others. Choose the parts where the design could genuinely fail — and where you can name the alternative you rejected."],
["h","Twitter's natural deep dives"],
["ul",["The celebrity problem — fan-out on write for an account with 50 M followers means 50 M cache writes per tweet. Hybrid: push for ordinary accounts, pull for accounts above a threshold, merge at read. Name the threshold and the read-time cost (Chapter 11).","Timeline cache sizing and eviction — 300 M users × 800 ids × 8 bytes ≈ 2 TB; keep active users only, rebuild inactive ones on demand from the follow graph.","Tweet storage partitioning — by tweet id (even distribution, timelines hydrate by id anyway) versus by user id (a user's tweets colocated; celebrity hotspots). Say which and why (Chapter 04).","Consistency — a follower may see a tweet a few seconds late; the author must see their own tweet immediately (read-your-writes: insert into the author's own timeline synchronously).","Failure — fan-out workers die mid-batch: the event is redelivered, and pushing an id twice is idempotent because the timeline is a set-like structure. The cache cluster loses a node: timelines on it rebuild lazily from the database (Chapters 06–08)."]],
["t","Going deep means reaching the alternative: 'I chose X; the alternative was Y; Y is better when Z, which isn't our case.' Going wide means listing five more components. Interviewers score depth."]
]},
{id:"bottlenecks",title:"Step 7 — Bottlenecks and tradeoffs",blocks:[
["p","Use the last five minutes to attack your own design before the interviewer does. Walk the diagram and name the failure of each box; name what breaks first at ten times the load; name what you would change and what you deliberately left out."],
["ul",["Hotspots — celebrity tweets, a viral tweet's id hydrated a million times a second (cache it at the timeline service).","Single points of failure — the fan-out queue, the timeline cache cluster, the social graph store.","Replication lag — a follow that has not yet replicated means a missed tweet in the next fan-out; acceptable, self-healing.","Queue backlog — fan-out lag during a global event; tweets appear late; alert on lag (Chapter 07).","Cache failure — a cold timeline cache after an outage; rebuild on demand with rate limiting to protect the database (Chapter 06).","Database overload — hydration misses under a cold cache; shed or serve partial timelines.","Regional outage — timelines are per-user and can be rebuilt in another region; the follow graph must be replicated across regions.","Cost — 2 TB of Redis and a fan-out fleet are the expensive parts; the tradeoff is against read latency."]],
["h","Recap"],
["p","End with three sentences: what you built, the two decisions that shaped it, and what you would do next. 'A read-optimised system with pre-computed timelines and hybrid fan-out; eventual consistency for followers and read-your-writes for authors; next I'd add ranking on top of the merged candidate set and a search index fed from the same tweet events.'"],
["t","Silence while you think reads as being stuck. Narrating a wrong turn and correcting it reads as engineering. Talk the whole time, including while you draw."]
]},
{id:"product-shaped",title:"Product-shaped questions — a worked Meetup Service",blocks:[
["p","Not every prompt is 'design Twitter'. Some companies ask you to design a small internal product — a few thousand users, no scale problem — and want to see data modelling, an algorithm, an API and an interface. The infrastructure toolkit from Chapters 03–08 is nearly irrelevant, and reaching for Kafka is a red flag. The framework still applies; the time allocation changes."],
["ex","Prompt: Develop a system for a company's employees to make friends\nwith other employees. Users 'match' with someone new every few weeks.\nFocus areas given: database design, matching algorithm, APIs,\nfrontend design; gloss over scalability."],
["ex","40 minutes for a product-shaped question\n 0–5    Scope: who opts in, how often, 1:1 or small groups,\n        what 'good match' means, what must never happen\n 5–15   Data model — entities, the repeat-prevention invariant\n15–25   Algorithm — scoring, pairing, the schedule, edge cases\n25–32   API — the handful of REST endpoints\n32–38   Interface — the three screens\n38–40   One-minute scalability and failure nod"],
["h","1. Scope it"],
["p","Users: employees who opt in. Core flows: set up a profile and preferences; get matched on a cadence; see the match and mark it met or skipped. Out of scope: chat (use the company's existing tool), event booking, recommendations beyond the match. Invariants: nobody is matched with the same person twice within a long window; nobody who opted out is matched; a round produces at most one match per person. Scale: ten thousand employees, one round every two weeks — trivial, and say so."],
["h","2. Data model"],
["ex","users        (id, name, email, office, team, timezone, joined_at)\nprofiles     (user_id, bio, interests[], seniority, meeting_pref,\n              opted_in bool, paused_until)\nrounds       (id, scheduled_at, status: planned|matched|closed)\nmatches      (id, round_id, user_a, user_b, status:\n              proposed|met|skipped, feedback_a, feedback_b,\n              UNIQUE (round_id, user_a), UNIQUE (round_id, user_b))\nmatch_history(user_lo, user_hi, last_round_id,\n              PRIMARY KEY (user_lo, user_hi))"],
["p","What defines a user: identity comes from the company directory (SSO), so users are provisioned rather than registered; the profile is what the user adds. Previous matches: the pair is stored with the smaller id first so (A, B) and (B, A) collapse to one row and a lookup is one indexed read — this is how you answer 'how do you avoid repeats' with a table rather than a scan. Data for a good match: interests, office and timezone (can they actually meet), team (cross-team is usually the point), seniority (optional balancing), and feedback from past matches, which is the signal that improves the algorithm over time."],
["h","3. Algorithm"],
["p","Every two weeks, a scheduled job (Chapter 11, scheduling) runs the round. Candidates are users with opted_in true and paused_until in the past. Score every eligible pair: positive weight for shared interests and compatible timezone, positive for different team, negative for same manager, hard exclusion for anyone in match_history within the last N rounds. Then pair: a greedy pass over pairs sorted by score is easy to explain and good enough; a maximum-weight matching (Blossom) is optimal and worth naming as the upgrade. Odd count: one person gets a group of three or is prioritised next round. Someone who was skipped last round gets a boost so nobody is left out repeatedly."],
["t","Greedy pairing is O(n² log n) and fine for ten thousand users; it can leave the last few people with poor matches. Optimal matching fixes that at the cost of an algorithm nobody wants to implement on a whiteboard. Name both, pick greedy, say when you'd upgrade."],
["h","4. API"],
["ex","GET    /v1/me/profile                 PUT /v1/me/profile\nPOST   /v1/me/opt-in                  POST /v1/me/pause { until }\nGET    /v1/me/matches?cursor=…        current and past matches\nPOST   /v1/matches/{id}/status        { status: met|skipped, feedback }\nPOST   /v1/rounds                     (admin) schedule a round\nGET    /v1/rounds/{id}                (admin) status and stats\n\nAuth: company SSO; users read only their own matches."],
["h","5. Interface"],
["p","Three screens. Onboarding: opt in, pick interests from a fixed list plus free text, meeting preference (coffee, lunch, video), pause toggle. Your match: who, why you were matched (the shared interests — this is the feature that makes people actually meet), a one-tap 'suggest a time' that opens the calendar, and Met / Skip buttons. History: past matches with a one-line note each. Nothing else — the product is the match card."],
["h","6. The one-minute scalability nod"],
["p","'At ten thousand users the round is a single job on one database. If this served a million users across companies, I'd partition by company — matching never crosses that boundary — and run rounds per company in parallel. The job is idempotent on round_id, so a crash mid-round is safe to rerun.' Then stop."],
["t","Product-shaped questions score on judgement: the right tables, the invariant enforced by a constraint, a sensible algorithm with a named upgrade, and an interface that shows you thought about why people would use it. Infrastructure vocabulary earns nothing here and costs time."]
]}
]};
