const D = (name, o) => ["dec", { name, ...o }];
export default {id:"partitioning",num:"15",part:"V · Growing",title:"Partitioning and sharding",example:"an e-commerce order system",
tagline:"Splitting the data itself across machines. Choosing the key, and knowing which queries you have just made expensive.",
terms:["Shard","Partition key","Hash partitioning","Range partitioning","Scatter-gather","Hot partition","Rebalancing","Secondary index"],
objectives:["Say when to shard, and why not before","Choose a partition key from the dominant access pattern","Name the query the key just made expensive","Explain why a monotonically increasing key concentrates all writes"],
sections:[
{id:"sharding",title:"Partitioning: whether, how and by what key",blocks:[
["p","Everything so far scales reads. Eventually the writes stop fitting on one machine, and you have to divide the data itself."],
["p","The moment to do that is not when the disk is full. It is when you can name two things: the axis the data grows along, and the query that dominates. If you cannot name both, sharding now means committing to a key you do not yet understand — and the key is very close to permanent."],
["p","For orders, ninety-five percent of queries are scoped to a single customer: their history, their open orders, their returns. Partition by customer_id and almost every query lands on exactly one shard."],
["p","Now say the cost out loud, because there always is one, and being able to state it is what separates a decision from a guess."],
["p","All orders for product P no longer has a home. It has to ask every shard and merge the answers, and it gets slower each time you add a shard. If that query matters to the business, you build a second index partitioned by product instead — and that index is maintained asynchronously, so it lags behind the truth."],
["p","And the wholesale customer with a million orders is now one shard's problem, alone. That is a hot partition, and it is election night again in a different costume: distributing keys evenly is not the same as distributing load evenly."],
["p","The choice between hashing and ranging is the same trade seen from the other side. Hash partitioning spreads writes beautifully and destroys range queries — orders from last Tuesday becomes a question you must ask everybody. Range partitioning keeps ranges local and manufactures hot spots, because if you partition by time then every new write goes to whichever shard is newest."],
["p","That last one is the most common sharding mistake there is, and it is worth stating as a rule: a monotonically increasing partition key guarantees that one partition receives all of the writes. Time is monotonically increasing. So is an auto-increment id."],
["p","Resharding afterwards is the thing to avoid. It means dual-writing, backfilling, verifying and cutting over on a live system, for weeks. Which is the real argument for waiting until you can name the axis — and then not waiting a great deal longer."],
D("Sharding — splitting the data across machines",{say:"Split by customer, because ninety-five percent of queries are about one customer. Stock stays on its own smaller store. Reporting runs against copies. The wholesale buyer with a million orders is the risk, and I would split them by customer and year if needed.",
use:["When the data or the write rate genuinely exceeds one machine — and you can name the axis it grows along and the query that dominates."],
avoid:["Before you can name those two things, because the key you choose is close to permanent.","When queries would constantly need to span several machines. Fix the boundary instead."],
consider:["Splitting by a hash of the key spreads writes evenly and turns range queries into questions you must ask every machine.","Splitting by ranges keeps range queries local and creates hot spots, because a steadily increasing key such as a date sends every new write to the same machine.","A lookup service that simply records where everything lives is completely flexible, at the cost of an extra hop and something else that must always be available.","Use consistent hashing or fixed virtual buckets so that adding machines moves a proportional amount rather than everything."],
fails:"One machine becomes hot because of one customer or one date. Or the key turns out to be wrong, and fixing it means writing to both layouts, copying history, verifying, and switching over — weeks of work on a live system.",
alt:"A bigger machine with read copies. Archiving old data. Or moving only the one table that is actually too big.",
cases:["A query that does not include the key has to ask every machine and combine the answers.","All orders for one product, when split by customer, needs a second index organised by product — and that index is updated asynchronously, so it lags.","Adding machines should move whole buckets rather than individual rows."]}),
["ex","Weak:   \"We'll shard the database.\"\nStrong: \"Partition by user_id because most requests are scoped to one\n        user. Cost: global search and celebrity users create cross-\n        shard queries and hotspots — search gets its own index and\n        celebrities get a cache.\""],
["t","Sharding early wastes effort and freezes a key you don't understand; sharding late means migrating under load. The moment is when you can name the axis and the dominant query — usually well before the single node's limit."]
]}
]};
