export default {id:"cases",num:"16",title:"Worked cases",example:"a URL shortener, end to end",
tagline:"Full case studies in the one structure every case should follow: prompt, questions, requirements, estimates, API, data, basic design, bottlenecks, alternatives, tradeoffs, failure cases, security, final design, weak answers, follow-ups.",
terms:["Clarifying questions","Functional / non-functional","Access patterns","Basic design","Bottleneck","Alternative design","Weak answer","Follow-up"],
objectives:["Run a full case in the 16-part structure without skipping steps","Produce a basic design first and only then scale it, naming the bottleneck that forces each change","State component-by-component tradeoffs and the alternative you rejected","Recognise the weak answers interviewers hear most and avoid them"],
sections:[
{id:"structure",title:"The structure every case follows",blocks:[
["ex","1  Ambiguous original prompt\n2  Questions you should ask\n3  Functional requirements\n4  Non-functional requirements\n5  Back-of-the-envelope estimates\n6  API design\n7  Data model and access patterns\n8  Basic working design\n9  Scaling bottlenecks\n10 Alternative designs\n11 Component-by-component tradeoffs\n12 Concurrency and failure cases\n13 Security and abuse\n14 Interview-quality final design\n15 Common weak answers\n16 Follow-up questions"],
["p","The order matters. Requirements before estimates, estimates before API, API before data, data before boxes. A basic design that works at small scale comes before any scaling — the interviewer wants to see you add each component because a named bottleneck forced it. The same sixteen headings apply to Ticketmaster, WhatsApp and a payment platform; the practice formats in Case studies grade against the same skeleton."]
]},
{id:"shortener-scope",title:"URL shortener · 1–5 · prompt, questions, requirements, estimates",blocks:[
["h","1 · Prompt"],
["ex","\"Design a URL shortener like bit.ly.\""],
["h","2 · Questions to ask (and why each changes the design)"],
["ul",["Custom aliases allowed? → uniqueness conflicts become user-visible; need a reserve step.","Do links expire? → TTL column, a sweeper, and cache TTLs that respect it.","Do we need click analytics? → decides 301 (cacheable, no counts) vs 302 (every hit reaches us) and adds a write per read.","Scale — links created per day, redirects per day? → whether one database is enough.","Can a link be edited or deleted after creation? → cache invalidation on the redirect path.","Global users? → CDN/edge caching for redirects.","Is the short code length fixed? → key space and generation strategy."]],
["h","3 · Functional requirements"],
["ul",["Given a long URL, return a short code (optionally a custom alias).","Redirect a short code to its long URL.","Links may have an expiry.","Basic click count per link (assume yes — it makes the design more interesting)."]],
["h","4 · Non-functional requirements"],
["ul",["Redirect latency p99 < 50 ms at the edge — it sits in front of someone else's page load.","Redirects 99.99% available; creation may be less (99.9%).","A code, once issued, must never point to a different URL (durability + immutability).","Reads vastly outnumber writes; eventual consistency for click counts is fine."]],
["h","5 · Estimates"],
["ex","Writes:   10 M links/day ÷ 100k s          ≈ 100/s (500/s peak)\nReads:    100:1 ratio → 1 B redirects/day  ≈ 10k/s (50k/s peak)\nStorage:  10 M × 500 B/day = 5 GB/day → ~2 TB/year, ~10 TB over 5 y\nKey space: 7 chars of [a–zA–Z0–9] = 62^7 ≈ 3.5 T codes — plenty\nCache:    hot 20% of a day's links ≈ 2 M entries × 500 B ≈ 1 GB\nSo: writes fit one leader for years; reads must come from cache/edge;\nstorage is small; the key generator is the only interesting write path."]
]},
{id:"shortener-api-data",title:"URL shortener · 6–8 · API, data model, basic design",blocks:[
["h","6 · API"],
["ex","POST /v1/links            { url, alias?, expires_at? }  → 201 { code, short_url }\n                          409 if alias taken · 400 if url invalid\nGET  /{code}              → 302 Location: <url>   (302 so clicks reach us)\n                          404 unknown · 410 expired\nGET  /v1/links/{code}     → { url, created_at, expires_at, clicks }\nDELETE /v1/links/{code}   (owner only)\nAuth: API key for creation; redirects are public."],
["h","7 · Data model and access patterns"],
["ex","links   (code PK, url, owner_id, created_at, expires_at)\nclicks  (code, day, count)      — or a counter in the cache flushed hourly\n\nAccess patterns:\n  redirect:  code → url            (99% of traffic; point lookup)\n  create:    insert if code absent (unique constraint on code)\n  stats:     code → counts by day"],
["p","Point lookups by code and inserts with a uniqueness check: a key-value shape. A relational database serves it fine at this size; a key-value store serves it fine at any size. The choice is not important; the index on code is."],
["h","8 · Basic working design"],
["ex","Client → LB → API servers (stateless) → Postgres (links)\n\nCreate: generate code, INSERT … ON CONFLICT DO NOTHING; retry on collision.\nRedirect: SELECT url FROM links WHERE code = ?; 302.\nThis works to ~5k redirects/s on one database. Say so, then scale it."]
]},
{id:"shortener-scale",title:"URL shortener · 9–11 · bottlenecks, alternatives, tradeoffs",blocks:[
["h","9 · Scaling bottlenecks, in the order they appear"],
["ul",["Redirect reads at 50k/s → add a cache (Redis, cache-aside, TTL = min(1 day, expires_at)). Hit rate > 95% for a power-law link distribution. DB now sees ~2k/s.","Global latency → cache redirects at the CDN edge as well (302 with a short Cache-Control, or 301 if analytics are dropped). Most redirects never reach a region.","Click counting at 50k writes/s → never increment a DB row per hit. Increment a sharded counter in the cache and flush aggregates every minute; or emit a click event to a log and aggregate in a stream job.","Code generation contention → see alternatives below.","Storage growth → trivial (10 TB / 5 y). Partition by code hash only when the single node's write rate is exceeded — years away at this load."]],
["h","10 · Alternative designs"],
["ul",["Code generation A — random 7-char code, insert, retry on collision. Simple; collision rate negligible at 3.5 T space; no coordination.","Code generation B — database sequence → base62 encode. No collisions, but sequential codes are guessable (enumeration) and one sequence is a single writer.","Code generation C — pre-generated key service handing out batches of unused codes to each API server. No collisions, no guessability, one more component.","Redirect status — 301 (browser caches; fewer hits; no click data) vs 302 (every click reaches you; analytics possible; more load).","Store — relational (simple, sufficient) vs key-value/DynamoDB (scales writes without sharding decisions; loses ad-hoc queries)."]],
["h","11 · Component-by-component tradeoffs"],
["tbl",{cols:["Component","Why it exists","What it costs / alternative"],rows:[["CDN edge cache","Redirect latency for global users","Stale redirect for TTL after edit/delete; purge on delete"],["Redis cache","DB cannot serve 50k reads/s","New component; cold start sends load to DB; stampede on hot code expiry"],["Postgres","Source of truth; unique constraint on code","Single writer; fine for years; KV store if writes explode"],["Random codes","No coordination, not guessable","Rare collision retry; codes not sortable"],["Click event log","50k counter writes/s would melt a row","Counts are minutes stale; another system to run"],["302 not 301","Analytics require the hit","2× the redirect traffic a 301 would leave to browsers"]]}]
]},
{id:"shortener-cases",title:"URL shortener · 12–13 · concurrency, failure, security",blocks:[
["h","12 · Concurrency and failure cases"],
["ul",["Two creates pick the same random code → unique constraint; loser retries with a new code. Invariant: one code, one URL, forever.","Two users request the same custom alias → same constraint; second gets 409.","Create succeeds, response lost, client retries → idempotency key on POST /links, or the client sends a client-generated id; return the existing code.","Redirect for a code just deleted → cache still holds it for up to TTL; delete-on-write to the cache plus a CDN purge bound the window.","Cache down → all reads hit the DB at 50k/s; it dies. Mitigation: local in-process cache on each API server for the top codes; shed non-redirect traffic; DB read replicas as a second line.","Hot code (a link on a viral tweet) → single cache node saturates; replicate the key or rely on the in-process cache (every server holds it after one miss).","DB leader fails → promote a replica; creations fail for ~30 s; redirects continue from cache. Reads and writes fail independently — a stated requirement.","Counter flush worker dies → clicks buffered in cache are lost for that minute; acceptable, stated.","Expiry → redirect checks expires_at on the cached record; a nightly sweeper deletes rows and purges cache entries."]],
["h","13 · Security and abuse"],
["ul",["Malicious destinations (phishing) → validate URL scheme, check against a blocklist at creation and periodically, show an interstitial for flagged links.","Enumeration → random codes, not sequential; rate-limit 404s per IP.","Creation abuse → API key required; rate limit per key; CAPTCHA for anonymous web creation.","Open-redirect concerns → only redirect to stored URLs; never accept a destination in the query string.","Privacy → click logs contain IPs; hash or truncate; retention 90 days."]]
]},
{id:"shortener-final",title:"URL shortener · 14–16 · final design, weak answers, follow-ups",blocks:[
["h","14 · Interview-quality final design"],
["ex","Client\n  → CDN (caches 302s for popular codes, short TTL)\n  → LB → API servers (stateless; in-process LRU for top ~10k codes)\n       → Redis (cache-aside, code → {url, expires_at}; TTL 1 day)\n       → Postgres leader + 2 replicas (links; unique(code))\n  Create: random base62 code; INSERT ON CONFLICT; idempotency key\n  Redirect: local cache → Redis → DB; 302; emit click event\n  Clicks: event log → stream aggregator → clicks(code, day)\n  Expiry: check on read; nightly sweeper + cache purge\n  Ops: alert on redirect p99, cache hit rate, DB QPS, aggregator lag"],
["p","Spoken: 'A read-dominated system, so redirects are served from caches at three layers and the database only sees misses and writes. Random codes avoid coordination and enumeration. Click counting is asynchronous through an event log because a counter row would be the hottest thing in the system. Creation and redirect fail independently, which is what the availability requirement asked for.'"],
["h","15 · Common weak answers"],
["ul",["\"Hash the URL with MD5 and take the first 7 characters\" — collisions between different URLs; same URL always gets the same code (is that wanted?); no answer for custom aliases.","\"Increment a click counter in the database on every redirect\" — 50k writes/s on hot rows.","\"Shard the database\" at 100 writes/s — solving a problem you do not have; unable to name the shard key.","\"Use 301 for speed\" without noticing it kills the analytics requirement.","Drawing Kafka, Cassandra and a microservice mesh for a system that fits one database and a cache.","No answer for 'what if the cache goes down?'"]],
["h","16 · Follow-up questions to expect"],
["ul",["How would you support link editing? (Cache invalidation across three layers; versioned codes.)","How do you handle a link that goes viral in the next 60 seconds? (In-process cache, replicated hot key, CDN.)","How would you do this across three regions? (Codes are immutable — replicate freely; creation in one region or with region prefixes to avoid collisions.)","How do you guarantee a code is never reused after deletion? (Tombstone rows; never delete, only mark.)","How would you make analytics exact rather than approximate? (Event log with idempotent aggregation keyed by click id.)","What changes at 100× the write rate? (Key service with pre-allocated ranges; partition links by code hash; KV store.)"]],
["t","The final design is smaller than most candidates' first design. That is the point: every component is there because a numbered bottleneck forced it, and every alternative was named and rejected out loud."]
]}
]};
