const D = (name, o) => ["dec", { name, ...o }];
export default {id:"observability",num:"19",part:"VII · Keeping it running",title:"Observability and production operations",example:"a ride-hailing dispatch service",
tagline:"Metrics detect, traces localise, logs explain. Each signal and each SRE practice as a decision: when to use it, when not, what it costs.",
terms:["Metrics vs traces vs logs","Request ID","SLI / SLO / SLA","Error budget","Golden signals","Burn rate","Postmortem"],
objectives:["Pick the signal by the question it answers during an incident","Propagate a request id across services and queues","Define an SLI, set an SLO, derive the error budget and use it to make decisions","Alert on symptoms at two burn rates and not on causes","Close a deep dive with how you'd know it broke"],
sections:[
{id:"signals",title:"Which signal for which question",blocks:[
["p","A rider waits eleven seconds for a car at three in the morning. Four services were involved. Which one was slow, for how many people, and since when?"],
["p","If you cannot answer that in two minutes, the problem is not that you are missing a dashboard. It is that the ability to answer was never designed in — and it cannot be added during the incident."],
["p","There are three kinds of signal, and the useful way to hold them is by the question each one answers."],
["p","Metrics detect. They are cheap aggregates over time — request rate, error rate, p99, saturation — so you can keep them for everything, forever, and alert on them. What they cannot do is say anything about an individual request. A metric will tell you that pricing's p99 jumped at 03:10. It will never tell you which requests, or why."],
["p","Traces localise. A trace follows one request across every service it touched and shows where the time actually went: 1,840 milliseconds in pricing, forty milliseconds everywhere else. That is precisely the question metrics cannot answer."],
["p","Logs explain. Once you know it was pricing, the log lines for that request tell you what pricing was doing while it took 1,840 milliseconds."],
["p","Detect, localise, explain. Skip one and you get a characteristic failure. Only logs, and you find out about outages from users. Only metrics, and you know something is wrong but never where. Only traces, and you are sampling a system nobody is watching."],
["p","The thing that makes all three work together costs almost nothing and is forgotten constantly: a single request id, generated at the edge, attached to every log line, propagated on every outbound call — and, the step everyone misses, carried in the headers of every queue message."],
["p","A request that crosses a queue and loses its id becomes two unrelated stories, and the asynchronous half is exactly the half that is hard to debug."],
["p","One practical note on cost. Traces are sampled, because tracing every request costs more than serving it. Sample a small fraction of successful requests and keep every slow one and every error, since that is where the information was to begin with."],
D("Metrics — cheap numbers over time, for detecting problems",{say:"Response time at the 99th percentile, error rate, how loaded each machine is, and how many requests arrive — these are counters and averages we keep for everything and alert on.",
use:["Noticing that something is wrong, and paging somebody about it.","Anything you want to see as a graph over time."],
avoid:["Trying to answer questions about individual requests. Metrics are summaries; the individual requests are already gone.","Labelling metrics with something that has thousands of possible values, such as a user id. That is no longer a metric, it is a database, and it will cost like one."],
consider:["Label them with a few low-variety things: which service, which region, whether it succeeded.","A metric will tell you that pricing got slower at ten past three. It will never tell you which requests, or why."]}),
D("Traces — following one request across every service",{say:"Every hop carries the same trace identifier, including inside message headers, and we keep a small sample of normal requests plus every error and every slow one. The trace shows 1,840 milliseconds in pricing and forty everywhere else.",
use:["Any system with more than two services, or with a queue in the middle of a user-facing flow.","Working out which hop is responsible for the delay."],
avoid:["A single application, where an ordinary profiler does the same job better.","Recording every request. That costs more than serving them."],
consider:["Sample a percentage as requests begin, or decide after the fact and keep everything slow or failed. The second is more useful and more work.","Passing the identifier through a queue is the step everyone forgets, and the asynchronous half is exactly the half that is hard to debug."],
fails:"One service does not pass the identifier along. The trace ends there, and the problem in everything downstream becomes invisible."}),
D("Logs — the detail that explains what the metrics detected",{say:"Logs are written as structured records rather than sentences, each carrying the request identifier, sampled for ordinary requests and kept in full for every error.",
use:["Investigating a specific incident.","Audit trails, which belong in their own stream and are kept far longer."],
avoid:["Free text you can only search by guessing at wording.","Logging every request in full at high volume, which becomes one of your larger bills."],
consider:["The request identifier assigned at the edge is what ties a log line to a trace and a metric. Without it you have three separate systems that cannot be compared."]}),
["ex","Edge      X-Request-Id: r-8813\nDispatch  {req: r-8813, svc: dispatch}\nPricing   {req: r-8813, svc: pricing, dur_ms: 1840}\nQueue msg headers carry req\nNotifier  {req: r-8813, svc: notifier}\nOne search on r-8813 reconstructs the story."],
["t","Only logs: you learn about problems from users. Only metrics: you know something's wrong, not where. All three, and accept traces are sampled and logs cost."]
]},
{id:"slo",title:"SLIs, SLOs, SLAs and the error budget",blocks:[
["p","Now the harder question: what does working mean, stated precisely enough that a machine can page somebody about it?"],
["p","It means choosing one thing you measure, one target for it, and accepting the consequences of both."],
["p","The measurement is the SLI — the fraction of dispatch requests completing in under two seconds. Measure it at the edge, where the rider is, rather than inside your service where the numbers are more flattering and less true."],
["p","The target is the SLO, and this is where most teams go wrong. They pick 99.99% because it sounds professional. Each additional nine costs roughly ten times the last, and the rider's mobile network is nowhere near four nines, so you would be spending enormous sums improving something no user can perceive."],
["p","The SLA is a third, separate thing: what you promise customers contractually, with money attached. It should always be looser than your internal SLO, so that missing your own target is a warning rather than an invoice."],
["ex","SLI  fraction of dispatch requests completing under 2 s\nSLO  99.5% over 30 days\nSLA  99% to enterprise customers, with credits (looser than the SLO)\nBudget 0.5% ≈ 3.6 h of failing requests per 30 days"],
D("Setting the target — what counts as working",{say:"Ninety-nine and a half percent of dispatch requests under two seconds. Not four nines: each additional nine costs roughly ten times the last, and the rider's mobile network is nowhere near that anyway.",
use:["One or two targets per service, based on something the user actually experiences."],
avoid:["Targets chosen because the number sounds impressive rather than because users can tell the difference.","An internal target looser than what you have promised customers contractually. That guarantees you break the promise before you notice."],
consider:["Pick a percentile of response time, a success rate, or how fresh the data is. Measure it at the edge, where the user is, not inside the service where the numbers flatter you."]}),
["p","Subtract the SLO from a hundred percent and you have the error budget: half a percent of thirty days, which is about three and a half hours of failing requests you are permitted to spend."],
["p","That number exists to change conversations, and that is genuinely its main purpose. Budget remaining means ship the risky migration this week. Budget exhausted means launches pause until reliability recovers. Outages and risky deploys draw down the same account, which is the honest way to describe reality."],
["p","And because the number was agreed in advance by product and engineering together, the argument at three in the morning is about what to do rather than about whether reliability matters at all. That is a much better argument to be having at three in the morning."],
D("Error budget — permission to take risks, in numbers",{say:"If we are within budget, ship the risky migration this week. If we have spent it, launches pause until reliability recovers. Product and engineering agreed the number in advance, so the argument at three in the morning is about what to do rather than whether it matters.",
use:["Every decision that trades reliability against speed of delivery."],
consider:["Subtract the target from a hundred percent. Half a percent of thirty days is about three and a half hours of failing requests you are allowed.","Outages and deliberate risky changes draw on the same allowance, which is the honest way to describe reality.","Put the remaining balance on the dashboard, or nobody will believe it is real."]}),
["tbl",{cols:["Nines","Downtime / year","Downtime / month"],rows:[["99%","3.65 days","7.3 h"],["99.9%","8.8 h","44 min"],["99.99%","53 min","4.4 min"],["99.999%","5.3 min","26 s"]]}]
]},
{id:"alerting",title:"Golden signals and alerting that gets read",blocks:[
["p","Four signals are worth watching on everything, with one refinement: measure latency for successful and failed requests separately. A fast error is not good latency, and averaging the two together can make an outage look like an improvement."],
["tbl",{cols:["Signal","Measure","Use"],rows:[["Latency","p99, split by success/failure","A fast error isn't good latency"],["Traffic","rps, rides/min","Context for everything else"],["Errors","5xx, wrong 200s, over-SLO responses","The symptom users feel"],["Saturation","CPU, memory, pool, queue depth","Predicts the other three"]]}],
["p","Then the single rule that decides whether your alerts get read at all: page on symptoms, not causes."],
["p","CPU at ninety percent is a cause. It might mean trouble. It might mean you are finally using the hardware you paid for. If it wakes somebody at three in the morning and everything turns out to be fine, they will learn — correctly — that the pager lies, and within a month they will be silencing it during real incidents."],
["p","Requests failing their SLO is a symptom. It always matters, because by construction it is the thing the user is experiencing."],
["p","Two burn rates, because outages arrive in two shapes. A fast burn — at this rate the whole month's budget is gone within hours — pages immediately. A slow burn — gone in weeks — opens a ticket for working hours. Without the first, a sharp outage goes unnoticed for an hour. Without the second, a persistent low-grade problem never gets fixed because it never quite crosses a line."],
["p","And review every page you send. Was it actionable? If it was not, delete the alert. An alerting system nobody trusts is worse than no alerting system, because it costs sleep and buys nothing."],
D("Alert on what users feel, at two different speeds",{say:"A fast alert when the month's allowance would be gone within hours. A slower ticket when it would be gone within weeks. Alerts about causes, like processor usage, go to dashboards and never to a pager.",
use:["Every service that has a target."],
avoid:["Paging on causes. Processor usage at ninety percent might be a problem or might be efficiency. Wake somebody for it once and they learn the pager lies, and within a month they will silence it during a real incident.","Only having the slow alert, which lets a sharp outage run unnoticed for an hour."],
consider:["Review every page you send. Was it actionable? If not, delete the alert.","A good dashboard answers is it us or a dependency within ten seconds: the four core signals, the target, the remaining allowance, and the health of everything you depend on."]})
]},
{id:"operations",title:"Capacity, incidents, postmortems",blocks:[
["p","Two practices and one closing habit."],
["p","Capacity planning is mostly a matter of noticing that some spikes are on a calendar. New Year's Eve is six times a normal Friday for dispatch. That is knowable weeks ahead, which makes it a provisioning decision rather than an incident. Provision with headroom for losing a zone at peak, and let the saturation signal tell you where the forecast was wrong."],
["p","Incident response works better with roles than with heroics. One person is the incident commander and decides; others investigate and communicate. Mitigate first — roll back, fail over, shed load — and find the root cause afterwards. The instinct to understand before acting is a good engineering instinct that costs users real minutes."],
["p","And the postmortem is blameless not because blame is impolite but because it is inaccurate. The engineer who ran the command was the last link in a chain that permitted it. Stop at them and the chain is still there, and the next person will find it."],
["p","Write what happened minute by minute, what users experienced, why the system allowed it, and what changes — with owners and dates. An incident without a postmortem is an incident you have quietly agreed to have again."],
D("Capacity planning — some spikes are on a calendar",{say:"New Year's Eve is six times an ordinary Friday for dispatch. That is knowable weeks ahead, so we add capacity in advance with enough headroom to lose an availability zone at peak.",
use:["Growth forecasts, launches and seasonal peaks — anything with weeks of warning."],
consider:["Load tests tell you whether the forecast translates into machines correctly.","Headroom means peak demand plus the loss of your largest single failure domain, not peak demand exactly."]}),
D("Incident response — roles beat heroics",{say:"One person is in charge and makes decisions; others investigate and communicate. Stop the bleeding first — roll back, fail over, shed load — and find the cause afterwards. Someone keeps a timeline as it happens.",
use:["Every page."],
avoid:["Several people acting independently with no one deciding.","Diagnosing the root cause while users are still affected. The instinct to understand before acting is a good engineering instinct that costs real minutes here."]}),
D("Postmortem — what happened, and what changes",{say:"A minute-by-minute timeline, the impact described in terms of what users experienced, why the system permitted it, and what we are changing — with named owners and dates. Never who.",
use:["Every incident that consumed a meaningful part of the allowance."],
avoid:["Postmortems with no actions, which produce a well-documented history of the same incident happening repeatedly."],
consider:["Blameless is not politeness, it is accuracy. The person who ran the command was the last link in a chain that allowed it. Stop at them and the chain is still there for the next person to find.","An incident without a postmortem is an incident you have agreed to have again."]}),
["ex","Closing a deep dive\n\"We trace every dispatch request end to end, page on a fast burn of\nthe 2-second SLI, watch saturation on the location index — it fails\nfirst under load — and plan New Year's Eve at 6× a normal Friday.\""]
]}
]};
