export default {id:"ambiguity",num:"24",part:"VIII · Putting it together",title:"Handling ambiguity and case coverage",example:"\"Design YouTube\"",
tagline:"Reducing a vague prompt to a decidable problem, then covering the seven kinds of case that distinguish strong candidates — worked through the two words 'Design YouTube'.",
terms:["Product scope","Data semantics","System guarantees","Invariant","Concurrency case","Hotspot","Lost response","Abuse case","Requirement → consequence"],
objectives:["Shrink a vague prompt along the five dimensions of ambiguity and state what you chose","Translate each requirement into an engineering consequence rather than a component name","Enumerate the seven kinds of case for any workflow and name the invariant concurrency must protect","Run the eight-minute pre-design drill on a new system without prompting"],
sections:[
{id:"space-of-questions",title:"A prompt is a space of questions",blocks:[
["p","'Design YouTube' is not a question. It is a space of thousands of possible questions — upload, playback, search, recommendations, comments, live streaming, monetisation, moderation — each of which is a forty-minute design on its own. Candidates who start drawing immediately design the average of all of them, which is none of them. The skill is to shrink the space fast, out loud, along dimensions you can name, and then to design the problem that remains."],
["p","Knowing Redis and Kafka is not enough if you design the wrong product. Ambiguity handling is the first thing a strong interviewer watches for, and it is a skill that can be trained like any other."]
]},
{id:"five-dimensions",title:"The five dimensions of ambiguity",blocks:[
["h","1. Product scope"],
["p","Who are the users? Which two or three workflows are core? Are we designing the whole product or one path through it? What is explicitly out? For YouTube: 'Should I focus on upload, processing and playback, or also search, recommendations, comments and live?' Then narrow: 'I'll take upload, processing and playback; recommendations and comments are out of scope.'"],
["h","2. Scale"],
["p","Daily users, reads and writes, the read/write ratio, average object size, geographic spread, spikes. If the interviewer gives nothing, state assumptions: 'I'll assume a billion monthly viewers, a few hundred uploads a second, and playback traffic several orders of magnitude larger.'"],
["h","3. Data semantics"],
["p","Can it be edited or deleted? Does ordering matter? Can duplicates exist? How long is it retained? Who may see it? What are the dominant access patterns? For video: can a creator replace a video after publishing? Are private and unlisted videos in scope? Is the original retained after transcoding?"],
["h","4. System guarantees"],
["p","Strong or eventual consistency, and for which operation? Expected latency and availability? Can an operation be processed more than once? What happens when a dependency fails? For YouTube: a new upload may take minutes to appear (eventual); playback must start in under two seconds (latency); view counts may be approximate (eventual, even approximate)."],
["h","5. Constraints and priorities"],
["p","Latency, availability, consistency or cost — which wins? Single-region or global? Legal or privacy constraints? Managed infrastructure allowed? Which component should we go deepest on? This last question is the one that tells you how to spend the fifteen deep-dive minutes."],
["ex","A strong opening, in one breath\n\"Before designing, I'd like to clarify scope and the key constraints.\nWho are the primary users, which two or three workflows should we\nprioritise, what scale should I assume, and do we favour consistency\nor availability for the critical operation?\"\n\nThen, having heard the answers:\n\"I'll focus on upload and playback, assume 500 uploads/s and 50 M\nconcurrent viewers, accept minutes of delay before a video is live,\nand require that a published video is never served with the wrong\ncontent.\""],
["t","Ask questions whose answers materially change the design. Interrogating the interviewer for fifteen minutes signals that you cannot make decisions; asking nothing signals that you do not know which decisions matter."]
]},
{id:"requirements-consequences",title:"Turning requirements into consequences",blocks:[
["p","This is the mental step that separates candidates who know components from candidates who design. A requirement is not a reason to add a box; it is a constraint that a specific mechanism satisfies. State the constraint, then the mechanism, then the tradeoff."],
["ul",["Global low-latency playback → CDN with regional edge caches; origin in object storage; adaptive bitrate so the first segment is small.","Uploads of multi-gigabyte files → multipart upload directly to object storage with presigned URLs; the API never proxies bytes.","Processing takes minutes and must not block the upload → durable job in a queue; workers process asynchronously; status field on the video record.","A published video must never serve the wrong content → immutable, content-addressed output paths; publish is a single atomic pointer update.","View counts on a viral video → approximate, sharded counters flushed periodically; never an increment on one row per view.","Strictly ordered messages (a chat product) → per-conversation sequence numbers.","Never charge twice (a payments product) → idempotency keys and a durable transaction record.","Never oversell a seat (a ticketing product) → transaction, conditional write or reservation with expiry.","Keep working when a dependency fails → queue, cached fallback or graceful degradation, decided per dependency."]],
["ex","Weak:   \"Let's add Kafka because we need scale.\"\nStrong: \"Transcoding takes several minutes and shouldn't block the\n        upload request, so I'll put a durable job in a queue and\n        let a pool of GPU workers process it. The cost is that the\n        creator sees 'processing' for a while, so the video record\n        needs a status and the UI needs to show it.\""],
["t","Every component in the diagram should be traceable to a sentence that starts with a requirement and ends with a tradeoff. If you cannot produce that sentence for a box, erase the box."]
]},
{id:"seven-cases",title:"The seven kinds of case",blocks:[
["p","Once the scope is set, walk every important workflow through seven categories. The first is what everyone does; the last five are where strong candidates separate themselves."],
["h","1. Happy path"],
["p","The normal flow, first and explicitly. Upload: client requests an upload URL; bytes go to object storage; API records the video as UPLOADED; a job is enqueued; workers transcode; the record flips to READY; the creator is notified. Establish this before anything else, or the edge cases have nothing to be edges of."],
["h","2. Alternate paths"],
["p","Other valid ways the same operation happens. The creator uploads from a browser instead of a phone. The video is scheduled for later publication. It is unlisted. It replaces an existing video. It has captions attached. You will not design all of them; acknowledging them shows you see the whole surface."],
["h","3. Edge cases"],
["p","Zero-byte upload. A file over the size limit. A video deleted while a viewer is mid-playback. Two creators choosing the same custom URL. A notification referring to a video that has since been removed. A user deleted while their upload is processing."],
["h","4. Concurrency"],
["p","Two operations at once. The creator replaces a video while a transcode of the previous version is in flight — which output wins? Two workers pick up the same job. A viewer's 'like' and 'unlike' arrive out of order. Ask: what invariant must remain true no matter how operations interleave? For YouTube's publish step: a video URL serves exactly one version's content, never a mix. For Ticketmaster: one seat, one confirmed owner."],
["h","5. Scale and hotspots"],
["p","One video goes globally viral; one creator's upload is a live event millions are waiting for; one partition holds today's uploads; one cache key is read a million times a second. This is where caching, replication of hot keys, salting, load shedding and fan-out strategies enter — as answers to a named hotspot, not as decoration."],
["h","6. Failure"],
["p","For every network call, the four outcomes (Chapter 18): success, failure, success with the response lost, still running at timeout. The lost response is the one to name: the transcode finished, the status update was lost; the payment succeeded, the confirmation did not. Then the infrastructure failures: database unavailable, cache unavailable, worker crashes mid-job, queue backlog, region outage, replication lag, half-finished deploy. Each has a mechanism: idempotency, deduplication, retries with backoff, transactional outbox, dead-letter queues, reconciliation."],
["h","7. Abuse and security"],
["p","Unauthorised access to a private video. Spam uploads. Bots inflating view counts. Malicious files. Account enumeration. Rate-limit evasion. Data leaking between channels. A user repeatedly requesting the most expensive operation. Each is a scale problem with an adversary and a security problem with a design consequence."],
["ex","Case-coverage checklist — run it on every important workflow\nNORMAL    what is the read/write path?\nDATA      where is the source of truth? which indexes serve which\n          access patterns?\nCONCUR    can two operations conflict? what invariant is protected,\n          and by which mechanism?\nFAILURE   what if the request times out halfway? is retry safe?\nSCALE     what is the bottleneck? which key, user or partition\n          becomes hot?\nSECURITY  who is authorised? how is this operation abused?\nOPS       how do we observe it, and how do we recover?"],
["t","Covering all seven for every workflow takes an hour you do not have. Cover all seven for the one critical workflow and name the categories for the others — the interviewer wants to see the habit, not the exhaustive list."]
]},
{id:"case-families",title:"The thirteen case families",blocks:[
["p","The seven categories are the habit; these thirteen families are the checklist. For each one: the question to ask, the mechanism that usually answers it, and how it shows up in the running example."],
["tbl",{cols:["Family","Ask","Mechanism"],rows:[
["Happy path","What is the normal read/write flow, end to end?","Trace it across the diagram first"],
["Alternate valid path","What other legitimate ways does this happen?","Same model; name them, design one"],
["Invalid input","Empty, oversized, malformed, wrong type, deleted target?","Validate at the boundary; 4xx with a code"],
["Concurrent operations","Two at once on the same object — which invariant must hold?","Unique constraint, conditional write, lock with fencing"],
["Duplicate operations","Same request twice — double-click, retry, redelivery?","Idempotency key; idempotent consumer"],
["Partial failure","Step 2 of 4 fails — what state is left?","Transaction if one DB; saga + PENDING state if not"],
["Retry after unknown outcome","Response lost — did it happen?","Idempotency + reconciliation against the truth"],
["Traffic spike","10× in a minute — what breaks first?","Queue, shed load, pre-scale, cache at edge"],
["Hot user / key / partition","One object gets most traffic?","Replicate hot key, salt, in-process cache, better shard key"],
["Regional failure","A region disappears — RPO/RTO?","Multi-zone default; multi-region only if justified"],
["Malicious usage","Bots, scraping, enumeration, expensive requests?","Rate limits, cost quotas, object-level authz, audit log"],
["Data deletion & privacy","Delete a user — where does their data live?","Delete across replicas, caches, indexes, backups; retention policy"],
["Deployment & schema migration","New column, new version, half the fleet upgraded?","Additive migrations; dual-write/backfill; version-tolerant consumers"]]}],
["ex","YouTube upload, run through the families\nInvalid input      zero-byte file, 50 GB file, .exe renamed .mp4\nConcurrent         creator replaces a video mid-transcode → version\n                   the outputs; publish is a pointer swap\nDuplicate          client retries the 'complete upload' call → idempotent\n                   on upload_id\nPartial failure    transcode 3 of 6 renditions done, worker dies → job\n                   idempotent per rendition; resume, don't restart\nUnknown outcome    status update lost → reconcile READY from storage\nSpike              10 M uploads after a trend → queue depth grows; shed\n                   4K rendition first\nHot key            one viral video → CDN + replicated cache entry\nRegional failure   originals in multi-region object storage; metadata\n                   replicated async; RPO minutes\nMalicious          copyright uploads, bot views → moderation stage,\n                   approximate counters resistant to inflation\nDeletion           delete video → originals, renditions, thumbnails,\n                   search index, CDN purge, analytics\nMigration          new 'chapters' field → additive; old players ignore it"],
["t","Running all thirteen on every workflow takes an hour. Run all thirteen on the one critical workflow, then say 'the same families apply to the other flows' — the interviewer wants the habit, not the list."]
]},
{id:"training",title:"Training the skill",blocks:[
["p","For every practice problem, spend the first eight minutes without designing anything. Write, in this order:"],
["ul",["The main users.","Three functional requirements.","Three non-functional requirements.","A scale estimate with one consequence each.","The single most important invariant.","Three failure cases.","One concurrency case.","One hotspot.","What is explicitly out of scope."]],
["ex","Eight minutes before designing Ticketmaster\nUsers:        fans buying; promoters listing events\nFunctional:   search events; view available seats; reserve and buy a seat\nNon-func:     no double-sale, ever; seat map < 500 ms; survive a\n              10 M-user on-sale\nScale:        one event, 50k seats, 10 M attempts in 10 min → 17k/s\n              on one partition → waiting room + cache, not raw DB\nInvariant:    one seat cannot have two confirmed owners\nFailure:      payment succeeds, our service times out → reconcile\nConcurrency:  two users reserve the same seat in the same ms\nHotspot:      one event's seat map at on-sale time\nOut of scope: event creation, recommendations, resale"],
["p","Do this for twenty or thirty systems and the recurring shapes stop hiding: the contention problem (tickets, inventory, ride assignment), the fan-out problem (feeds, group chat, notifications), the large-object problem (video, files, backups), the ordering problem (chat, logs, ledgers), the search problem, the asynchronous-processing problem. A new prompt becomes a recognition task, and the forty minutes become a matter of saying what you already see."],
["t","Practising designs without the eight-minute drill trains you to draw faster. Practising the drill trains you to draw the right thing. Only the second one transfers to a prompt you have never seen."]
]}
]};
