export default {id:"plan",num:"25",part:"VIII · Putting it together",title:"Practice systems and the 12-week plan",example:"your own study calendar",
tagline:"What to build, in what order, and how to spend the weeks — worked through the calendar you will actually follow.",
terms:["URL shortener","Rate limiter","Notification service","News feed","Job scheduler","Payment platform","Ticketmaster","Timed practice","DDIA","SRE book"],
objectives:["Sequence the practice systems from beginner to advanced and say what each one teaches","Answer the eight standing questions for any system you have practised","Follow a twelve-week plan that alternates learning with designing aloud","Use the primary sources — DDIA, the SRE books, the Builders' Library — rather than question banks alone"],
sections:[
{id:"systems",title:"Systems to practise, and what each teaches",blocks:[
["h","Beginner"],
["ul",["URL shortener — key generation, read-heavy caching, redirects, the first hot key. (the running example in Chapters 03–05.)","Pastebin — large-ish objects, object storage versus database, expiry.","Rate limiter — token buckets, distributed counters, the choice between accuracy and coordination.","Notification service — fan-out, multiple channels, retries, deduplication, user preferences.","File storage (Dropbox-lite) — chunking, deduplication, sync, metadata versus bytes."]],
["h","Intermediate"],
["ul",["Twitter/X feed — fan-out on write versus read, the celebrity problem, timeline caches. (Chapter 23's example.)","Instagram — feed plus media pipeline plus a social graph.","WhatsApp — WebSockets, ordering, offline delivery, receipts, group fan-out.","YouTube — multipart upload, transcoding queue, CDN, adaptive bitrate, approximate counters. (Chapter 24's example.)","Web crawler — politeness, deduplication, frontier prioritisation, a very large queue.","Search autocomplete — tries, prefix indexes, query-log aggregation, memory budgets.","Distributed cache — consistent hashing, replication, eviction, hot keys. (Chapters 12 and 13 together.)","Job scheduler — time-indexed storage, leases, leader election, idempotent jobs."]],
["h","Advanced"],
["ul",["Uber — geo-indexing, a huge ephemeral write stream, matching as a contention problem.","Google Docs — real-time collaboration, OT/CRDTs, presence, permissions.","Dropbox at scale — block storage, sync conflicts, bandwidth optimisation, versioning.","Payment platform — idempotency, ledgers, sagas, reconciliation, fraud. (Chapters 09, 16 and 22.)","Metrics and logging platform — time-series ingestion, cardinality, downsampling, retention, query fan-out.","Ticketmaster — the purest contention problem; waiting rooms; the seat invariant.","Distributed message queue — you build Chapter 17: partitions, replication, offsets, delivery guarantees.","Google Search — crawling, inverted indexes at planetary scale, ranking, index partitioning.","Production ML inference platform — feature stores, model serving, batching, canaries, drift."]],
["h","The eight standing questions"],
["p","For every system on the list, be able to answer without hesitation: What are the access patterns? Where is the source of truth? What gets cached? What gets partitioned, and by what key? What consistency does the critical operation require? What can fail, and what happens then? What happens under overload? Why this design rather than the main alternative?"],
["t","Doing thirty systems shallowly teaches vocabulary. Doing fifteen with all eight questions answered teaches design. The list is long so that you can choose, not so that you can finish it."]
]},
{id:"twelve-weeks",title:"The twelve weeks",blocks:[
["ul",["Weeks 1–2 · Foundations — what system design is, users and requirements, how a system is measured, how a request travels, and what one server does with it. Read Chapters 01–05. Practise: URL shortener, Pastebin.","Weeks 3–4 · Data — choosing a store, modelling and indexes, transactions and the one airtight operation. Read Chapters 06–08. Practise: file storage, ticket booking.","Weeks 5–6 · Interfaces and growth — API design, real-time delivery, service boundaries, load balancing and caching. Read Chapters 09–13. Practise: notification service, job scheduler.","Weeks 7–8 · Distribution — replication, partitioning, consistency models, consensus, queues and asynchronous work. Read Chapters 14–17. Practise: WhatsApp, payment platform.","Weeks 9–10 · Running it, and the patterns — reliability, observability, security, estimation, then feeds, search, media, location and production ML. Read Chapters 18–22. Practise: Twitter, YouTube, Uber, Google Docs.","Weeks 11–12 · Execution — two timed 40-minute designs a week on the framework in Chapter 23, using the ambiguity drill in Chapter 24 for the first eight minutes of each. Record yourself. Afterwards, list every component you drew but could not fully justify, and every case category you skipped."]],
["h","The weekly rhythm"],
["p","Roughly 40% learning fundamentals, 40% designing systems aloud, 20% reading real architectures and postmortems. One chapter's worth of reading, one or two full designs spoken out loud to a wall or a friend, and one engineering blog post or incident report from a company that runs the thing you just designed."],
["t","Reading without designing produces someone who can critique a design and cannot produce one. Designing without reading produces confident, plausible, wrong answers. The alternation is the method."]
]},
{id:"materials",title:"Materials and how to use them",blocks:[
["ul",["Designing Data-Intensive Applications (Kleppmann) — the definitive text for storage engines, replication, partitioning, transactions, consistency and stream processing. Read Chapters 2–9 and 11 closely; they map onto Chapters 06–08, 16 and 17 here.","Google's SRE books (Site Reliability Engineering; The Site Reliability Workbook) — free online. Monitoring distributed systems, handling overload, addressing cascading failures, managing critical state (consensus), postmortem culture. They are the source of Chapters 18 and 12.","The AWS Builders' Library — short, practical articles by AWS engineers: timeouts, retries and backoff with jitter; avoiding fallback; caching challenges; leader election; workload isolation with shuffle sharding. The best treatment of retries that exist.","Official documentation — PostgreSQL (transactions, isolation, indexes), Redis (data types, cache patterns, eviction), Kafka (design section: partitions, replication, delivery semantics). Read the design rationale sections, not just the API reference.","Engineering blogs and postmortems — how the systems on the practice list are actually built, and how they actually failed. One a week.","Interview question collections — for practice prompts and to calibrate depth, never as the primary source of knowledge; they teach the answers without the reasons."]],
["h","If you have implementation experience"],
["p","Then the gap is not knowledge of components. It is the habit of connecting a requirement to a decision and saying the tradeoff out loud — the sentence 'because we need X, I choose Y, at the cost of Z'. Start with databases, then caching, then queues, then reliability, then the product architectures, and practise the sentence until it is reflexive. That is where the improvement is, and it is faster than it looks."],
["ex","The sentence to practise until it is automatic\n\"Because [requirement], I'll use [mechanism]; the cost is [tradeoff],\nwhich is acceptable here because [reason]. The alternative was\n[other mechanism], which is better when [condition].\""]
]}
]};
